lib/*: Add syscall interfaces for dotnet runtime
unikraft/unikraft pull request #1004
Opened 2023-07-25 17:34 UTC by i-Pear

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Description of changes

Stub the following syscall interfaces for `dotnet runtime 7.0`:

- `posix-mmap`: `SYS_mlock` and `SYS_msync`
- `uksched`: `SYS_sched_getaffinity` and `SYS_sched_setaffinity`
- `vfscore`: `SYS_mknodat`

2023-07-25 19:34 UTC, StefanJum requested changes
Thank you for this @i-Pear.
Please add a `UK_WARN_STUBBED()` in the stubbed syscalls (see an example [here](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/main.c#L2598)) and wrap the commit messages to ~50 characters per line.

Also, does the `dotnet` require the syscalls to return success? If not I would do an `errno = ENOTSUP; return -1` where it is the case.

2023-07-26 09:58 UTC, i-Pear commented
@StefanJum Thanks for your review. `msync` doesn't need to return success, so I changed it to `-ENOTSUP`. But others must `return 0` to make prevent the `dotnet runtime` from crashing.

2023-07-26 10:06 UTC, mschlumpp commented
> `msync` doesn't need to return success, so I changed it to `-ENOTSUP`.

I think we should return zero from `msync`. It's unlikely that it breaks anything and we don't run into issues where software only checks for the documented error codes.

2023-07-26 10:11 UTC, StefanJum commented
> I think we should return zero from `msync`. It's unlikely that it breaks anything and we don't run into issues where software only checks for the documented error codes.

Agree. I was a bit worried about the `mknodat` returning 0, the others I doubt will matter that much.

2023-07-26 10:38 UTC, i-Pear commented
Changed `msync` to return zero.
The `mknodat` is for the dotnet runtime to create `/tmp/clr-debug-pipe`, seems to be pipes for connecting to the debugger.

2023-07-26 10:47 UTC, i-Pear commented
I found that adding env `COMPlus_EnableDiagnostics=0` can prevent creating these debug pipes. So just assert users will add this env, and remove `mknodat` from this PR? @StefanJum 

However, I realize that the design of debugging through pipes is quite interesting. This means that we might be able to debug `dotnet` programs in unikernels, which is challenging to achieve with other languages.

2023-07-26 10:55 UTC, StefanJum commented
> I found that adding env `COMPlus_EnableDiagnostics=0` can prevent creating these debug pipes. So just assert users will add this env, and remove `mknodat` from this PR? @StefanJum

Yes, I think that would be safer than stubbing `mknodat`, just have the users set the env variable in the elfloader config. 
Any thoughts @mschlumpp @razvand?

@i-Pear if this is selectable (via an env variable), could there be a way to completely disable it in the dotnet configuration step?

> However, I realize that the design of debugging through pipes is quite interesting. This means that we might be able to debug `dotnet` programs in unikernels, which is challenging to achieve with other languages.

That would be nice indeed, it would require a proper implementation of `mknodat` though.

2023-07-26 11:06 UTC, i-Pear commented
> if this is selectable (via an env variable), could there be a way to completely disable it in the dotnet configuration step?
Do you mean build our own dotnet framework? I think it will be easy to modify the default value in the source code, if you think this is worth. As the number of applications grows, we might find ourselves in need of developing our own package manager to effectively manage them.

2023-07-26 11:13 UTC, StefanJum commented
> Do you mean build our own dotnet framework? I think it will be easy to modify the default value in the source code, if you think this is worth. As the number of applications grows, we might find ourselves in need of developing our own package manager to effectively manage them.

We do have (or soon will have, I don't think there are any merged yet) dynamic apps that are build from source ([this pr for example](https://github.com/unikraft/dynamic-apps/pull/57/files#diff-a8c34384afd52ef0dfa5103b88b39b39d6c41971e1aadc88dfaf509906e71d25)).
I think we could do the same here, provide a script that does everything, and in the end have 2 versions in the `dynamic-apps` repo, the one you opened a pr for, already built, where you will need to set the env variable, and the one that will be build from source.

In the meantime, we'll just state in the `dynamic-apps/lang/c-sharp/README.md` file that `COMPlus_EnableDiagnostics=0` needs to be set.

2023-07-26 11:20 UTC, StefanJum requested changes
Looks fine @i-Pear, just one more comment below.

2023-07-26 11:20 UTC, StefanJum commented on lib/uksched/Makefile.uk
> +UK_PROVIDED_SYSCALLS-$(CONFIG_LIBUKSCHED) += sched_yield-0 sched_getaffinity-3 sched_setaffinity-3
Add these on separate lines (like you did in the `lib/posix-mmap/Makefile.uk` file)

2023-07-26 12:00 UTC, i-Pear commented
> Looks fine @i-Pear, just one more comment below.

Fixed. Besides, while porting `ASP.NET`, I found it uses `sched_getaffinity` to get `ncpus`, and the ret val must > 0, which cost me a lot of time. I think it would be better to return a positive value, while not having imported the `affinity` related functions and headers.

2023-07-26 12:32 UTC, i-Pear commented
> I think we could do the same here, provide a script that does everything, and in the end have 2 versions in the `dynamic-apps` repo, the one you opened a pr for, already built, where you will need to set the env variable, and the one that will be build from source.

It works. For backup:
- Change [EXTERNAL_EnableDiagnostics](https://github.com/dotnet/runtime/blob/ef3fd8523ddc69e4f508df2d1875b088e2ee3833/src/coreclr/inc/clrconfigvalues.h#L167) 's default value to `0`.
- And overwrite `build/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/libcoreclr.so` to `/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.7/libcoreclr.so`

2023-07-26 13:11 UTC, StefanJum commented
> It works. For backup:
> 
>     * Change [EXTERNAL_EnableDiagnostics](https://github.com/dotnet/runtime/blob/ef3fd8523ddc69e4f508df2d1875b088e2ee3833/src/coreclr/inc/clrconfigvalues.h#L167) 's default value to `0`.
> 
>     * And overwrite `build/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/libcoreclr.so` to `/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.7/libcoreclr.so`

Perfect, if it's just the `libcoreclr.so` we need to modify I saw we just overwrite that in the pr you opened on `dynamic-apps`.
We can still document the change in a README file.

2023-07-26 13:51 UTC, i-Pear commented
> Perfect, if it's just the `libcoreclr.so` we need to modify I saw we just overwrite that in the pr you opened on `dynamic-apps`. We can still document the change in a README file.

Done, the readme is here: https://github.com/unikraft/dynamic-apps/pull/60/files

2023-07-26 16:36 UTC, i-Pear commented
I realized that unikraft doesn't support swap memory, so `mlock` doesn't make sense. Moreover, according to the description in [1], unikraft also doesn't support saving mmap data to file, causing `msync` also to be meaningless, it can simply return 0.

[1] https://github.com/unikraft/unikraft/blob/staging/lib/ukvmem/vma_file.c#L230

2023-07-26 17:23 UTC, i-Pear commented
It also seems that unikraft only supports running on a single cpu. I tried to run qemu with `-smp 4` but only one core is used. If so, `sched_getaffinity` and `sched_setaffinity` also seems meaningless -- there's only one cpu available.

2023-07-28 07:55 UTC, StefanJum commented
> It also seems that unikraft only supports running on a single cpu. I tried to run qemu with `-smp 4` but only one core is used. If so, `sched_getaffinity` and `sched_setaffinity` also seems meaningless -- there's only one cpu available.

Yes, that's being worked on, but we can go for the implementation you provided for now.

2023-07-28 07:58 UTC, StefanJum requested changes
Few more comments @i-Pear, it looks fine besides those.

2023-07-28 07:58 UTC, StefanJum commented on lib/uksched/Makefile.uk
> +UK_PROVIDED_SYSCALLS-$(CONFIG_LIBUKSCHED) += sched_getaffinity-3 sched_setaffinity-3
```suggestion
UK_PROVIDED_SYSCALLS-$(CONFIG_LIBUKSCHED) += sched_getaffinity-3 
UK_PROVIDED_SYSCALLS-$(CONFIG_LIBUKSCHED) += sched_setaffinity-3
```

2023-07-28 07:58 UTC, StefanJum commented on lib/uksched/sched.c
> +UK_SYSCALL_R_DEFINE(int, sched_getaffinity, int, pid, long, cpusetsize, unsigned long*, mask)
Wrap this to ~80 characters.
```suggestion
UK_SYSCALL_R_DEFINE(int, sched_getaffinity, int, pid, long, cpusetsize,
                                           unsigned long*, mask)
```

2023-07-28 07:58 UTC, StefanJum commented on lib/uksched/sched.c
> +UK_SYSCALL_R_DEFINE(int, sched_setaffinity, int, pid, long, cpusetsize, unsigned long*, mask)
Same as above, wrap this line to ~80 characters

2023-07-28 10:13 UTC, i-Pear commented
> Few more comments @i-Pear, it looks fine besides those.

Thanks, these have benn fixed.

2023-07-30 08:08 UTC, StefanJum approved these changes
All good now, thank you @i-Pear.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-07-30 13:12 UTC, RaduNichita requested changes
All good with me.

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

2023-07-30 13:12 UTC, RaduNichita approved these changes

2023-08-03 16:13 UTC, i-Pear commented
@razvand This has been ready to be merged.

2023-08-05 05:43 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-08-07 14:19 UTC, closed without merging