plat: Let coalescing method ensure memregion alignment
unikraft/unikraft pull request #1060
Opened 2023-08-21 07:43 UTC by mogasergiu

### Prerequisite checklist

 - [ ] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [ ] Tested your changes against relevant architectures and platforms;
 - [ ] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [all]
 - Platform(s): [all]
 - Application(s): [all]

### Additional configuration

### Description of changes

In order to preserve alignment among memory region descriptors, we
would strive to align every manually inserted memory region. However,
this would also rely on the boot protocol itself to report initial aligned
memory regions, which seems not be the case for some boot protocols
(e.g. cmdline may not be aligned in `Multiboot1`, `initrd` start
address may not be aligned in Linux Boot Protocol).

Therefore, write a single, centralized solution, inside the memory
region coalescing function and make it handle misalignment cases
as well to cope with misbehaving boot protocols. To guarantee
alignment, take each memory region, align it to both ends and
then resolve overlappings. Just like before, free memory regions
are trimmed in favor of other types of memory regions. We know
free memory regions will always be aligned because resolving
conflicts between aligned memory region descriptors will always
yield aligned memory regions.

To preserve original sizes of user allocated memory region descriptors,
in case a deletion is not detected, restore the start address and
length of such region and make sure that the `vbase` field stays updated
with new values of `pbase`.

Finally, now that we offload alignments to the newly improved coalescing
method, remove manual, hardcoded alignments from early boot glue code.
If everything goes as planned and is implemented in a manner where
expectations are met, these alignments should not be needed as they
are transparently ensured by the coalescing method as well as the
paging initialization.

NOTE: Re-adjust the other parts of the code that are a client of the memregion
API's to throw an exception if a memregion is not already aligned. From now on,
client code of such API shall not attempt to align received memory regions,
but rather throw an exception if that has not happened already. This way we
will be able to catch more cases that the coalescing method does not care
of and update it accordingly, to maintain one single centralized solution.

2023-08-21 07:54 UTC, mogasergiu commented
Failing points met so far and why this should be done:
- QEMU's multiboot cmdline start address happened to be misaligned one time. This seems to be generally unreliable only in the case of the command-line. GRUB, the official reference implementation of multiboot, also does not explicitly align the command-line, it simply [allocates](https://github.com/coreos/grub/blob/2.02-coreos/grub-core/loader/i386/multiboot_mbi.c#L675) memory with an alignment of [0](https://github.com/coreos/grub/blob/2.02-coreos/grub-core/kern/mm.c#L380)
- ARM CCA GSOC student booting through the `Linux Boot Protocol` (our `lxboot`) was met with a misaligned initrd
start address on `kvmtool`. This actually seems to be [defined behavior](https://github.com/kvmtool/kvmtool/blob/e17d182ad3f797f01947fc234d95c96c050c534b/arm/kvm.c#L98)
- we need to have page-aligned non-overlapping memory regions that are flagged as
`UKPLAT_MEMRF_MAP` because we would have duplicate mappings, possibly with
conflicting flags (e.g. overlapping `UKPLAT_MEMRT_STACK` (`rw-` permissions) with `UKPLAT_MEMRT_DEVICETREE` (`r--` permissions, due to forced [alignments](https://github.com/unikraft/unikraft/blob/staging/plat/common/paging.c#L1506),  and would end up making paging initialization issue an
`EEXIST`
- we need to have page-aligned free memory regions because otherwise they will
end up overlapping with `UKPLAT_MEMRF_MAP `memory regions and when the allocator
reaches that specific overlapping free memory region it will end up being
double mapped, resulting in an undefined behavior

2023-09-04 14:07 UTC, michpappas requested changes
Hi @mogasergiu this looks like a good approach to the problem. Please find some review comments below.

2023-09-04 14:07 UTC, michpappas commented on plat/common/paging.c
> +		if (unlikely(mrd->len == 0))
Is there a legitimate case of free regions with zero length? Should this be an assert instead?

2023-09-04 14:07 UTC, michpappas commented on plat/common/paging.c
>  				  paddr, paddr + len, rc);
These need to be updated to `mrd->paddr`, `mrd->len` too

2023-09-04 14:07 UTC, michpappas commented on lib/ukboot/boot.c
> +#define PAGE_OFF				(0xfff)
You can include `uk/arch/paging.h` unconditionally to `CONFG_PAGING` and use `PAGE_MASK` from there.

2023-09-04 14:07 UTC, michpappas commented on plat/common/memory.c
> +			mrd->len = desired_sz;
> A user may want however to fetch some memory regions and know the actual, intended size

From the above the *exact* motivation of this change is unclear to me, but I am a bit skeptical because this information may be later used by other code that performs operations at the page level. One example is `lib_ukrsi_init()` in (https://github.com/unikraft/unikraft/pull/964/) that sets the RIPAS for each region. Right now the implementation calls  `ALIGN_UP(mrd->len, __PAGE_SIZE)`, which makes me slightly uncomfortable as feels quite implicit.

One way to satisfy both requirements is to append an additional 'page_count' element into the mrd structure so that we preserve both values, similarly to what we do in `metadata_ifpages` of  `ukalloc` for MTE: https://github.com/unikraft/unikraft/blob/staging/lib/ukalloc/alloc.c#L78. That of course needs to be maintained for all mrds, including those that are not inserted via `ukplat_memregion_alloc`, and would require coalesce to also update the `page_count` as needed.

On the other hand one may argue that it's enough to rely to the guarantees provided by the mrds, and always assume that:
1. mrd->[p,v]addr is always page aligned, regardless of a region's origin origin (alloc or insert+coalesce). 
2. mrd->size may or may not be aligned (the latter isonly possible when the region was inserted via `ukplat_memregion_alloc`), but can always be safely aligned down to page size.

If we agree that these are indeed guarantees, then we can also keep it as is. What do you think?

2023-09-04 14:07 UTC, michpappas commented on plat/common/memory.c
> +		/* If they overlap. We assume MRD_PRIO_KRNL_RSRC will never
"If they overlap." is not a sentence 😆 "If they overlap, we assume...", or "If they overlap: We assume..."

But more importantly, would an assertion be preferable over a "gentlemen's agreement"? 🎩

2023-09-04 14:07 UTC, michpappas commented on plat/common/memory.c
> +	mrd->len -= mrd->pbase;
Now that I understand your intention, everything is clear (and in fact a clever way to address the problem), but initially I found this sequence of statements initially confusing because `mrd->len` is being used as an intermediate variable for something different than its purpose. I don't have a strong opinion about it, as the confusion is only momentary, but just FYI in case you'd like to rephrase it using a temporary variable or leave a brief comment.

2023-09-04 14:07 UTC, michpappas commented on plat/common/memory.c
>  				overlapping_mrd_fixup(list, ml, mr, ml_prio,
Unless I'm missing something. ;) Neither here or in `overlapping_mrd_fixup()` we take into account flags, and that's a bug waiting to happen, or worse a security issue. If that's correct, then this condition should check if the flags are the same before calling `overlappping_mrd_fixup()`, and bail with an error otherwise.

2023-09-04 14:07 UTC, michpappas commented on plat/common/memory.c
> +		/* We assume only MRD_PRIO_FREE can be dropped. We want
Is there a reason this happens post-processing as opposed to deleting conditionally to these? Similarly for the updating of `mrd->vaddr`.

2023-09-04 14:39 UTC, mogasergiu commented on plat/common/memory.c
> +			mrd->len = desired_sz;
> 1. mrd->[p,v]addr is always page aligned, regardless of a region's origin origin (alloc or insert+coalesce).

They may not be aligned, the aligned mappings are to be guaranteed by `ukplat_paging_init`'s last `for` loop that aligns all `UKPLAT_MEMRT_MAP` mrd's. It is the free memory regions whose [p,v]addr and len must always be aligned.

> 2.  mrd->len may or may not be aligned (the latter isonly possible when the region was inserted via > ukplat_memregion_alloc), but can always be safely aligned down to page size.

Yes, this we can assume.

In short, with this commit, the only mrd's that shall be aligned are the free ones, while the others keep their intended, original, values.

2023-09-04 14:40 UTC, mogasergiu commented on plat/common/memory.c
> +	mrd->len -= mrd->pbase;
I will add both a comment and a temporary variable :smile:.

2023-09-04 14:42 UTC, mogasergiu commented on plat/common/memory.c
> +		/* If they overlap. We assume MRD_PRIO_KRNL_RSRC will never
> "If they overlap." is not a sentence 😆 "If they overlap, we assume...", or "If they overlap: We assume..."

Oops, that is part of the old delete comment, forgot to remove that.

> But more importantly, would an assertion be preferable over a "gentlemen's agreement"? 🎩

Good point, I will add an `UK_ASSERT(mr_prio != MRD_PRIO_RSVD && ml_prio != MRD_PRIO_RSVD)`

2023-09-04 14:50 UTC, mogasergiu commented on plat/common/memory.c
>  				overlapping_mrd_fixup(list, ml, mr, ml_prio,
Hmm, actually I am assuming that only free mrd's may overlap with mrd's of other prio. So, instead, I would add another assertion: `UK_ASSERT(ml_prio == MRD_PRIO_FREE || mr_prio == MRD_PRIO_FREE);` to ensure that at least one of the overlapping regions is a free one that must e adjusted in favor of the other. Kernel rsrc type mrd's should never overlap with anything as those represent what we manually insert.

2023-09-04 14:51 UTC, mogasergiu commented on plat/common/memory.c
I should add a `m[i]->vbase = m[i]->pbase;` out of the loop here, as there may be a case where the last mrd is left unrestored.

2023-09-04 14:53 UTC, mogasergiu commented on plat/common/memory.c
> +		/* We assume only MRD_PRIO_FREE can be dropped. We want
Thought I would only have one place where this is done :thinking:. I could have also wrapped this into a short function instead :thinking:.

2023-09-04 14:54 UTC, mogasergiu commented on plat/common/paging.c
> +		if (unlikely(mrd->len == 0))
Good point, I did not think of much here I just updated it accordingly., this code was here before the memregion PR even I think.

2023-09-04 14:55 UTC, mogasergiu commented on lib/ukboot/boot.c
> +#define PAGE_OFF				(0xfff)
I remember having tried this and was met with some errors. I always try to use already existing definitions. I might misremember, I will try again :+1: .

2023-09-04 16:50 UTC, michpappas commented on lib/ukboot/boot.c
> +#define PAGE_OFF				(0xfff)
It's `uk/plat/paging.h` that requires `CONFIG_PAGING`, but `uk/arch/paging.h` does not have such a requirement.

2023-09-05 08:34 UTC, michpappas commented on plat/common/memory.c
> +		if (!del && mr_prio == MRD_PRIO_KRNL_RSRC)
As discussed, it looks like we need a condition for ` != MRD_PRIO_FREE_RSRC`?

2023-09-09 16:41 UTC, michpappas approved these changes
Looks good thanks! 🚀 

Reviewed-by: Michalis Pappas <michalis@unikraft.io>

2023-09-23 08:29 UTC, mogasergiu commented
@michpappas Added another commit to handle a case I have just encountered while working on something else. Let me know your thoughts. I am not sure if it would be good idea to use `unlikely` here though :thinking:, I probably should though.

2023-09-27 05:02 UTC, razvand commented
@michpappas , @zhxj9823 , could you take a final look, given @mogasergiu 's new commit?

2023-09-28 09:44 UTC, michpappas commented
> @michpappas , @zhxj9823 , could you take a final look, given @mogasergiu 's new commit?

@razvand the additional commit looks good, I think this one's good to merge now.

2023-09-28 16:15 UTC, mogasergiu commented
@michpappas Added two more commits :laughing: :ok_hand:

2023-09-28 17:40 UTC, michpappas requested changes
@razvand please ignore my last comment and refrain from merging, as there are newly added commits.

2023-10-02 13:48 UTC, michpappas requested changes
Hi @mogasergiu, good stuff 💪🏼  Besides the comments below, the commit message initially describes the case where the regions are equal, but later also covers the case where the regions partially overlap. It then describes the pre-conditions at the very end. If I were you I would restructure that a bit to have the constraints in the beginning along with the description of the problem, followed by the solution, and also maybe leave the implementation details out.

2023-10-02 13:48 UTC, michpappas commented on plat/common/memory.c
> +			__sz len = ml->pbase + ml->len - mr->pbase - mr->len;
I think you can simplify the logic a bit, as `RANGE_CONTAIN` already handles the case where the two regions are equal. And that's why it also works when `ml_prio > mr_prio`. Also in general the code would be easier to follow if the different cases are handled in an explicit and discrete way, ie:
```C
/* If the left memory region is contained in within the right region,
 * or the regions are equal, drop it entirely.
if (RANGE_CONTAIN()) {

/* If the left memory region is partially contained in the right region,
 * drop that part of the left region only.
 */
} else if () {

/* If the right region is contained within the left region,
 * keep the right region, and split the left region into two
 * surrounding parts.
 */
} else {

}
```
Together with documenting the guarantees you get from the caller regarding the relative position of the regions, then you have the code speak for itself and it doesn't require so much explanation in comments 😎

2023-10-02 13:48 UTC, michpappas commented on plat/common/memory.c
> +			/* len here is basically ml_end - mr_end. Thus,
This function heavily relies on assumptions about the regions (order, relative base / size, type). In this case it's a good practice to explicitly state these assumptions with comments accompanied with assertions, as it makes the function more robust, and also helps the reader understand it as a self-contained unit.

While some early-UART challenged architectures may have issues with such assertions, IMO opinion that should not prevent us from adding these assertions right now, because ultimately we cannot avoid dealing with fatal cases anyway and for that we use `UK_CRASH`, which also requires early UART. Moreover, we have plenty of calls to `UK_ASSERT` before UART is initialized in our code-base already, even in the memory subsystem. Finally, adding a fix to the x86 drivers to ignore early UART calls if early UART is not enabled - just how we do it on `arm64` - should be easy.

2023-10-06 09:42 UTC, michpappas approved these changes
Looks good thanks!

Reviewed-by: Michalis Pappas <michalis@unikraft.io>

2023-10-09 07:05 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-10-09 07:18 UTC, merged