plat/kvm: Adapt EFI boot to new APIC driver
unikraft/unikraft pull request #1138
Opened 2023-10-15 09:02 UTC by kha-dinh

Fixed the header include, and also added config guard for APIC-related operations in `efi_post.c`.

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [e.g. `x86_64` or N/A]
 - Platform(s): [e.g. `kvm`, `xen` or N/A]
 - Application(s): [e.g. `app-python3` or N/A]

### Additional configuration

### Description of changes

The re-arched upstream APIC driver breaks EFI compilation. This PR adds minor changes to EFI boot to make it work.

2023-10-16 07:17 UTC, mschlumpp approved these changes
Thanks

Reviewed-by: Marco Schlumpp <marco@unikraft.io>

2023-10-16 08:32 UTC, mogasergiu commented on plat/kvm/x86/efi_post.c
> +#if CONFIG_LIBUKINTCTLR_APIC
Hmm, weird how I did not bump into this error. But it makes sense now :+1:. Problem is, this means that the LAPIC Timer would only get disabled if the APIC driver is enabled (which seems to happen implicitly for SMP builds only), which is not ok. Let's follow the PIC example (see the PIC macros defined above) and declare duplicate macros for `APIC_MSR_BASE` and `APIC_BASE_EN` in this file and add a comment with a TODO to let the reader know this should be removed once we handle the LAPIC Timer in our APIC driver.

2023-10-16 08:36 UTC, mogasergiu commented on plat/kvm/x86/efi_post.c
> +#if CONFIG_LIBUKINTCTLR_APIC
> which seems to happen implicitly for SMP builds only

Ahh.. now I know I did not bump into this... I always have SMP enabled... :laughing:

2023-10-17 08:00 UTC, mogasergiu requested changes
Thank you for the quick update :camera_flash:! Two very minor comments. Also keep in mind that the commit message may need re-adjustment :smile:, if you agree with the suggested changes.

2023-10-17 08:00 UTC, mogasergiu commented on plat/kvm/x86/efi_post.c
> +#include <uk/intctlr/apic.h>
Do we still need this header? We probably only need the one for the `rdmsr` instead :thinking:, unless it is already included.

2023-10-17 08:00 UTC, mogasergiu commented on plat/kvm/x86/efi_post.c
> +#define APIC_BASE_EN					(1 << 11)
Awesome :+1:. Thank you :pray:.

Let's move these, as well as the comments, below `LAPIC_TMICT` and also add the `L` letter so that they look somewhat more uniform, i.e. `LAPIC_MSR_BASE`/`LAPIC_BASE_EN`.

2023-10-17 08:58 UTC, kha-dinh commented on plat/kvm/x86/efi_post.c
> +#define APIC_BASE_EN					(1 << 11)
Done :sunglasses:.

2023-10-17 12:51 UTC, mogasergiu requested changes
Sorry, I am probably being annoying here :sweat_smile:, but two more minor comments.

2023-10-17 12:51 UTC, mogasergiu commented on plat/kvm/x86/efi_post.c
> +#include <uk/intctlr/apic.h>
What about this? :thinking: 
```diff
diff --git a/plat/kvm/x86/efi_post.c b/plat/kvm/x86/efi_post.c
index 63cb82a6..81d261d9 100644
--- a/plat/kvm/x86/efi_post.c
+++ b/plat/kvm/x86/efi_post.c
@@ -7,9 +7,6 @@
 #include <uk/arch/paging.h>
 #include <uk/plat/common/bootinfo.h>
 #include <uk/plat/lcpu.h>
-#if CONFIG_LIBUKINTCTLR_APIC
-#include <uk/intctlr/apic.h>
-#endif /* CONFIG_LIBUKINTCTLR_APIC */
 #include <x86/cpu.h>
 
 /* Slave Controller Edge/Level Triggered Register */
 ```
 Seems to work for me with both SMP enabled and disabled
 
 EDIT: Btw I noticed you also added the `/* CONFIG... */ which is what we are trying to have for `#if` guards. Thanks a lot for the careful thought :pray:

2023-10-17 12:51 UTC, mogasergiu commented on plat/kvm/x86/efi_post.c
> +#define LAPIC_MSR_BASE					0x01b
You're going to hate me for this nitpick :grin:, but I really like **muh** consistency<sup>TM</sup>: can we do this with a capital :laughing: `0x01B` like the other macros in this file? Sorry :sweat_smile:, but better now during review. Other than that, everything looks good. Thank you again for catching this :muscle:.

2023-10-18 01:35 UTC, kha-dinh commented on plat/kvm/x86/efi_post.c
> +#define LAPIC_MSR_BASE					0x01b
I left the include there because there might be dependency in the future. Removed it.

2023-10-18 07:28 UTC, mogasergiu approved these changes
Awesome :love_you_gesture:! Thanks a lot for your work and cooperation!

Reviewed-by: Sergiu Moga <sergiu@unikraft.io>

2023-10-18 08:12 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-10-18 08:12 UTC, merged