include: Add strong/weak reference counting
unikraft/unikraft pull request #1160
Opened 2023-11-16 18:34 UTC by andreittr

### Description of changes

This change adds a utility header implementing a reference counting scheme that supports regular (strong) as well as weak references.

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

Checkpatch is ignorant of docstring formatting (or context); false-positive warnings.

### Base target

 - Architecture(s): N/A
 - Platform(s): N/A
 - Application(s): N/A

### Additional configuration

N/A

2023-11-28 00:32 UTC, skuenzer requested changes

2023-11-28 00:32 UTC, skuenzer commented on include/uk/weak_refcount.h
> +#ifndef __UK_WEAK_REFCOUNT_H__
We usually have the following header guards layout (no defintion to `1` and closing `#endif` repeats the guard name with a comment):
```c
#ifndef __UK_WEAK_REFCOUNT_H__
#define __UK_WEAK_REFCOUNT_H__
```
...
```c
#endif /* __UK_WEAK_REFCOUNT_H__ */
```

2023-11-28 18:23 UTC, skuenzer approved these changes
Reviewed-by: Simon Kuenzer <simon@unikraft.io>
Approved-by: Simon Kuenzer <simon@unikraft.io>

2023-11-28 18:24 UTC, merged

2023-11-30 14:20 UTC, skuenzer commented
Hey @andreittr, I just noticed after merging that the `Signed-off-by` tag was missing. Can you reply to this message with your Signed-off-by tag to confirm that the commit should have it? Otherwise we need to remove the commit from the branch.

2023-11-30 17:32 UTC, andreittr commented
Signed-off-by: Andrei Tatar <andrei@unikraft.io>