Add comments for posix-user
unikraft/unikraft pull request #1164
Opened 2023-11-20 20:29 UTC by DeliaPavel

### Prerequisite checklist

 - [ ] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [ ] Tested your changes against relevant architectures and platforms;
 - [ ] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [e.g. `x86_64` or N/A]
 - Platform(s): [e.g. `kvm`, `xen` or N/A]
 - Application(s): [e.g. `app-python3` or N/A]

### Additional configuration

### Description of changes

2023-11-23 01:49 UTC, PAN740623 commented
错误报告 阻止

2023-11-23 01:50 UTC, PAN740623 commented
url:

2023-12-17 09:14 UTC, StefanJum requested changes
Few comments @DeliaPavel, looks good overall.

2023-12-17 09:14 UTC, StefanJum commented on lib/posix-user/musl-imported/include/grp.h
> +/**
```suggestion

/**
```

2023-12-17 09:14 UTC, StefanJum commented on lib/posix-user/musl-imported/include/grp.h
> +/**
```suggestion

/**
```

2023-12-17 09:14 UTC, StefanJum commented on lib/posix-user/musl-imported/include/grp.h
> +/**
```suggestion

/**
```

2023-12-17 09:14 UTC, StefanJum commented on lib/posix-user/musl-imported/include/grp.h
> +/**
```suggestion

/**
```

2023-12-17 09:14 UTC, StefanJum commented on lib/posix-user/musl-imported/include/grp.h
> +/**
```suggestion

/**
```

2023-12-17 09:14 UTC, StefanJum commented on lib/posix-user/musl-imported/include/grp.h
> +/**
```suggestion

/**
```

2023-12-17 09:14 UTC, StefanJum commented on lib/posix-user/musl-imported/include/grp.h
> +/**
```suggestion

/**
```

2023-12-17 09:14 UTC, StefanJum commented on lib/posix-user/musl-imported/include/grp.h
> +/**
```suggestion

/**
```

2023-12-17 09:14 UTC, StefanJum commented on lib/posix-user/musl-imported/include/grp.h
> +/**
```suggestion

/**
```

2023-12-17 09:14 UTC, StefanJum commented on lib/posix-user/musl-imported/include/grp.h
> +/**
```suggestion

/**
```

2023-12-17 09:14 UTC, StefanJum commented on lib/posix-user/user.h
> +/**
```suggestion

/**
```

2023-12-23 13:46 UTC, StefanJum requested changes
Almost done, see the comments @DeliaPavel

2023-12-23 13:46 UTC, StefanJum commented on lib/posix-user/musl-imported/include/grp.h
> + *	 Group structure in which the group with the `gid` group id is stored
```suggestion
 *   Group structure in which the group with the `gid` group id is stored
```
Do not use tabs within comment blocks.

2023-12-23 13:46 UTC, StefanJum commented on lib/posix-user/musl-imported/include/grp.h
> + *	 Length of buffer `buf`
```suggestion
 *   Length of buffer `buf`
```

2023-12-23 13:46 UTC, StefanJum commented on lib/posix-user/musl-imported/include/grp.h
> + *	 Group structure in which the group with the `name` group name is stored
```suggestion
 *   Group structure in which the group with the `name` group name is stored
```

2023-12-23 13:46 UTC, StefanJum commented on lib/posix-user/musl-imported/include/grp.h
> + *	 Length of buffer `buf`
```suggestion
 *   Length of buffer `buf`
```

2023-12-23 13:46 UTC, StefanJum commented on lib/posix-user/musl-imported/include/grp.h
> + *	 The number of groups the user belongs to, or -1 on error.
```suggestion
 *   The number of groups the user belongs to, or -1 on error.
```

2023-12-23 13:46 UTC, StefanJum commented on lib/posix-user/musl-imported/include/grp.h
> + *	 0 on success, -1 on error.
```suggestion
 *   0 on success, -1 on error.
```

2023-12-23 13:46 UTC, StefanJum commented on lib/posix-user/user.h
> + *	 Destination string
```suggestion
 *   Destination string
```

2023-12-23 16:05 UTC, StefanJum approved these changes
Thanks @DeliaPavel 
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-12-30 03:16 UTC, razvand reviewed
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>

2023-12-30 03:16 UTC, razvand approved these changes
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>

2023-12-30 03:17 UTC, merged