Add README for posix-time library
unikraft/unikraft pull request #1176
Opened 2023-11-25 13:13 UTC by RaduNichita

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s):  N/A
 - Application(s): N/A

### Additional configuration

### Description of changes

Add README for `posix-time` internal library.

2023-12-08 09:37 UTC, StefanJum requested changes
Thanks @RaduNichita, please add a short application example that uses some `posix-time` functions and short instructions on how to enable it from the menuconfig screen.

2023-12-10 23:25 UTC, RaduNichita commented
@StefanJum I have applied the suggestions. Please have another look when you have time.

2023-12-17 10:48 UTC, StefanJum requested changes
Few comments @RaduNichita, also sign-off the commit.

2023-12-17 10:48 UTC, StefanJum commented on lib/posix-time/README.md
> +Note: the operation with timers are not yet supported.
```suggestion
Note: timer operations are not yet supported.
```

2023-12-17 10:48 UTC, StefanJum commented on lib/posix-time/README.md
> +int main(void) {
```suggestion
int main(void) {
```

2023-12-26 14:43 UTC, RaduNichita commented
I applied the changes. @StefanJum please have a look when you have time.

2023-12-30 04:38 UTC, razvand approved these changes
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-12-30 04:39 UTC, merged