lib/posix-user: Add README.md file for posix-user
unikraft/unikraft pull request #1177
Opened 2023-11-26 11:25 UTC by DeliaPavel

### Prerequisite checklist

 - [ ] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [ ] Tested your changes against relevant architectures and platforms;
 - [ ] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [e.g. `x86_64` or N/A]
 - Platform(s): [e.g. `kvm`, `xen` or N/A]
 - Application(s): [e.g. `app-python3` or N/A]

### Additional configuration

### Description of changes

2023-12-08 09:35 UTC, StefanJum requested changes
Looks good @DeliaPavel, thanks.
Besides the comments, see if you can please the codacy linter.

Also please add instructions on how to set the config variables (CONFIG_LIBPOSIX_USER...) and specify their default values.

2023-12-08 09:35 UTC, StefanJum commented on lib/posix-user/README.md
> +The `passwd` structure is used to define the default `passwd` entry, whose format is similar to the ones from the `etc/passwd` file in Linux:
```suggestion
The `passwd` structure is used to define the default `passwd` entry, whose format is similar to the one from the `/etc/passwd` file in Linux:
```

2023-12-08 09:35 UTC, StefanJum commented on lib/posix-user/README.md
> +`CONFIG_LIBPOSIX_USER_GID`.
```suggestion
* `pw_gid` is the ID of the default user's group and is equal to `CONFIG_LIBPOSIX_USER_GID`.
```

2023-12-08 09:35 UTC, StefanJum commented on lib/posix-user/README.md
> +`CONFIG_LIBPOSIX_USER_GID`.
```suggestion
* `gr_gid` is the ID of the default group and is equal to `CONFIG_LIBPOSIX_USER_GID`.
```

2023-12-23 16:28 UTC, DeliaPavel reviewed
I tried pleasing the Codacy linter, but I don't really understand the comments we have left. Also, for the `[ordered-list-marker-value]`, I know for past PRs we used 1. for all the list values.

2023-12-30 05:23 UTC, razvand approved these changes
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-12-30 05:24 UTC, merged