lib/posix-environ: Add comments for posix-environ
unikraft/unikraft pull request #1184
Opened 2023-12-02 16:31 UTC by DeliaPavel

### Prerequisite checklist

 - [ ] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [ ] Tested your changes against relevant architectures and platforms;
 - [ ] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [e.g. `x86_64` or N/A]
 - Platform(s): [e.g. `kvm`, `xen` or N/A]
 - Application(s): [e.g. `app-python3` or N/A]

### Additional configuration

### Description of changes

2023-12-23 13:41 UTC, StefanJum requested changes
One small comment @DeliaPavel, all good after that.

2023-12-23 13:41 UTC, StefanJum commented on lib/posix-environ/environ.h
> +/**
```suggestion
int __putenv(char *s, size_t l, char *r);

/**
```

2023-12-23 16:03 UTC, StefanJum approved these changes
Thank you @DeliaPavel 
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-12-30 04:33 UTC, razvand approved these changes
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>

2023-12-30 04:34 UTC, merged