lib/posix-fdtab: Support independent (per-process) fdtabs
unikraft/unikraft pull request #1278
Opened 2024-01-24 15:56 UTC by andreittr

### Description of changes

This PR changes the way `posix-fdtab` handles tables, from a single, static, OS-wide table, to a thread-local reference to one of possibly many independent tables. This allows for, among others, per-process independent fdtabs. Specifically, the commits in this changeset:
- Make the currently active fdtab a thread-local reference
- Support dynamically allocated (and freed) fdtabs
- Handle the `clone()` syscall to duplicate the fdtable when needed

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s): N/A
 - Application(s): N/A

### Additional configuration

`CONFIG_LIBPOSIX_FDTAB=y`

All single-process code should keep working as-is, with a shared fdtab (albeit through independent, refcounted references).
Once multi-process support is added, every thread spawned with `clone()` without the `CLONE_FILES` flag should have independent tables.

2024-02-07 11:46 UTC, andreittr commented
Rebased to current staging.

2024-04-30 15:58 UTC, John-Ted approved these changes
Looks good to me

Reviewed-by: Ioan-Teodor Teugea ioan_teodor.teugea@stud.acs.upb.ro

2024-06-01 13:40 UTC, csvancea approved these changes
Reviewed-by: Cosmin Vancea csvancea@gmail.com

2025-02-05 12:26 UTC, andreittr commented
Rebased to current staging

2025-02-07 02:22 UTC, michpappas requested changes

2025-02-07 02:22 UTC, michpappas commented on lib/posix-fdtab/fdtab.c
> +			return -ENOMEM;
Very minor: In case `fdtab_duplicate()` fails for additional reasons in the future, instead of making assumptions on  the caller's side, consider if it would be preferable to update `fdtab_duplicate()` to return error pointer that the caller can directly decode and return. Alternatively you can consider adding a line in the description "Returns pointer on success or NULL if out of memory".

2025-02-07 02:22 UTC, michpappas commented on lib/posix-fdtab/fdtab.c
> +	if (likely(ret)) {
Generally speaking, the convention in the codebase is to wrap checks for errors with `unlikely` and return immediately, and not use `likely` in general. The reason is more than style: If a block wrapped around `likely()` calls an inline function that involves error handling, that function will almost certainly use `unlikely`, and that results into multiple likelihood attributes in the same execution path, which can result into the [opposite than the desired effect](https://blog.aaronballman.com/2020/08/dont-use-the-likely-or-unlikely-attributes/).

2025-02-07 02:22 UTC, michpappas commented on lib/posix-fdtab/fdtab.c
> +UK_POSIX_CLONE_HANDLER(CLONE_FILES, 0, fdtab_clone, 0);
Not necessarily in the scope of this PR, but from the documentation for `CLONE_FILES` in the man page, it looks like we need to update the `fdtab_handle_execve()` to handle the case where the fdtab is shared between the parent and the child:
> If a process sharing a file descriptor table calls execve(2), its file descriptor table is duplicated (unshared).

2025-02-07 02:22 UTC, michpappas commented on lib/posix-fdtab/fmap.h
> +	if (!_FMAP_INRANGE(m, idx))
Just curious cause I notice that you make the same check in other functions in this header: is the out-of-range an expected case that we can safely continue execution from, and therefore not qualifying for an assertion?

2025-02-07 08:57 UTC, andreittr commented on lib/posix-fdtab/fdtab.c
> +	if (likely(ret)) {
I also tend to use `unlikely` in general and keep `likely` for only this exact pattern: "call, likely init, ret", as that's "safe" from unintended effects in isolation. But I hadn't considered the effects of inlining or LTO before :thinking: good point; will replace with unlikely.

2025-02-07 09:21 UTC, andreittr commented on lib/posix-fdtab/fdtab.c
> +UK_POSIX_CLONE_HANDLER(CLONE_FILES, 0, fdtab_clone, 0);
I agree we have to update fdtab for `execve()`, and more generally make "fdtab unsharing" a singular well-defined event that can be triggered either by `clone()` or `execve()`, and can in turn trigger further actions.
I believe we need this in order to correctly support "magic" files that are unshared implicitly along with the fdtab, without explicit action from userspace, such as `epollfd` and `signalfd`.

2025-02-07 09:33 UTC, andreittr commented on lib/posix-fdtab/fmap.h
> +	if (!_FMAP_INRANGE(m, idx))
:thinking: fdtab ops/syscalls _should_ return -EBADF if called with an out-of-bounds fd, so that's explicitly a use-case we need to safely continue from, and from looking at the code it seems fdtab relies on fmap to signal errors instead of bounds-checking at higher levels.

I see your point that a cleaner design would do bounds checking & `return -EBADF` in the fdtab ops/syscalls themselves and have the raw internal data structure at most assert bounds -- separation of mechanism and policy and all that. While such a refactor is not something I'm comfortable tacking on to this PR, I think the broader VFS work (i.e., now-ish) is a good time to do this.

2025-02-07 09:50 UTC, andreittr commented on lib/posix-fdtab/fdtab.c
> +			return -ENOMEM;
I see your point, though I prefer that functions who have a single possible failure state by design do not return error codes, but let the caller in higher levels interpret their failure. Returning errptrs is particularly tricky because then the caller must worry _both_ about errptrs _and_ NULLs (because NULL is _not_ an error pointer as it doesn't map to a negative errno).

`fdtab_duplicate()` falls into this single fail state group, as it's a glorified malloc + memcpy by design (and the latter cannot fail recoverably); `fdtab_clone` is the higher-level "public-facing" function that is expected to conform to the errno API, and there is IMO the best place to encode and return errors.
I'll update description to make its return values clear.

2025-02-07 10:24 UTC, michpappas commented on lib/posix-fdtab/fmap.h
> +	if (!_FMAP_INRANGE(m, idx))
Yes of course it's out of scope. Just a general observation as I was going through the code 👍🏼

2025-02-07 10:26 UTC, michpappas commented on lib/posix-fdtab/fdtab.c
> +UK_POSIX_CLONE_HANDLER(CLONE_FILES, 0, fdtab_clone, 0);
Alright, thanks for confirming. Let's treat it as a follow up item then 👍🏼

2025-02-07 10:27 UTC, michpappas commented on lib/posix-fdtab/fdtab.c
> +			return -ENOMEM;
Up to you, especially as its not a public API it's not that critical. Just sharing my 2c.

2025-02-07 11:19 UTC, andreittr commented
Rebased to current staging

2025-02-07 11:20 UTC, andreittr commented
Addressed comments

2025-02-17 11:11 UTC, andreittr commented
Rebased to current staging

2025-02-17 14:40 UTC, andreittr commented
Pushed a minor rework; in short:
- single fdtab or multi-fdtab is now a hidden Kconfig option, autoselected if `clone()` support is enabled
  - this neatly decouples the mechanism of "having multiple fdtabs" from the policy of "what fdtab each thread has"
- newly-created threads no longer inherit their parent's fdtab reference; raw `uk_thread`s get NULL (kernel threads shouldn't be mucking about with the fdtab anyway), `clone` handler implements the semantics of sharing/unsharing for posix threads
- the init thread still starts with a reference to the init fdtab; this is in lieu of a "thread posixification" callback, and once such a mechanism exists, we should probably move the init fdtab there

2025-02-19 09:40 UTC, michpappas approved these changes
As discussed: once #1364 is merged the `POSIX_PROCESS_EXIT_EVENT` will be available to terminate the fdtab of posix threads.

Other than that...

Reviewed-by: Michalis Pappas <michalis@unikraft.io>

2025-02-19 11:35 UTC, andreittr commented
Pushed a compat stop-gap change to have all raw threads inherit the fdtab ref of their parent (instead of NULL).

2025-02-19 11:58 UTC, andreittr commented
Pushed a tiny bonus fix for the wrong value being returned by the `execve` event handler.

2025-02-21 11:31 UTC, andreittr commented
Pushed a fix for a type mismatch that resulted in misaligned accesses on arm64.

2025-02-22 07:46 UTC, michpappas approved these changes
Reviewed-by: Michalis Pappas <michalis@unikraft.io>

2025-02-23 10:26 UTC, michpappas commented
Approved-by: Michalis Pappas <michalis@unikraft.io>

2025-02-23 10:29 UTC, merged