lib/vfscore: Prevent superfluous slashes in working directory
unikraft/unikraft pull request #1302
Opened 2024-02-01 13:55 UTC by mschlumpp

The mount point can contain a trailing slash (for example the root mount point has a path of "/"). The path that is concatenated to the mount point also contains a slash at the beginning. Therefore, extra care must be taken to prevent two slashes from appearing besides each other.

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s): N/A
 - Application(s): N/A

### Additional configuration

### Description of changes

2024-02-02 16:41 UTC, RaduNichita requested changes

2024-02-02 16:41 UTC, RaduNichita commented on lib/vfscore/syscalls.c
> +	// Cut of the last trailing slash if there is one
```suggestion
	// Cut off the last trailing slash if there is one
```

2024-02-05 12:14 UTC, StefanJum approved these changes
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2024-02-05 22:28 UTC, RaduNichita approved these changes
Looks good.

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

2024-02-06 17:22 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2024-02-06 17:22 UTC, merged