lib/posix-process: Add option to context switch away from clone caller
unikraft/unikraft pull request #1303
Opened 2024-02-01 13:57 UTC by mschlumpp

Some applications are expecting to run on a cooperative scheduler and will naively assume that the new thread will do some progress even if the clone caller does not context-switch by blocking/yielding.

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s): N/A
 - Application(s): N/A

### Additional configuration

 - `CONFIG_LIBPOSIX_PROCESS_CLONE_PREFER_CHILD=y`

### Description of changes

2024-02-01 14:12 UTC, mschlumpp commented
Note: it is undecided whether we want to prioritize the parent or the children by default. (cc @michpappas)

2024-02-02 12:57 UTC, eduardvintila approved these changes
Nice addition, looks good to me.

Reviewed-by: Eduard Vintilă <eduard.vintila47@gmail.com>

2024-02-02 13:52 UTC, Mihnea0Firoiu approved these changes
Looks good to me.
Reviewed-by: Mihnea Firoiu <mihneafiroiu0@gmail.com>

2024-02-07 07:37 UTC, michpappas requested changes
@mschlumpp just one minor comment below. Regarding ordering: As discussed offline, there isn't a good default in our case so let's leave it as is.

2024-02-07 07:37 UTC, michpappas commented on lib/posix-process/Config.uk
> +	default n
This is redundant, as Kconfig's default for `bool` types is `n`: https://docs.zephyrproject.org/latest/build/kconfig/tips.html#redundant-defaults.

2024-02-07 10:24 UTC, michpappas commented
Approved-by: Michalis Pappas <michalis@unikraft.io>

2024-02-07 10:24 UTC, merged