lib/posix-sysinfo: Fix off-by-1 error in `sethostname`
unikraft/unikraft pull request #1307
Opened 2024-02-05 15:37 UTC by andreittr

### Description of changes

This change corrects an an off-by-1 error in sethostname when checking the length of the new hostname, leading to a missing terminating NUL byte in the `nodename` field of `struct utsname`, contrary to the expected Linux ABI. The suboptimal `strncpy` call is also replaced with a more appropriate `memcpy` call, since (1) we know the length of the input string, which (2) does not need to be NUL-terminated.

Additionally, declarations of `gethostname` and `sethostname` are added to `nolibc`'s `unistd.h`, making these functions available to core unikraft as well as microlibraries.

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s): N/A
 - Application(s): N/A

### Additional configuration

`CONFIG_LIBPOSIX_SYSINFO=y`

Test snippet:
```c
int main(void)
{
	char name[4096];
	int r;

	r = gethostname(name, 4096);
	assert(!r);
	puts(name);

	r = sethostname("123456789012345678901234567890123456789012345678901234567890abcde", 65);
	if (!r) {
		r = gethostname(name, 4096);
		assert(!r);
		puts(name);
	} else {
		puts("Errored out");
	}

	r = sethostname("123456789012345678901234567890123456789012345678901234567890abcde", 64);
	assert(!r);

	r = gethostname(name, 4096);
	assert(!r);
	puts(name);

	return 0;
}
```
On `staging` it incorrectly sets a hostname without a NUL byte, resulting in the Unikraft version leaking into the hostname:
```
SeaBIOS (version 1.16.3-1.fc39)
Booting from ROM..Powered by
o.   .o       _ _               __ _
Oo   Oo  ___ (_) | __ __  __ _ ' _) :_
oO   oO ' _ `| | |/ /  _)' _` | |_|  _)
oOo oOO| | | | |   (| | | (_) |  _) :_
 OoOoO ._, ._:_:_,\_._,  .__,_:_, \___)
               Telesto 0.16.1~4b12ebc89
unikraft
123456789012345678901234567890123456789012345678901234567890abcde5-Telesto
123456789012345678901234567890123456789012345678901234567890abcd

```
After the fix, it should correctly error out of the first `sethostname` call:
```
SeaBIOS (version 1.16.3-1.fc39)
Booting from ROM..Powered by
o.   .o       _ _               __ _
Oo   Oo  ___ (_) | __ __  __ _ ' _) :_
oO   oO ' _ `| | |/ /  _)' _` | |_|  _)
oOo oOO| | | | |   (| | | (_) |  _) :_
 OoOoO ._, ._:_:_,\_._,  .__,_:_, \___)
               Telesto 0.16.1~c704be7ea
unikraft
Errored out
123456789012345678901234567890123456789012345678901234567890abcd
```

2024-02-06 22:57 UTC, mariasfiraiala requested changes
Looks good to me, however, please fix the `NUL` typo in commit's c704be7ea7d4b8f80a575560e0195ad5edfaa0df message.

2024-02-06 23:29 UTC, adinamariav approved these changes
Aside from what @mariasfiraiala stated [here](https://github.com/unikraft/unikraft/pull/1307#pullrequestreview-1866476440), looks good. 

Reviewed-by: Adina-Maria Vaman adinamariav22@gmail.com

2024-02-07 11:07 UTC, andreittr commented
> Looks good to me, however, please fix the `NUL` typo in commit's [c704be7](https://github.com/unikraft/unikraft/commit/c704be7ea7d4b8f80a575560e0195ad5edfaa0df) message.

@mariasfiraiala Oh that's on purpose, I meant that as `NUL`, [ASCII](https://www.asciitable.com/asciifull.gif) abbreviation for char code 0 (aka "the null char", but that "null" is lowercase), instead of `NULL`, like the null pointer.
I know it's confusing, blame the telecom people behind ascii and their aversion to 4 letter names :smile: .

2024-02-07 11:20 UTC, mariasfiraiala approved these changes
Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

2024-02-07 12:22 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2024-02-07 12:23 UTC, merged