lib/posix-socket: Expose internal socket syscalls
unikraft/unikraft pull request #1337
Opened 2024-02-23 13:25 UTC by andreittr

### Description of changes

This change exposes Unikraft-internal syscalls that create sockets. Both versions returning raw uk_files as well as opened file descriptors are provided.

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [ ] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s): N/A
 - Application(s): N/A

### Additional configuration
N/A

2024-05-11 14:28 UTC, Mihnea0Firoiu approved these changes
All good!
Reviewed-by: Mihnea Firoiu <mihneafiroiu0@gmail.com>

2024-05-13 14:27 UTC, RaduNichita approved these changes
Thanks @andreittr, it looks good.

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

2024-05-15 07:05 UTC, StefanJum requested changes
@andreittr should we also add the exposed symbols in `exportsyms.uk`?

2024-05-22 07:58 UTC, andreittr commented
> @andreittr should we also add the exposed symbols in `exportsyms.uk`?

Good catch, thanks! Added.

2024-05-24 11:36 UTC, StefanJum approved these changes
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2024-05-24 13:22 UTC, andreittr commented
Force-push: rebased on current staging & patched to work with changes introduced in a922af776d.

2024-05-29 04:35 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2024-05-29 04:36 UTC, merged