lib/isrlib: Adding unit tests for isrlib
unikraft/unikraft pull request #1367
Opened 2024-03-29 12:51 UTC by ahmd-kamel

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [ ] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [e.g. `x86_64` or N/A]
 - Platform(s): [e.g. `kvm`, `xen` or N/A]
 - Application(s): [e.g. `app-python3` or N/A]

### Description of changes

This PR adhere to the opend issue #580 .

I have added a full unit test cases file in order to check the correctness and point of weaknesses in the following library.
While running the tests you will find some unit tests fails you need to check weather this test case is valid or not based on the purpose of the functions that is implemented inside isrlib. Finally i wanna highlight one result approximately the whole functions inside isrlib does not have any checking for false inputs like passing null pointer you will see at the end of each test suite i commented a line of code this line actually can make the system to crash if the line executed.   

- Changing the config.uk inside the library in order to generate the main config.uk correctly.
-  Adding the unit_test.c for the library after going throw the whole library to understand the purposes of functions inside.
- Editing the makefile to add the unit_test.c with executables in order to perform unit testing to the library.

2024-05-02 17:31 UTC, RaduNichita requested changes
Thanks for the contribution @ahmd-kamel 

I did a first pass, please see my comments.

2024-05-02 17:31 UTC, RaduNichita commented on lib/isrlib/tests/test_isrlib.c
> +/* 1- Threre is no type checking inside memset_isr
```suggestion
/* 1 - There is no type checking inside memset_isr
```

2024-05-02 17:31 UTC, RaduNichita commented on lib/isrlib/tests/test_isrlib.c
> +	UK_TEST_EXPECT_BYTES_EQ(result_1, dest_1, 5);
I think you can use src_1 instead of the result_1, just as you did in the previous example from the same test

2024-05-02 17:31 UTC, RaduNichita commented on lib/isrlib/tests/test_isrlib.c
> +	char src_1[14] = "Hello, World!";
I would mark this as const and do not modify it in the testcase

2024-05-02 17:31 UTC, RaduNichita commented on lib/isrlib/tests/test_isrlib.c
> +	memcpy_isr(src_1 + 5, src_1, 5);
If you want to do some overlap of memory, I think it would be better to create a new char* instead of modifying the source.

In that way, if there are some more usecases to be able to this test, it would be easier to follow.

2024-05-02 17:31 UTC, RaduNichita commented on lib/isrlib/tests/test_isrlib.c
> +	memcpy_isr(dest_2, src_2, 1024);
What do you want to test in this scenario? How is this different from the first scenario from this test.

2024-05-02 17:31 UTC, RaduNichita commented on lib/isrlib/tests/test_isrlib.c
> +	UK_TEST_EXPECT_SNUM_EQ(ret, 0);
I would also add a test in which the result of EQ is different from 0.

2024-05-02 17:31 UTC, RaduNichita commented on lib/isrlib/tests/test_isrlib.c
> +	UK_TEST_EXPECT_PTR_EQ(ptr, array_0 + 7);
I would organize the test in the following way. What do you think?

```suggestion

	char *ptr = (char *)memrchr_isr(array_0, 'o', 11);
	UK_TEST_EXPECT_PTR_EQ(ptr, array_0 + 7);
```

2024-05-02 17:31 UTC, RaduNichita commented on lib/isrlib/tests/test_isrlib.c
> +	UK_TEST_EXPECT_PTR_EQ(ptr, array_0);
Same for this

```suggestion

	ptr = (char *)memrchr_isr(array_0, 'H', 11);
	UK_TEST_EXPECT_PTR_EQ(ptr, array_0);
```

2024-05-02 17:31 UTC, RaduNichita commented on lib/isrlib/tests/test_isrlib.c
> +	/* incase of forward overlapping the method */
```suggestion
	/* in case of forward overlapping the method */
```

2024-05-02 23:56 UTC, ahmd-kamel commented on lib/isrlib/tests/test_isrlib.c
> +	memcpy_isr(dest_2, src_2, 1024);
I know you might see no difference, but here I am testing the case of copying a large string at the first I am just testing copying of small string.

2024-05-03 00:04 UTC, ahmd-kamel commented on lib/isrlib/tests/test_isrlib.c
> +	UK_TEST_EXPECT_SNUM_EQ(ret, 0);
I have just add a test case for EQ in line 158 and 159.

2024-05-03 00:36 UTC, ahmd-kamel commented on lib/isrlib/tests/test_isrlib.c
> +	char src_1[14] = "Hello, World!";
The purposes of this string is to help me test :
1 - Copying sub string  from the whole string. --> Not the main purpose but I take it on my way.
2 - Test the case of self overlapping. --> the main purpose you can see the following snip shot.

![Screenshot from 2024-05-03 03-35-43](https://github.com/unikraft/unikraft/assets/65306204/f5c9a6ff-3eab-460b-8875-1727f5313bcf)

I take the memcpy as my reference so since  memcpy_isr doing the same function we must expect the same results.

2024-05-03 00:37 UTC, ahmd-kamel commented on lib/isrlib/tests/test_isrlib.c
> +	UK_TEST_EXPECT_BYTES_EQ(result_1, dest_1, 5);
You are right, I will edit once we finish the conversation per this test suite.

2024-05-03 00:38 UTC, ahmd-kamel commented on lib/isrlib/tests/test_isrlib.c
> +	memcpy_isr(src_1 + 5, src_1, 5);
I have added the snip shot in the above conversation I think it's all linked together.

2024-05-15 06:57 UTC, StefanJum reviewed
Looks good, @ahmd-kamel please also squash the commits.

2024-05-21 20:51 UTC, razvand commented
> Looks good, @ahmd-kamel please also squash the commits.

@ahmd-kamel , could you please squash the commits according to feedback from @StefanJum ?

2024-05-21 22:02 UTC, ahmd-kamel commented
Thank you, @StefanJum, @razvand. I apologise for the late response.
 I have squashed only the last two commits.
 I wanna hear if there are any notes that can make the PR better.

2024-05-24 11:45 UTC, StefanJum requested changes
@ahmd-kamel you need to squash *all* commits into one. That means only one commit should appear in the `commit` tab.
You can follow the instructions [here](https://www.freecodecamp.org/news/git-squash-commits/).

Also, about the nullptr acesses, you can add the proper checks nor nullptrs in the faulty functions, or add a FIXME before the comment so we don't forget about that.

2024-05-24 19:28 UTC, ahmd-kamel commented
Hello, @StefanJum as requested in your review I have squashed all commits in one commit, also I add `FIXME:` tag in comments.

2024-05-25 15:38 UTC, RaduNichita reviewed
It looks better, I still have left some question / suggestions @ahmd-kamel

2024-05-25 15:38 UTC, RaduNichita commented on lib/isrlib/tests/test_isrlib.c
> + *  the following comment causes crash for accessing nullptr
What is the following comment? I think it should be place right under this for an easy understanding.

Same for the rest.

2024-05-25 15:38 UTC, RaduNichita commented on lib/isrlib/tests/test_isrlib.c
> +	/* take a look at this case and the above they */
Can you better explain the situation here, please? What is different?

2024-05-29 04:33 UTC, razvand commented
@ahmd-kamel , could you check the comments from @RaduNichita ?

2024-10-07 19:02 UTC, closed without merging