libs/vfscore: Fix dirent64 warning
unikraft/unikraft pull request #1372
Opened 2024-03-30 15:47 UTC by razvanrus2003

Current Musl-based builds generate warnings related to dirent64 definition. Define _LARGEFILE64_SOURCE early so it prevents the warning from happening.

2024-03-30 16:14 UTC, StefanJum requested changes
Thanks @razvanrus2003.
Since `_LARGEFILE64_SOURCE` is a [feature test macro](https://www.man7.org/linux/man-pages/man7/feature_test_macros.7.html), it should not be defined in a header file. As a general rule, never define feature macros in header files. Only in source files, and before any other headers are included.

Also according to [the manual](https://www.man7.org/linux/man-pages/man7/feature_test_macros.7.html), `_LARGEFILE64_SOURCE` should be implied by `_GNU_SOURCE`, so I would just define `_GNU_SOURCE` in whatever source file this header was included from when generating the warning.

Defining `_LARGEFILE64_SOURCE` in the source file works too IMO, it's not that big of a deal, but do it in a source file/files, not in the header file.

2024-05-01 22:55 UTC, RaduNichita approved these changes
LGTM, thanks @ra
Reviewed-by: Radu Nichita <radunichita99@gmail.com>

2024-05-29 04:32 UTC, razvand commented
@razvanrus2003 , could you check @StefanJum 's comments?

2024-09-28 07:53 UTC, StefanJum approved these changes
All good, thanks and sorry for the delay.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2024-09-28 09:56 UTC, razvand approved these changes
Thanks, @razvanrus2003 , @StefanJum 

Fixes: #1508 

Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2024-09-28 09:57 UTC, merged