Tbunch1/clang updates
unikraft/unikraft pull request #1390
Opened 2024-04-21 14:18 UTC by tbunch1

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [N/A]
 - Platform(s): [N/A]
 - Application(s): [N/A]

### Additional configuration
N/A

### Description of changes
Updates .clang-format to better reflect the Unikraft coding conventions.

2024-04-22 05:57 UTC, craciunoiuc commented on .clang-format
> +TabWidth: 8
```suggestion
TabWidth: 8

```

Missing newline at the end :sweat_smile:

2024-04-24 07:21 UTC, craciunoiuc commented
I think you should also merge all commits into a single one 🙏

2024-04-25 23:16 UTC, tbunch1 commented
Apologies if this is a dumb question, but how should we do that? We're pretty new to contributing to open source and we can't figure out how to merge them together. I've been trying to rebase them but I'm having trouble because the changes are pushed. Again sorry if this is a simple question, but we're stuck

2024-04-26 07:25 UTC, craciunoiuc commented
No worries,

on your local machine run these commands:
1. `git rebase --interactive HEAD~3`
2. in the prompt change the last two `pick` to `fixup` and the first `pick` to `reword`
3. change the first commit message to: `.clang-format: Update to match coding conventions` and continue
4. `git push --force`

I hope this works/helps 😅

2024-04-26 18:28 UTC, tbunch1 commented
Oh I see. I was worried about messing with the commit that merged the recent updates but I guess I didn't understand how it worked.

2024-05-18 09:05 UTC, StefanJum requested changes
@tbunch1 please remove the changes to `pagefault64.c`, since they are not part of this pr

2024-05-21 20:39 UTC, razvand commented
> @tbunch1 please remove the changes to `pagefault64.c`, since they are not part of this pr

@tbunch1 , could you please see the comments from @StefanJum and update the PR accordingly?

See also the `checkpatch` checks.

2024-05-29 07:00 UTC, craciunoiuc approved these changes
I guess it looks okay. Thanks!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

2024-05-29 07:27 UTC, StefanJum approved these changes
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2024-05-29 09:35 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2024-05-29 09:41 UTC, merged