support/makefile.patch: Change PYTHONCMD to python3
unikraft/unikraft pull request #1391
Opened 2024-04-23 23:33 UTC by tbunch1

Make it so that python3 is used to run scripts.

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): [N/A]
 - Platform(s): [N/A]
 - Application(s): [N/A]

### Additional configuration
None.

### Description of changes
Change makefile.patch so that python3 is used to run Python scripts. 
Addresses #1006. From what we could tell all other instances of python have been replaced by python3.

2024-04-24 10:39 UTC, nderjung commented
Hi @tbunch1! Thanks for the contribution!

If you are co-authoring commits with peers, please include their sign-off in the form:

```
Co-authored-by: Jane Doe <jane.doe@email.com>
Co-authored-by: John Doe <john.doe@email.com>
```

As part of the commit message. Thanks!

2024-05-02 09:19 UTC, mariasfiraiala requested changes
Thank you for the contribution @tbunch1! The changes look fine, however I have some comments regarding the commit message.

1. As @nderjung mentioned, you need to add the `Co-authored-by` tag **inside the commit message**. You have edited the PR message, not the commit message, so please do that.

1. Add a valid email to the `Signed-off-by` tag; `<92049355+tbunch1@users.noreply.github.com>` is automatically generated by GitHub so it doesn't reflect your real details (and it looks kinda bad).

That's all on my part, thanks!

2024-05-17 08:49 UTC, StefanJum requested changes
Hi. The changes look good, but you all need to add a `signed-off-by` tag to the commit message.

2024-05-17 09:45 UTC, nderjung approved these changes
Hi, I think the multiple `Co-authored-by` is enough with at least 1 `Signed-off-by` by the committer. This PR is good to go imho. Thanks!

Reviewed-by: Alexander Jung <alex@unikraft.io>

2024-05-22 19:27 UTC, mariasfiraiala approved these changes
Looks good, thanks!

Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

2024-05-24 08:34 UTC, StefanJum approved these changes
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2024-05-29 04:26 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2024-05-29 04:26 UTC, merged