lib/{ukfile, posix-socket, posix-unixsocket}: Add support for explicitly polled files & sockets
unikraft/unikraft pull request #1446
Opened 2024-06-04 14:18 UTC by andreittr

### Description of changes

This changeset adds `ukfile` support for explicitly polled files. These files accomodate drivers that, in contrast to the present `ukfile` event polling model, maintain events internally and cannot or will not signal falling edges of events, and thus cannot have `ukfile` maintain event levels for them.
Explicitly polled files provide for this use-case by allowing drivers to implement a custom `poll` operation, which shall be called whenever consumer code requests the instantaneous levels of events. Signaling rising edges of events remains the responsibility of the driver.

Sockets can similarly be explicitly polled, with the API of `posix-socket` changed to accomodate this.
Unix sockets are patched by this PR; LWIP requires a patch for the new API.

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): [e.g. `x86_64` or N/A]
 - Platform(s): [e.g. `kvm`, `xen` or N/A]
 - Application(s): [e.g. `app-python3` or N/A]

### Additional configuration

N/A

2025-02-06 11:10 UTC, andreittr commented
Rebased to current staging

2025-02-07 10:50 UTC, michpappas requested changes
@andreittr very minor comments here. Also: out-of-scope for this PR, but although the README.md` provides very good description of the underlying concepts, as someone getting familiar with `libukfile` for the first time, I found that it would be really helpful if the APIs for the driver and user as well as the config options were documented too.

2025-02-07 10:50 UTC, michpappas commented on lib/ukfile/include/uk/file/pollqueue.h
> +uk_pollevent uk_pollq_poll_level(struct uk_pollq *q, uk_pollevent req,
Since you've documented all functions in this header, maybe consider if this one should be documented too.

2025-02-07 10:50 UTC, michpappas commented on lib/ukfile/Config.uk
> +config LIBUKFILE_POLLED
As a general note: Looking at `pollqueue.h` it seems that there is some ambiguity in naming within config, documentation, and the API, when it comes to managed / polled and edge / level (triggered).

Also out of curiosity - and without implying that they should be changed - what makes these options qualify as invisible compared to visible options offered by other libraries?

2025-02-07 10:50 UTC, michpappas commented on lib/ukfile/include/uk/file/pollqueue.h
> +typedef uk_pollevent (*uk_poll_func)(const struct uk_file *f,
Since this needs to implemented by drivers perhaps it would be worth documenting its parameters and return value. More importantly, as I see you don't do any error handling when calling this function, is that a design choice that drivers cannot err here?

2025-02-07 11:34 UTC, andreittr commented on lib/ukfile/include/uk/file/pollqueue.h
> +typedef uk_pollevent (*uk_poll_func)(const struct uk_file *f,
> worth documenting its parameters and return value

Agreed, I'll expand the docstring.

> is that a design choice that drivers cannot err here?

Yes; `uk_pollevent` is defined as a "set of active events" and has no reserved value to signal "error in retrieving events".
I can't easily think of a situation where such an error can (1) occur, (2) be safely recoverable, and (3) meaningfully different from returning 0 (no events set). But if we do encounter such, I believe there are unused bits in `uk_pollevent` that we can reserve for this purpose.
I chose to not reserve such an error bit unless needed and used, because it would otherwise require input validation in all other funcs (set/clear/assign) that take event sets.

2025-02-07 11:56 UTC, andreittr commented on lib/ukfile/Config.uk
> +config LIBUKFILE_POLLED
> that there is some ambiguity in naming within config, documentation, and the API, when it comes to managed / polled and edge / level (triggered).

Yes, the double naming scheme came about as a result of thinking at different abstraction layers when designing&writing (file vs. raw pollqueue); I can't say I'm fully happy with it either, nor with the general naming tbh (pollqueue should really have been called eventqueue :sweat_smile: ). I'll have a closer look and see if I can harmonize these.

> what makes these options qualify as invisible compared to visible options offered by other libraries?

If you mean why are they hidden as opposed to user-visible: these options control extensions to the ukfile API that:
- are _not_ required by for general use, but provide special accomodations to other libs:
  - chainupdate & finalizers support complex callers (unixsockets delegating to pipes & epoll autoremove shenanigans)
  - explicitly polled files support drivers that can't do falling-edge notifications
- have a (marginal) runtime cost -- so keeping them always-on when not needed would be wasteful
- have _no_ user-visible behavior (other than the aforementioned runtime cost)
- are _only_ relevant as part of the API negociation between `ukfile` and its set of consuming libraries
- make no sense to be manually enabled; only to be `select`ed by dependent libs

There is ofc an architectural discussion to be had on what should constitute a user-visible configuration knob vs. internal flag; but I feel this use-case is closer in concept to `#define _GNU_SOURCE` before including a libc header than to a true degree of freedom in config.

2025-02-10 11:09 UTC, michpappas commented on lib/ukfile/include/uk/file/pollqueue.h
> +typedef uk_pollevent (*uk_poll_func)(const struct uk_file *f,
Okay fair enough, just wanted to make sure it was a intentional design decision. Thanks for the explanation, sounds reasonable.

2025-02-10 11:19 UTC, michpappas commented on lib/ukfile/Config.uk
> +config LIBUKFILE_POLLED
> I'll have a closer look and see if I can harmonize these.

Okay, it was more of a general comment, not necessarily for this PR. Up to you.

> I feel this use-case is closer in concept to #define _GNU_SOURCE before including a libc header than to a true degree of freedom in config

Yeah okay. So far we didn't pay attention to differentiate between options that make or don't make sense to be visible to the user; most of the time if a library *requires* something it just makes a hard select. And an arch-wide definition is a can of worms I don't want to open as I anticipate it will be hard to come up with solid rules.  But I do see your point, though, and it sounds reasonable, so let's keep as is.

2025-02-13 07:08 UTC, michpappas approved these changes
Reviewed-by: Michalis Pappas <michalis@unikraft.io>

2025-02-14 02:15 UTC, michpappas commented
Approved-by: Michalis Pappas <michalis@unikraft.io>

2025-02-14 02:16 UTC, merged