build: Option to switch stack frame pointers on and off
unikraft/unikraft pull request #185
Opened 2021-04-16 09:15 UTC by skuenzer

Introduces a configuration option for activating or deactivating the use of stack frame pointers. Frame pointers reserve one CPU register permanently but simplify stack walks for debugging purposes.

2021-08-18 05:42 UTC, albisorua approved these changes
Reviewed-by: Andrei Albisoru <andreialbisoru98@gmail.com>

2021-11-29 15:00 UTC, marcrittinghaus requested changes
Just some typos. Otherwise, looks good 👍🏻

2021-11-29 15:00 UTC, marcrittinghaus commented on Config.uk
> +		Reserves one CPU register for uisng it as stack frame pointer.
```suggestion
		Reserves one CPU register for using it as stack frame pointer.
```

2021-11-29 15:00 UTC, marcrittinghaus commented on Config.uk
> +		Functions are instrumented to to save, set up, and restore frame
```suggestion
		Functions are instrumented to save, set up, and restore frame
```

2021-11-29 15:00 UTC, marcrittinghaus commented on Config.uk
> +		pointers. This options simplifies doing stack walks for
```suggestion
		pointers. This option simplifies doing stack walks for
```

2021-11-29 21:11 UTC, skuenzer commented
Thanks for finding these typos. I just fixed them.

2021-11-29 21:57 UTC, marcrittinghaus approved these changes
Approved-by: Marc Rittinghaus <marc.rittinghaus@kit.edu>

2021-11-30 11:58 UTC, closed without merging