build: Introduce `mk_sub_libbuild_dir`
unikraft/unikraft pull request #194
Opened 2021-04-26 14:35 UTC by skuenzer

Inline with `mk_sub_build_dir`, this commit introduces `mk_sub_libbuild_dir` that enables creating a sub build directory for a library. This new Makefile command has two parameters: (1) library name, (2) sub directory structure.

This can be handy when writing library `Makefile.uk`'s that require additional directory structures within the build target directory:
``` Makefile
$(eval $(call addlib_s,libexample,$(CONFIG_LIBUKSTORE)))
$(call mk_sub_libbuild_dir,libexample,include/uk)

LIBEXAMPLE_GEN_INCLUDES := $(call sub_libbuild_dir,libexample,include/uk)

# <...>
```

2021-04-27 11:00 UTC, craciunoiuc requested changes
Hey @skuenzer,

All good here. There is just one small typo you need to fix and everything will be ok.

Cezar

2021-04-27 11:00 UTC, craciunoiuc commented on support/build/Makefile.rules
> +# creates a sub build directory for a lbrary
There is a small typo here:

```suggestion
# creates a sub build directory for a library
```

2021-05-05 14:56 UTC, skuenzer commented on support/build/Makefile.rules
> +# creates a sub build directory for a lbrary
Thanks, I fixed it in the new version

2021-05-05 17:47 UTC, craciunoiuc approved these changes
@skuenzer

Looks good to me.

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@gmail.com>

2021-05-05 17:49 UTC, closed without merging