plat/x86
unikraft/unikraft pull request #230
Opened 2021-06-15 06:15 UTC by marcrittinghaus

This PR changes the trap handling in KVM and XEN to use the event-based trap interface. This means, it adds code to raise the corresponding trap event in the architectural trap. A list of implemented trap events and a context data structure that is supplied to handlers is provided in `uk/arch/traps.h`.

For example, adding a page fault handler can be done in the following way:
```
#include <uk/arch/traps.h>
static int my_pagefault_handler(void *data)
{
	struct ukarch_trap_ctx *ctx = (struct ukarch_trap_ctx *)data;

	return UK_EVENT_HANDLED;
}
UK_EVENT_HANDLER_PRIO(TRAP_PAGE_FAULT, my_pagefault_handler, UK_PRIO_LATEST);
````
The same code will work with other architectures (e.g., arm64). However, the `ukarch_trap_ctx` structure may change.

**NOTE**: This code depends on [PR 227 - include/event: Add uk_event for new trap interface](https://github.com/unikraft/unikraft/pull/227). To be able to build this PR independently, this PR branches off of PR 227. It should be seamlessly mergeable.

2022-02-05 06:22 UTC, razvand commented
@marcrittinghaus , could you please rebase this?

2022-03-25 17:32 UTC, marcrittinghaus commented
Changed `TRAP_*` to `UKARCH_TRAP_*` to avoid potential name clashes.

2022-03-29 10:04 UTC, skuenzer requested changes
Could you adopt the title since this PR just adopts KVM and xen, not linuxu.
Something like `plat/kvm, /plat/xen: x86: Use event-based trap interface`

2022-03-29 10:11 UTC, marcrittinghaus commented
> Could you adopt the title since this PR just adopts KVM and xen, not linuxu. Something like `plat/kvm, /plat/xen: x86: Use event-based trap interface`

This would actually be too long.

2022-03-29 10:35 UTC, skuenzer approved these changes
Thanks a lot for the updates. I am good with this PR @razvand .

Reviewed-by: Simon Kuenzer <simon@unikraft.io>

2022-03-29 11:15 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>

2022-03-29 11:31 UTC, closed without merging