Makefile.rules: add support for extra CFLAGS
unikraft/unikraft pull request #255
Opened 2021-07-14 09:51 UTC by hlef

Additional flags can now be passed to the compiler via CFLAGS_EXTRA, e.g.:

    make CFLAGS_EXTRA="-DSOME_MACRO=0"

Update the documentation as well.

Signed-off-by: Hugo Lefeuvre <hugo.lefeuvre@manchester.ac.uk>

2021-07-15 09:03 UTC, skuenzer requested changes
Hey, you should remove the EXTRA_ARCHFLAGS, other from this I am fine with this PR. ;-)

Thanks,

Simon

2021-07-15 09:03 UTC, skuenzer commented on support/build/Makefile.rules
> +		       $$(ARCHFLAGS) $$(ARCHFLAGS-y) $$(ARCHFLAGS_EXTRA) \
We shouldn't enable the ARCHFLAGS_EXTRA, the archflags are really build system specific and every compilation unit receives ARCHFLAGS, actually. We should only include language-specific extra flags.

2021-07-15 09:03 UTC, skuenzer commented on doc/guides/developers-app.rst
> +Additional flags can be passed to the compiler via ``CFLAGS_EXTRA``, e.g.:
Maybe mention that extra flags are language specific

2021-07-15 13:22 UTC, hlef commented
Thanks a lot for the review Simon, I have updated the PR.

2021-07-19 10:52 UTC, skuenzer approved these changes
Hi Hugo,
thanks a lot for your changes. This looks good to me!
Thanks,
Simon

Reviewed-by: Simon Kuenzer <simon.kuenzer@neclab.eu>

2021-07-26 16:09 UTC, closed without merging