lib/ukalloc: Register allocator statistics to `ukstore`
unikraft/unikraft pull request #279
Opened 2021-09-03 16:26 UTC by craciunoiuc

This adds the allocator statistics to `ukstore` as an example for the USoC21 hackathon.
The implementation is just for showcase purposes and is not final/ready for `staging`.

Please merge the ukstore PR first.

Signed-off-by: Cezar Craciunoiu <cezar.craciunoiu@gmail.com>

2022-01-10 22:12 UTC, albisorua approved these changes
Looks good. Tested.

Signed-off-by: Andrei Albisoru andreialbisoru98@gmail.com

2022-01-19 12:16 UTC, nderjung commented
Depends on #202.

2022-06-09 23:45 UTC, skuenzer requested changes
Hi @craciunoiuc ,

thanks for your work. I think we should do it slightly different: `ukalloc` already provides the interface `uk_alloc_stats_get_global()` globally, I see less of an advantage in forwarding the struct also through `ukstore`. Users would need to include ukalloc headers to get the struct defintion and then they actually could just use the `ukalloc`API directly. I would also avoid doing any allocations in the entry callbacks, if possible.
Overall, I think that it is probably more meaningful if we export some individual and selected numbers from the stats directly, like:
```c
static int get_mem_free(void *cookie __unused, __u64 *out)
{
   *out = (u64) uk_alloc_availmem_total(void);
}
UK_STORE_STATIC_ENTRY(mem_free, u64, get_mem_free, NULL);

#if CONFIG_LIBUKALLOC_IFSTATS_GLOBAL
static int get_mem_used(void *cookie __unused, __u64 *out)
{
   struct uk_alloc_stats stats;

   uk_alloc_stats_get_global(&stats);
   *out = (u64) cur_mem_use;
   return 0;
}
UK_STORE_STATIC_ENTRY(mem_used, u64, get_mem_used, NULL);

static int get_nb_allocs(void *cookie __unused, __u64 *out)
{
   struct uk_alloc_stats stats;

   uk_alloc_stats_get_global(&stats);
   *out = (u64) cur_nb_allocs;
   return 0;
}
UK_STORE_STATIC_ENTRY(nb_allocs, u64, get_nb_allocs, NULL);
#endif /* CONFIG_LIBUKALLOC_IFSTATS_GLOBAL */
```

2022-06-10 08:47 UTC, craciunoiuc commented
Hey, yes, this is what I wanted to do initially. This PR was more like a Draft until now, I kind of forgot about it too 😓

I will do an ukstore entry for each stat

2022-06-10 14:23 UTC, skuenzer approved these changes
Thanks a lot for the changes and work! This looks good.

Reviewed-by: Simon Kuenzer <simon.kuenzer@neclab.eu>
Approved-by: Simon Kuenzer <simon.kuenzer@neclab.eu>

2022-06-11 11:27 UTC, closed without merging