lib/ukargparse: Add basic tests
unikraft/unikraft pull request #280
Opened 2021-09-04 09:28 UTC by cryeprecision

### Prerequisite checklist

 - [X] Read the [contribution guidelines](https://docs.unikraft.org/contribute.html) regarding submitting new changes to the project;
 - [X] Tested your changes against relevant architectures and platforms;
 - [X] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [X] Updated relevant documentation.

### Additional configuration

 - `CONFIG_LIBUKARGPARSE_TESTS=y`
 - `CONFIG_LIBUKARGPARSE_TESTS_PARSE=y`
 - `CONFIG_LIBUKARGPARSE_TESTS_NULL=y`
 - `CONFIG_LIBUKARGPARSE_TESTS_EXTRA=y`

### Description of changes

Added some basic tests for the `ukargparse`-library.

2021-09-28 10:13 UTC, nderjung requested changes
Hi @cryeprecision, thanks for PR and the great work at [USoC21](https://usoc21.unikraft.org)!

To get this PR ready to be merged, please can you:

 * Remove the `uktest` base commits (4f3bb8c through 8ef440e) as these will be introduced via separate PRs and so will cause a merge conflict;
  * Please check the results of the `checkpatch.pl` script, there seem to be errors whiich need address.

Thanks again!

Depends-on: #218

2021-09-28 10:13 UTC, nderjung commented on lib/ukargparse/tests/test_ukargparse_parse.c
> + *                     All rights reserved.
You can contribute the copyright to yourself, it does not necessarily need to be NEC :)

2021-11-27 09:26 UTC, razvand commented
@cryeprecision , can you take at look at this PR and make the requested fixes?

2022-02-05 12:08 UTC, razvand commented
This will be closed, since it has been resubmitted by @StefanJum in #392

2022-02-05 12:08 UTC, closed without merging