uklock/mutex metrics for ukstore
unikraft/unikraft pull request #282
Opened 2021-09-04 14:58 UTC by RaduMantu

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://docs.unikraft.org/contribute.html) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): `x86_64`
 - Platform(s): `kvm`
 - Application(s): N/A

### Description of changes

Added a new static `ukstore` entry and metric collection for `uklock/mutex`. These include active (un)locked mutex objects and total (un)successful (un)locks since startup.

Based on Cezar's branch: [ukstore_fixed_tree](https://github.com/craciunoiuc/unikraft/tree/ukstore_fixed_tree).

2021-09-28 09:53 UTC, nderjung commented
Hi @RaduMantu, thanks for submitting this PR and for the great work at [USoC21](https://usoc21.unikraft.org)!

To get this PR ready to be merged, please can you:

 * Remove the `ukstore` and `uktest` base commits; these libraries will be introduced by separate PRs (commits 0d2aa9e through 8ef440e need to be removed);
  * Please can you prefix all commit messages with `uklock: `;
  *  Please check the results of the `checkpatch.pl` program; looks like it failed.
  
  Thanks again!

2021-11-08 13:22 UTC, RaduMantu commented
Hi. Again, sorry for the delay.

I removed Cezar's commits and squashed / reworded mine. `checkpatch` should't cause any issues but I'll follow up once `ukstore` and `uktest` are integrated.

2021-11-20 09:41 UTC, craciunoiuc requested changes
Hey @RaduMantu,

Thank you for your contributions.
I left you some comments in this review regarding your PR. Please address them before it can be merged.

Some additional notes regarding the PR:
 * In the commit description `currently` -> `Currently`
 * In the commit title `uklock:` -> `lib/uklock:`
 * Please change the PR title, as it won't be directly related to `ukstore` (it should be independent of it)
 * Suggestion: I would split this commit into 3:
   1. Registers the option inside `Config.uk`
   2. Registers the ctor with the init function & adds the new symbols
   3. Implements the decrementing/incrementing of fields

I was able to run run this PR and it worked as intended, functionality-wise there are no problems 🙂 

Cezar

2021-11-20 09:41 UTC, craciunoiuc commented on lib/uklock/include/uk/mutex.h
> +extern spinlock_t              mutex_metrics_lock;
I would prefix these like (and their other appearances, of course):
```
mutex_metrics;        -> _uk_mutex_metrics;
mutex_metrics_lock;   -> _uk_mutex_metrics_lock;
```

This is to ensure that there won't be name conflicts in the future (someone might create another `mutex_metrics` symbol).

2021-11-20 09:41 UTC, craciunoiuc commented on lib/uklock/include/uk/mutex.h
> +#include <string.h>
Those might be worth protecting with `#ifdef CONFIG_LIBUKLOCK_MUTEX_METRICS` guards

2021-11-20 09:41 UTC, craciunoiuc commented on lib/uklock/mutex.c
> +#include <uk/store.h>
Remove `#include <uk/store.h>`. The linking to `ukstore` can be introduced as another PR

2021-11-20 09:41 UTC, craciunoiuc commented on lib/uklock/mutex.c
> +UK_STORE_STATIC_ENTRY(mutex_stats, uptr, uk_mutex_metrics_get, NULL);
Also, remove this, as it is related to `ukstore`. It can be introduced back as a separate `ukstore` PR in the future.

2021-11-20 09:41 UTC, craciunoiuc commented on lib/uklock/mutex.c
> + * @return 0 on success, !0 otherwise.
It says it returns !0 on fail, but I only see a `return 0;`.

2021-11-20 09:41 UTC, craciunoiuc commented on lib/uklock/mutex.c
> +#include <stdlib.h>
Also remove these 2. They are only needed in the `ukstore` context.

2021-11-26 13:56 UTC, RaduMantu commented
Hey @craciunoiuc,

I've addressed the problems that you pointed out in your last review. Thanks for the feedback, btw.
Let me know if I missed anything.

2021-11-26 15:11 UTC, craciunoiuc requested changes
Hey @RaduMantu,

This should be the last round before this PR is approved. I had a few more ideas and added them as suggestions. Feel free to move them around to better places.

Cezar

2021-11-26 15:11 UTC, craciunoiuc commented on lib/uklock/mutex.c
> +struct uk_mutex_metrics _uk_mutex_metrics;
```suggestion
struct uk_mutex_metrics _uk_mutex_metrics = { 0 };
```

Easily initialize everything to 0 so there is no need for `memset`

2021-11-26 15:11 UTC, craciunoiuc commented on lib/uklock/mutex.c
> +	memset(&_uk_mutex_metrics, 0, sizeof(_uk_mutex_metrics));
```suggestion
```

You can remove this, as the structure is initialized to 0

2021-11-26 15:11 UTC, craciunoiuc commented on lib/uklock/exportsyms.uk
> +_uk_mutex_metrics
```suggestion
_uk_mutex_metrics
uk_mutex_get_metrics
```

Add a function to retrieve the structure with metrics

2021-11-26 15:11 UTC, craciunoiuc commented on lib/uklock/mutex.c
> +
```suggestion
void uk_mutex_get_metrics(struct uk_mutex_metrics *dst)
{
	UK_ASSERT(dst);

	ukarch_spin_lock(&_uk_mutex_metrics_lock);
	memcpy(dst, &_uk_mutex_metrics, sizeof(*dst));
	ukarch_spin_unlock(&_uk_mutex_metrics_lock);
}
```

A separate function can do the retrieval so users do not use the `_uk_mutex_metrics` directly.

2021-11-26 15:11 UTC, craciunoiuc commented on lib/uklock/include/uk/mutex.h
```suggestion
#ifdef CONFIG_LIBUKLOCK_MUTEX_METRICS
void uk_mutex_get_metrics(struct uk_mutex_metrics *dst);
#endif /* CONFIG_LIBUKLOCK_MUTEX_METRICS */
```

2021-11-26 15:27 UTC, craciunoiuc commented on lib/uklock/mutex.c
> +
You might need to include something `#include <uk/assert.h>`

2021-11-26 15:44 UTC, RaduMantu commented
Thanks for the suggestions, @craciunoiuc.

2021-11-26 15:48 UTC, craciunoiuc commented
All good now. I tested it and it works.

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@gmail.com>

2021-11-26 15:49 UTC, craciunoiuc approved these changes
All good now. I tested it and it works.

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@gmail.com>

2021-11-26 16:16 UTC, RaduMantu commented
Fixed some `checkpatch` warnings. My bad.

2021-11-26 16:35 UTC, craciunoiuc commented
I guess I rushed with the approval before checkpatch. Sorry

2021-11-26 16:36 UTC, craciunoiuc approved these changes
All good now. I tested it and it works.

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@gmail.com>

2021-11-30 18:08 UTC, nderjung approved these changes
Great! Thanks 🐒 

Approved-by: Alexander Jung <a.jung@lancs.ac.uk>

2021-11-30 18:10 UTC, closed without merging