plat/common/arm: Add psci definitions in psci headers
unikraft/unikraft pull request #295
Opened 2021-09-24 16:10 UTC by razvanvirtan

Add three psci headers (1 for common definitions + 2 to cover both arm and arm64).
Remove psci definitions from `cpu_defs.h`.

Signed-off-by: Răzvan Vîrtan <virtanrazvan@gmail.com>, Justin He <justin.he@arm.com>

2021-09-26 14:03 UTC, cristian-vijelie requested changes
It looks good, except some minor esthetic things. I'll also test if everything builds/ runs as it should, and update this comment.

2021-09-26 14:03 UTC, cristian-vijelie commented on plat/common/include/arm/psci.h
> +#endif /* __PLAT_CMN_ARM_PSCI_H__ */
You missed a newline at the end of the file.

2021-09-26 14:03 UTC, cristian-vijelie commented on plat/common/include/arm/psci.h
> +#define PSCI_RET_NOT_SUPPORTED			-1
```suggestion
#define PSCI_RET_NOT_SUPPORTED		-1
```

2021-09-26 14:03 UTC, cristian-vijelie commented on plat/common/include/arm/psci.h
> +#define PSCI_RET_NOT_SUPPORTED			-1
Same for the lines below. Make sure the values are aligned nicely.

2021-09-26 14:03 UTC, cristian-vijelie commented on plat/common/include/arm/arm64/psci.h
> +#define	PSCI_FNID_VERSION		0x84000000
I think the defines should be consistent:
#define\<space\>\<whatever\>

2021-09-26 14:03 UTC, cristian-vijelie commented on plat/common/include/arm/arm/psci.h
> +#define	PSCI_FNID_VERSION		0x84000000
I think it would be cleaner if you used space after the define, instead of tab

2021-09-26 15:26 UTC, cristian-vijelie approved these changes
Good to merge.

Reviewed-by: Cristian Vijelie <cristianvijelie@gmail.com>

2021-09-28 07:45 UTC, michpappas reviewed
Hi @razvanvirtan, is there any particular reason for different headers for arm and arm64? Perhaps it would be better to avoid unnecessary duplication, as it's error-prone in the long term.

2021-09-28 09:55 UTC, razvanvirtan commented
> Hi @razvanvirtan, is there any particular reason for different headers for arm and arm64? Perhaps it would be better to avoid unnecessary duplication, as it's error-prone in the long term.

Hi @michpappas , there are some psci function codes that have different value on arm vs. arm64 (like `PSCI_FNID_CPU_SUSPEND`, `PSCI_FNID_CPU_ON `).

2021-09-28 10:45 UTC, michpappas commented
Ah didn't notice, sorry. LGTM.

Reviewed-by: Michalis Pappas <michalis.pappas@opensynergy.com>

2021-09-28 14:20 UTC, closed without merging