Update struct sigset_t to 128bits and macros
unikraft/unikraft pull request #326
Opened 2021-11-08 08:11 UTC by dragosargint

Signed-off-by: Dragos Iulian Argint <dragosargint21@gmail.com>

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://docs.unikraft.org/contribute.html) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [`x86_64`]
 - Platform(s): [`kvm`]

### Additional configuration

Include `uksignal` from menuconfig.
### Description of changes

As newlib uses a 64bits mask for signals and musl uses 128bits mask we need a unified way for those to work
with the underlying signal processing. This is what this PR intends to do.

2021-11-17 08:46 UTC, craciunoiuc requested changes
Hey @dragosargint,

Please update your review as discussed to switch from 128bits to 1024bits.

Cezar

2021-11-20 12:37 UTC, dragosargint commented
> Hey @dragosargint,
> 
> Please update your review as discussed to switch from 128bits to 1024bits.
> 
> Cezar

Hi, @craciunoiuc,

The signal mask in both musl and glibc does have 1024 bits, but this is done for signals that can be added later in Linux. In reality, this mask needs only 64 bits, equivalent to the 62 signals we have on Linux (signo 32, and 33 do not exist). On the other hand, newlib uses only a 64-bit mask. So this PR aims to provide support for both musl and newlib.

2021-11-21 10:36 UTC, craciunoiuc commented
Hey @dragosargint,

All good now. I tested the PR and it works.

Reviewed-By: Cezar Craciunoiu <cezar.craciunoiu@gmail.com>

2021-11-24 11:01 UTC, craciunoiuc approved these changes
Hey @dragosargint,

All good now. I tested the PR and it works.

Reviewed-By: Cezar Craciunoiu <cezar.craciunoiu@gmail.com>

2021-11-27 18:16 UTC, marcrittinghaus commented
@craciunoiuc, @dragosargint
Please ensure that the commit messages contain a clear description of the problem and the solution.

Then I am not sure I understand this correctly. Is there a PR for `lib-newlib` and `nolibc`? According to [signal.h:L63](https://github.com/unikraft/lib-newlib/blob/286d5b8ae7c4b9d14e9bf269389e2d37ef60bcc5/musl-imported/include/signal.h#L63), our version of `lib-newlib` defines `sigset_t` as `unsigned long`. Obviously, the new macros won't work with this, but only with the definition from `musl`. The same is true for `nolibc` [signal.h:L63](https://github.com/unikraft/unikraft/blob/ec8882b8e34346fd890c04d15257316895b7de21/lib/nolibc/musl-imported/include/signal.h#L63).

2021-11-27 18:26 UTC, craciunoiuc commented
Hey @marcrittinghaus,

Thanks for the comment suggestion. @dragosargint please also add the explanation from this discussion to the commit description.

Yes, there is a separate PR for updating the structure redefinition (https://github.com/unikraft/unikraft/pull/327).
I'm not 100% sure how the macros will behave with `newlib` as I only look at them from the `musl`/`nolibc` perspective.

2021-11-30 15:37 UTC, marcrittinghaus commented
This won't work with `newlib`, I think. 

@dragosargint Please have a look and publish a PR similar to `nolibc` for `lib-newlib`. Otherwise, we'll break builds with `lib-newlib` with this PR.

2021-12-01 01:40 UTC, dragosargint commented
Hi @craciunoiuc, @marcrittinghaus. First of all, I would like to mention that these PRs ((327)[https://github.com/unikraft/unikraft/pull/327 ] and (326)[https://github.com/unikraft/unikraft/pull/326] ) were made initially by Bernard and I took them over. So there are things that I missed too. In my work with musl, I only used (326)[https://github.com/unikraft/unikraft/pull/326 ]). The reason why this PR is necessary is that when you try to compile an application that uses both uksignal and musl some compilation errors are encountered. These can be seen in the photo attached. This is due to the `sigset_t` structure which is defined in musl as follows: 
```
typedef struct __sigset_t { unsigned long __bits[128/sizeof(long)]; } sigset_t;
```
However, in `uksignal` the macros that are used are not suitable for this structure. Hence the changes from this PR.
On the other hand, `newlib` does indeed define `sigset_t` as an `unsigned long` and this PR will break compilation for it (I didn't know that last week when I made the changes to this PR). I tried for a few hours to make a change like PR (327) [https://github.com/unikraft/unikraft/pull/327/commits/d7e8ed6eb4542dd8de20c6f24fba5511ab581eee]  for `newlib`, but unfortunately, this is not as straight forward and it still gives some compilation errors. So I will need more time to look into it.

2022-02-22 21:08 UTC, craciunoiuc requested changes
Hey @marcrittinghaus,

I tested the PR and it worked just fine with the others (newlib/nolibc/musl)

@dragosargint please reformat the commit message adding the required `selector` and some additional description

2022-02-22 21:18 UTC, dragosargint commented
Done!

2022-02-23 08:53 UTC, craciunoiuc approved these changes
Hey @marcrittinghaus @dragosargint,

I think the PR looks good now. I hope I didn't miss anything.

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@gmail.com>

2022-03-24 08:31 UTC, marcrittinghaus requested changes
Hi @dragosargint,

looks good so far. I have one point just to keep definitions clean and to not create error-prone and confusing duplicates.

2022-03-24 08:31 UTC, marcrittinghaus commented on lib/uksignal/include/uk/uk_signal.h
> +
Hi @dragosargint

These macros are only used within `lib/uksignal` and are not part of the official libc headers. I thus agree that it makes sense to define them here. Could you then also remove the definitions in `lib-newlib` and `nolibc` so we have the same source of definition no matter what libc we are using? Then you can also remove the `#ifndef` barriers.

2022-05-26 08:27 UTC, closed without merging