Update sigset_t from nolibc to 128 bits
unikraft/unikraft pull request #327
Opened 2021-11-08 08:26 UTC by dragosargint

Signed-off-by: Dragos Iulian Argint <dragosargint21@gmail.com>

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://docs.unikraft.org/contribute.html) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [`x86_64`]
 - Platform(s): [`kvm`]

### Description of changes

This PR modifies the sigset_t structure to 128 bits for nolibc. The 128bits signal mask is musl imported.

2021-11-17 08:49 UTC, craciunoiuc reviewed
Hey @dragosargint,

This PR is good, but you need to change the other one (#326) first.

Maybe also change this one's name to reflect it is actually on 1024 bits.

Cezar

2021-11-21 10:36 UTC, craciunoiuc commented
Hey @dragosargint,

All good now. I tested the PR and it works.

Reviewed-By: Cezar Craciunoiu <cezar.craciunoiu@gmail.com>

2021-11-24 11:01 UTC, craciunoiuc approved these changes
Hey @dragosargint,

All good now. I tested the PR and it works.

Reviewed-By: Cezar Craciunoiu <cezar.craciunoiu@gmail.com>

2021-11-30 15:32 UTC, marcrittinghaus requested changes
@dragosargint

Also for this PR (just like with #326 , please add a description to the commit message that justifies the change.

2022-02-22 21:08 UTC, craciunoiuc commented
Hey @marcrittinghaus,

After the new set of changes to the PR set, this one still works, so it should be okay. I tested it and couldn't find anything out of the ordinary with it

@dragosargint please reformat the commit message to add some additional description for the change

2022-02-22 21:28 UTC, dragosargint commented
Done!

2022-02-23 08:53 UTC, craciunoiuc approved these changes
Hey @marcrittinghaus @dragosargint,

I think the PR looks good now.

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@gmail.com>

2022-03-24 08:49 UTC, marcrittinghaus commented
Will approve when all PRs in the series are ok.

2022-05-26 08:25 UTC, closed without merging