lib/ukmmap: Fix some bugs and add mprotect
unikraft/unikraft pull request #394
Opened 2022-02-10 14:23 UTC by marcrittinghaus

### Prerequisite checklist

 - [X] Read the [contribution guidelines](https://docs.unikraft.org/contribute.html) regarding submitting new changes to the project;
 - [X] Tested your changes against relevant architectures and platforms;
 - [X] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [X] Updated relevant documentation.

### Base target

 - Architecture(s): [N/A]
 - Platform(s): [N/A]
 - Application(s): [N/A]

### Additional configuration

`CONFIG_LIBUKMMAP=y`

### Description of changes

This PR fixes two bugs:
* Callers of `mmap` expect anonymous memory to be zeroed. The patch adds a `memset` to do so.
* The `munmap` call tries to remap remaining memory to a smaller area. However, the caller won't have a chance to be informed about the changing base address of the area. Changing the base address also violates POSIX. As we are not able to free parts of the memory area, we have to keep it unchanged and silently fail. We only free it, if the caller unmaps the whole area.

In addition, the PR introduces a stub for `mprotect`.

2022-03-19 10:31 UTC, StefanJum requested changes
I think the memset that zeroes the memory should be done after we check if the `mem` variable is `NULL` [here](https://github.com/unikraft/unikraft/pull/394/files#diff-9cae6ee04f03a432adc2090da51d2d0dec431feda48f720db65e882db397d2bbR102). If there is not enough space to allocate the new memory, the application crashes since it passes `NULL` to `memset`.

2022-03-21 09:28 UTC, marcrittinghaus commented
> I think the memset that zeroes the memory should be done after we check if the `mem` variable is `NULL` [here](https://github.com/unikraft/unikraft/pull/394/files#diff-9cae6ee04f03a432adc2090da51d2d0dec431feda48f720db65e882db397d2bbR102). If there is not enough space to allocate the new memory, the application crashes since it passes `NULL` to `memset`.

Yes, of course 🤦🏻‍♂️ Thanks for catching that! I updated the commit.

2022-03-21 16:31 UTC, StefanJum approved these changes
All good now!

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2022-03-26 15:59 UTC, hlef commented
Thanks for this PR @marcrittinghaus !

I had a look, it looks good overall. If necessary, we could merge it as-is.

That being said, I have a few nits to bring up:
- The comment before the implementation of `munmap` is now outdated. Outdated comments are so confusing. I'd be grateful if you could update it! :slightly_smiling_face: 
- My understanding after taking a quick look at the code is that the new implementation of `munmap` is going to leak memory forever if the caller frees chunks in bits (and not as a whole). This is fine for this PR as this is already a major improvement, but ultimately it'd be nice to address... And at any rate, we must have this clear somewhere, ideally with a NOTE or a FIXME comment in the code.

Do you think that you could address this for the release?

2022-03-27 15:59 UTC, marcrittinghaus commented
> Thanks for this PR @marcrittinghaus !
> 
> I had a look, it looks good overall. If necessary, we could merge it as-is.
> 
> That being said, I have a few nits to bring up:
> 
> * The comment before the implementation of `munmap` is now outdated. Outdated comments are so confusing. I'd be grateful if you could update it! 🙂
> * My understanding after taking a quick look at the code is that the new implementation of `munmap` is going to leak memory forever if the caller frees chunks in bits (and not as a whole). This is fine for this PR as this is already a major improvement, but ultimately it'd be nice to address... And at any rate, we must have this clear somewhere, ideally with a NOTE or a FIXME comment in the code.
> 
> Do you think that you could address this for the release?

Hi @hlef,

thanks for looking into this and pointing out the stale comment. I fixed it 👍🏻

Concerning your second point, this is actually something that cannot be fixed as `ukalloc` simply does not allow to emulate `munmap` with partial release. However, I will introduce `posix-mmap` at some point. This will use the paging code to properly implement the `mmap`-type syscalls. I am going to revisit `ukmmap` then and it will probably become obsolete or be replaced with a similar emulation in `posix-mmap` if paging is not available. I will then clearly point out limitations of `ukalloc`-based emulation.

2022-03-28 07:55 UTC, hlef commented
Hi Marc,

> Concerning your second point, this is actually something that cannot be fixed as `ukalloc` simply does not allow to emulate `munmap` with partial release. However, I will introduce `posix-mmap` at some point. This will use the paging code to properly implement the `mmap`-type syscalls. I am going to revisit `ukmmap` then and it will probably become obsolete or be replaced with a similar emulation in `posix-mmap` if paging is not available. I will then clearly point out limitations of `ukalloc`-based emulation.

Hum, don't you think that you could keep track of partially freed blocks in your ukalloc-based munmap implementation and free the whole block as soon as you got all the pieces? That'd have a bit of a cost for sure, but it could be optional. Of course, if the user never frees all sub-blocks ultimately, that wouldn't help, but in certain cases, it might. I don't think that it'd be very hard to implement. In another PR of course.

2022-03-28 07:56 UTC, hlef commented
Otherwise, thanks for updating!

Approved-by: Hugo Lefeuvre <hugo.lefeuvre@manchester.ac.uk>

2022-03-28 08:14 UTC, closed without merging

2022-03-28 08:14 UTC, marcrittinghaus commented
> Hi Marc,
> 
> > Concerning your second point, this is actually something that cannot be fixed as `ukalloc` simply does not allow to emulate `munmap` with partial release. However, I will introduce `posix-mmap` at some point. This will use the paging code to properly implement the `mmap`-type syscalls. I am going to revisit `ukmmap` then and it will probably become obsolete or be replaced with a similar emulation in `posix-mmap` if paging is not available. I will then clearly point out limitations of `ukalloc`-based emulation.
> 
> Hum, don't you think that you could keep track of partially freed blocks in your ukalloc-based munmap implementation and free the whole block as soon as you got all the pieces? That'd have a bit of a cost for sure, but it could be optional. Of course, if the user never frees all sub-blocks ultimately, that wouldn't help, but in certain cases, it might. I don't think that it'd be very hard to implement. In another PR of course.

Yes of course, this would work, but it is not the interface `ukalloc` exposes at the moment. So we would have to implement like a feature flag in `ukalloc` and upgrade our own allocators. Because allocators like mimalloc don't do it and you don't want to adapt these 😏

2022-03-28 08:17 UTC, marcrittinghaus commented
> Hi Marc,
> 
> > Concerning your second point, this is actually something that cannot be fixed as `ukalloc` simply does not allow to emulate `munmap` with partial release. However, I will introduce `posix-mmap` at some point. This will use the paging code to properly implement the `mmap`-type syscalls. I am going to revisit `ukmmap` then and it will probably become obsolete or be replaced with a similar emulation in `posix-mmap` if paging is not available. I will then clearly point out limitations of `ukalloc`-based emulation.
> 
> Hum, don't you think that you could keep track of partially freed blocks in your ukalloc-based munmap implementation and free the whole block as soon as you got all the pieces? That'd have a bit of a cost for sure, but it could be optional. Of course, if the user never frees all sub-blocks ultimately, that wouldn't help, but in certain cases, it might. I don't think that it'd be very hard to implement. In another PR of course.

Yes, of course, this can be done and I guess should be part of a more proper emulation in `posix-mmap`. But as you said it won't actually free the memory until the whole region is unmapped.

2022-03-29 11:26 UTC, nderjung commented
Hi, when compiling NGINX, I am now receiving:

```
/bin/../lib/gcc/x86_64-linux-gnu/9.2.0/../../../../x86_64-linux-gnu/bin/ld: /usr/src/unikraft/apps/nginx/build/libnewlibglue.o: in function `mprotect':
/usr/src/unikraft/libs/newlib/mem.c:72: multiple definition of `mprotect'; /usr/src/unikraft/apps/nginx/build/libukmmap.o:/usr/src/unikraft/unikraft/lib/ukmmap/mmap.c:194: first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [/usr/src/unikraft/unikraft/plat/kvm/Linker.uk:22: /usr/src/unikraft/apps/nginx/build/nginx_kvm-x86_64.dbg]
Error 1
make: *** [Makefile:1015: sub-make] Error 2
```

2022-03-29 11:30 UTC, marcrittinghaus commented
Ah. damn it. Yes, let me quickly do a PR for lib-newlib.