lib/vfscore: Fixing various bugs
unikraft/unikraft pull request #411
Opened 2022-02-15 18:46 UTC by marcrittinghaus

### Prerequisite checklist

 - [X] Read the [contribution guidelines](https://docs.unikraft.org/contribute.html) regarding submitting new changes to the project;
 - [X] Tested your changes against relevant architectures and platforms;
 - [X] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [N/A]
 - Platform(s): [N/A]
 - Application(s): [N/A]

### Additional configuration

- `CONFIG_LIBVFSCORE=y`

### Description of changes

This PR fixes a couple of bugs in `lib/vfscore` where:
+ `sys_fchdir` sets the wrong current working directory if the FS is not mounted at `/` (root)
+ the `read`/`write`/`stat` syscalls return values according to the C lib but not the raw syscall implementation

2022-02-16 14:40 UTC, craciunoiuc approved these changes
Hey @marcrittinghaus @skuenzer,

All good here 🙂 

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@gmail.com>

2022-02-17 13:41 UTC, marcrittinghaus commented
I think there is a problem when the syscall shim is not activated. That is why it is not building. Have to revise

2022-02-17 14:27 UTC, craciunoiuc commented
Hmm, strange, I am 99% sure I looked at the checks and they were okay. Also the build worked for me. Maybe I'm going crazy 😅 

I'll also recheck now

Edit: Nevermind, you are right, I forgot to check without the shim

2022-02-17 14:36 UTC, craciunoiuc requested changes
I removed the Reviewed-by tag, thanks for catching the error @marcrittinghaus 

Good thing we have a CI/CD pipeline

2022-03-29 08:29 UTC, marcrittinghaus commented
@craciunoiuc

I just had to move the definition of the `read` and `write` syscalls so that they are below the `readv` and `writev` syscalls. It works with the shim active because then you include a header with all the syscalls as forward declarations. So it should be good now.

2022-03-29 09:23 UTC, marcrittinghaus commented
Forgot to fix the outstanding checkpatch warning. Done.

2022-03-29 10:48 UTC, craciunoiuc approved these changes
All good! 🙏

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@gmail.com>

2022-03-29 10:49 UTC, skuenzer approved these changes
Thanks a lot for these fixes.

Approved-by: Simon Kuenzer <simon@unikraft.io>

2022-03-29 10:54 UTC, closed without merging