lib/posix-futex: Add initial futex implementation
unikraft/unikraft pull request #488
Opened 2022-07-03 12:40 UTC by adinasm

### Prerequisite checklist

 - [ ] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [ ] Tested your changes against relevant architectures and platforms;
 - [ ] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [N/A]
 - Platform(s): [N/A]
 - Application(s): [N/A]

### Additional configuration

 - `CONFIG_LIBPOSIX_FUTEX=y`

### Description of changes

This PR introduces `posix-futex` which contains the implementation for the futex system call. At the moment, it supports the following futex operations:
- `FUTEX_WAIT`
- `FUTEX_WAKE`
- `FUTEX_CMP_REQUEUE`

It also contains some basic tests for the aforementioned operations.

2022-07-16 22:28 UTC, aadhi0319 commented
**Menuconfig:**
- posix-futex
- syscall-shim
- uktest

Running `qemu-guest -k app-helloworld_kvm-x86_64` causes a crash on `posix_futex_testsuite->test_cmp_requeue_two_waiters_no_requeue`. @adinasm is this reproducible on your end?

2022-07-18 11:11 UTC, adinasm commented
Hi @aadhi0319, I cannot reproduce this crash. Can you give me more details about it?

2022-07-18 18:20 UTC, Sairajkodilkar commented
Hey @adinasm thanks for the PR

- Using a global spinlock, you should protect the `futex_list` because the list APIs `uk_list_add_tail`, `uk_list_for_each_safe` and `uk_list_del` are not SMP safe.

- Instead of iterating over the entire list, you can check if the thread is runnable or not.

2022-07-18 18:40 UTC, Sairajkodilkar requested changes

2022-07-18 18:40 UTC, Sairajkodilkar commented on lib/posix-futex/futex.c
> +
uk_spinlock futex_list_lock = UK_SPINLOCK_INITIALIZER()

2022-07-18 18:40 UTC, Sairajkodilkar commented on lib/posix-futex/futex.c
> +		/* Enqueue thread to wait list */
irqf = uk_plat_save_irqf();
uk_spin_lock(&futex_list_lock);

2022-07-18 18:40 UTC, Sairajkodilkar commented on lib/posix-futex/futex.c
> +
uk_spin_unlock(&futex_list_lock);
uk_plat_restore_irqf(irqf);

2022-07-18 18:40 UTC, Sairajkodilkar commented on lib/posix-futex/futex.c
> +		/* Thread is no longer blocked. Remove it from the futex list */
irqf = uk_plat_save_irqf();
uk_spin_lock(&futex_list_lock);

2022-07-18 18:40 UTC, Sairajkodilkar commented on lib/posix-futex/futex.c
> +
uk_spin_unlock(&futex_list_lock);
uk_plat_restore_irqf(irqf);

2022-07-18 18:40 UTC, Sairajkodilkar commented on lib/posix-futex/futex.c
> +
irqf = uk_plat_save_irqf();
uk_spin_lock(&futex_list_lock);

2022-07-18 18:40 UTC, Sairajkodilkar commented on lib/posix-futex/futex.c
> +
uk_spin_unlock(&futex_list_lock);
uk_plat_restore_irqf(irqf);

2022-07-26 20:36 UTC, adinasm commented
>     * In `futex_wait()` function instead of iterating over the entire list, you can check if the thread is runnable or not.

@Sairajkodilkar I'm not sure that the timed out thread should check if it's runnable. When `schedcoop_schedule()` is called, the expired threads are awaken [1]. This means that even though the thread timed out in `futex_wait()`, it would already be set as runnable by the time it resumes after `sched_yield()`. Please correct me if I'm wrong.

[1] https://github.com/unikraft/unikraft/blob/staging/lib/ukschedcoop/schedcoop.c#L87

2022-07-26 21:46 UTC, aadhi0319 requested changes
Thanks for the PR. Looks pretty good from what I can tell; just made a couple small suggestions. Once that test is fixed I'll run the test cases again and make sure that the tests pass on my end too.

2022-07-26 21:46 UTC, aadhi0319 commented on lib/posix-futex/tests/test_posix_futex.c
> +
It seems that `threads[3]` is not initialized. I am getting a crash when `uk_thread_wait(threads[3])` is called in the for loop below.

2022-07-26 21:46 UTC, aadhi0319 commented on lib/posix-futex/Config.uk
> +endif
Is there a way to enable `LIBSYSCALL_SHIM` if this library is added and all tests are enabled from `uktest` in menuconfig? In that scenario, there is an error during make which may be confusing to users who are not familiar with unikraft.

2022-07-26 21:46 UTC, aadhi0319 commented on lib/posix-futex/tests/test_posix_futex.c
> +/* TODO: Replace with the real futex system call number */
Has this TODO been implemented? If so, I would suggest removing this comment.

2022-07-27 18:43 UTC, adinasm commented on lib/posix-futex/tests/test_posix_futex.c
> +
Thanks, now I set the right number of threads.

2022-07-27 18:46 UTC, adinasm commented on lib/posix-futex/Config.uk
> +endif
I added another select in case all the tests are enabled from `uktest` and the error is gone now on my end.

2022-07-27 18:47 UTC, adinasm commented on lib/posix-futex/tests/test_posix_futex.c
> +/* TODO: Replace with the real futex system call number */
Removed it.

2022-07-29 15:03 UTC, Sairajkodilkar commented
Hi, @adinasm yeah, you are right about it!

2022-08-01 00:25 UTC, aadhi0319 requested changes

2022-08-01 00:25 UTC, aadhi0319 commented on lib/posix-futex/Config.uk
> +endif
I believe this has the opposite effect. From my understanding, this selects the option to run all uktests if libfutex tests are enabled, which is not the functionality we desire. We may need to modify the Config.uk for uktest to get the intended behavior. @razvand would probably be the best point of contact to determine how to address this (including whether we even need to address this).

2022-08-01 00:25 UTC, aadhi0319 commented on lib/posix-futex/tests/test_posix_futex.c
> +
All tests pass for me now.

2022-08-12 04:29 UTC, Sairajkodilkar commented
Hey @adinasm can you please resolve the checkpatch warnings

2022-08-19 14:26 UTC, skuenzer commented
This PR is okay from my side. I would approve as soon as review is finished.
Thanks,

Simon

2022-08-19 14:55 UTC, marcrittinghaus commented
I already use this PR successfully in a project that requires futexes and never had problems. So it seems to work quite well 😃👍🏻

2022-08-20 08:49 UTC, Sairajkodilkar commented
Hi @marcrittinghaus  the PR is okay from my side too.

2022-08-20 08:52 UTC, razvand approved these changes
All OK. Thanks, @adinasm 

Reviewed-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>

2022-08-20 09:20 UTC, skuenzer approved these changes
Approved-by: Simon Kuenzer <simon.kuenzer@neclab.eu>

2022-08-20 09:21 UTC, closed without merging