plat/virtio_pci: Fix buffer length argument when calling `virtio_cread_bytes_many`
unikraft/unikraft pull request #519
Opened 2022-08-14 12:55 UTC by eduardvintila

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [`x86_64`, `aarch64`]
 - Platform(s): [kvm]
 - Application(s): [redis, sqlite, nginx]

### Description of changes

This PR fixes an incorrect call to the `virtio_cread_bytes_many` function which is used to read a virtio PCI device's configuration. The function expects a `len` argument which is the total size of the buffer where the configuration bytes will be copied. However, the `vpci_legacy_pci_config_get` function invokes this routine by specifying the number of elements in the buffer, not its total size in bytes. This results in issues for example in the 9pfs filesystem initialization phase, where the filesystem tag (usuallly `fs0`) is incorrectly read and could result in filesystem setup failure. Problems could even arise past the configuration phase. More detalis can be found here in Issue #518 made by @mariasfiraiala.

Signed-off-by: Eduard Vintilă <eduard.vintila47@gmail.com>

2022-09-24 13:47 UTC, mariasfiraiala approved these changes
Thank you @eduardvintila for this fix.
For the past month I've been using the changes in this PR whenever I wanted to run `SQLite`, `redis` or`nginx` on `AArch64` and they work perfectly.

All good on my part, @michpappas your turn.

Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

2022-09-29 08:40 UTC, razvand commented
@michpappas , could you please prioritize checking this PR?

2022-10-04 08:17 UTC, michpappas requested changes
Hi @eduardvintila, except from the comments below, please fix the issues reported by checkpatch.pl. Other than these it looks good 👍🏼

2022-10-04 08:17 UTC, michpappas commented on plat/drivers/virtio/virtio_pci.c
> +		__u32 buf_len_bytes = len * type_len;
Careful here: As `len` is also `__u32` you risk an overflow, so it would be better if you added a check against that. 
One way to do that is to check for reasonable results after multiplication, eg:
```
	unsigned long a = 1 << 31;
	unsigned long b = 10;
	unsigned long x = a * b;

	if (x / a != b)
		return -1;
```

A better way is to use `__builtin_umull_overflow()`, that is supported by both GCC and clang, and it compiles into checking the processor's carry flag. That avoids division, that is generally expensive.
```
	unsigned long a = 1 << 31;
	unsigned long b = 10;
	unsigned long x;
	
	if (__builtin_umulll_overflow(a, b, &x))
		return -1;
```

Notice that these bugs can potentially lead into security vulnerabilites, and that was the case with the infamous 2002 vulnerability in OpenSSH: http://undeadly.org/cgi?action=article&sid=20060330071917

2022-10-04 08:17 UTC, michpappas commented on plat/drivers/virtio/virtio_pci.c
> +		if (rc != (int)(buf_len_bytes))
The parenthesis around `buf_len_bytes` here are not needed. And while you're there, maybe wrap the check around `unlikely` to help with performance a bit.

2022-10-09 19:20 UTC, eduardvintila commented
Hey, @michpappas! Very good point on checking the multiplication result, sorry for missing that. I've added an overflow check using a compiler built-in function, just as you suggested. I chose `__builtin_umul_overflow()`, which works on `unsigned int` types. Since the ABIs for all our target architectures (`arm`, `x86_64` and `riscv64` in future) specify that `int` types are 32-bits wide, that should be well suited for our `__u32` multiplication.

I've also fixed the coding style issues that you have mentioned.

2022-10-10 09:28 UTC, michpappas approved these changes
@eduardvintila thanks a lot for the update, it all looks good now! 👍🏼 

Approved-by: Michalis Pappas <mpappas@fastmail.fm>

2022-10-15 19:05 UTC, gabrielmocanu commented
@razvand  Can we merge it?

2022-11-15 22:59 UTC, closed without merging