lib/posix-process: Add RLIMIT_DATA resource for prlimit64
unikraft/unikraft pull request #531
Opened 2022-08-23 05:25 UTC by Alex-deVis

This commit provides simple implementation for the `RLIMIT_DATA` resource for the `prlimit64` syscall.

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s): N/A
 - Application(s): N/A

2022-10-01 16:11 UTC, mogasergiu requested changes
Thanks for the patch! Looks good to me! Please also provide a short commit message describing what you did and why you did it. What is more, you should add a `Signed-off-by` tag at the end of your commit message with your name and email (e.g. `Signed-off-by: Alex Apostolescu <alexx.apostolescu@gmail.com>`) as specified in the guidelines[1].

[1] https://unikraft.org/docs/contributing/submitting-changes/

2022-10-15 19:07 UTC, gabrielmocanu commented
@Alex-deVis  Can you please update your PR based on @mogasergiu  input?
Thanks!

2022-10-15 19:12 UTC, Alex-deVis commented
Hi, I will update it in the following days.

2022-10-22 13:41 UTC, mogasergiu approved these changes
Reviewed-by: Sergiu Moga <sergiu.moga@protonmail.com>

2022-11-25 07:33 UTC, razvand approved these changes
Thanks, @Alex-deVis 

Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2022-11-25 07:38 UTC, closed without merging