Warning fix: uninitialized variable
unikraft/unikraft pull request #551
Opened 2022-09-10 16:53 UTC by mariamosn

Initialized the  variable. The previous use without initializtion was likely the cause of the build warnings.
Related to issue #545 

Signed-off-by: Maria Moșneag <mariamosneag@gmail.com>

2022-09-11 10:38 UTC, nderjung requested changes
Hi @mariamosn! Thanks or this contribution :)

Just a small change is necessary for it to get accepted.  Please can you rebase/reword your commit message so as to [follow our commit message style guide](https://unikraft.org/docs/contributing/coding-style/#commit-message-format):

```
lib/vfscore: Initialize `bytes` variable to `0` in syscall definition `pwritev`

This commit fixes an uninitialized variable which would otherwise throw build
warnings.

GitHub-Fixes: #545
Signed-off-by: Maria Moșneag <mariamosneag@gmail.com>
```

2022-09-11 13:18 UTC, razvand requested changes
Hi, @mariamosn , thanks for this.

See @nderjung 's comments on commit messages.

Your solution doesn't really fix the issue. The actual issue is in the function [`do_pwritev`](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/main.c#L560). The `bytes` argument is not initialized in case of error. So the solution is adding:

```
        *bytes = -1
```

at line [`578`](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/main.c#L560), right before:

```
       return -error;
```

2022-09-12 17:16 UTC, mariamosn commented
Thank you, @nderjung and @razvand, for all the help and explanations!

2022-09-13 11:07 UTC, razvand requested changes

2022-09-13 11:07 UTC, razvand commented on lib/vfscore/main.c
> +	ssize_t bytes = 0;
Remove this, it's no longer required.

2022-09-17 10:43 UTC, razvand approved these changes
Thanks, @mariamosn . This works.

@nderjung , please test it and see if it's OK on your side. Once you give the approval I would add the `Reviewed-by` message on my side.

2022-11-05 08:14 UTC, StefanJum approved these changes
Looks good @mariamosn, thank you.
@razvand please add your `Reviewed-by:` tag so this can be merged.

Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2022-11-14 13:23 UTC, razvand approved these changes
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>

2022-11-17 21:21 UTC, closed without merging