Build warning in lib/vfscore/stdio.c
unikraft/unikraft pull request #552
Opened 2022-09-11 14:31 UTC by huanhuanou

Signed-off-by:Jinbo hu 2451203274@qq.com

2022-09-11 14:44 UTC, huanhuanou commented
@razvand I don't know how to change the path. I republished one.

2022-09-12 15:35 UTC, skuenzer requested changes

2022-09-12 15:35 UTC, skuenzer commented on lib/vfscore/stdio.c
> +	if (dup2(0, 1) != 1)  /* uk_syscall_r_dup2 */
Please don't use `dup2`, because this will fail when `LIBSYSCALL_SHIM_NOWRAPPER` is set. `dup2` may not exist anymore. The safe way is to use `uk_syscall_r_dup2()` and whats might be missing is just the prototytpe defintion. You probably only need to include `<uk/syscall.h>` in this file.

2022-09-12 16:07 UTC, huanhuanou commented on lib/vfscore/stdio.c
> +	if (dup2(0, 1) != 1)  /* uk_syscall_r_dup2 */
But I tried to include <uk/syscall.h> before，and then there was still warning.I'll try again

2022-09-13 10:51 UTC, razvand commented on lib/vfscore/stdio.c
> +	if (dup2(0, 1) != 1)  /* uk_syscall_r_dup2 */
@skuenzer , the `uk_syscall_r_dup2()` symbol is not actually part of any header. It's generally used for system calls. For library calls, this is only used inside the same source code file (i.e. [`lib/vfscore/main.c`](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/main.c). There is no header for `uk_syscall_r_...` or `uk_syscall_e_...` symbols.

2022-10-15 19:14 UTC, gabrielmocanu commented
@huanhuanou  Any updates on this PR ?

2022-10-15 19:24 UTC, huanhuanou commented
> @huanhuanou Any updates on this PR ?

no

2022-11-25 08:34 UTC, razvand commented
@huanhuanou , @skuenzer , @gabrielmocanu , the issue is no longer present, so I'll close this issue:

```
make: Leaving directory '/home/razvan/projects/unikraft/scripts/workdir/unikraft'
GEN     libsyscall_shim: provided_syscalls.h.in.new                                                                                                                                    
CONFIGURE libmusl: version.h                                                                                                                                                           
HOSTLN  libmusl: complex: src/intenal/libm.h                                                                                                                                           
GEN     libsyscall_shim: syscall_map.h.new                                                                                                                                             
GEN     libsyscall_shim: syscall_stubs.h.new                                                                                                                                           
GEN     libsyscall_shim: syscall_nrs.h.new                                                                                                                                             
GEN     libsyscall_shim: syscall_nrs2.h.new                                                                                                                                            
CC      libvfscore: stdio.o                                                                                                                                                            
LD      libvfscore.ld.o                                                                                                                                                                
OBJCOPY libvfscore.o 
```

2022-11-27 11:39 UTC, razvand commented
@huanhuanou , @skuenzer , @gabrielmocanu , I was wrong. The issue still appears but it's very weird.

I'm able to reproduce it by using LWIP as a dependency for an `app-helloworld`. The first time I build it (`kraft build` or `make`), the issue appears:

```
CC      libvfscore: stdio.o 
    64%
/home/razvan/projects/unikraft/scripts/workdir/unikraft/lib/vfscore/stdio.c: In function ‘init_stdio’:
/home/razvan/projects/unikraft/scripts/workdir/unikraft/lib/vfscore/stdio.c:226:7: warning: implicit declaration of function ‘uk_syscall_r_dup2’; did you mean ‘uk_syscall_r_stub’? [-W
implicit-function-declaration]   
  fd = uk_syscall_r_dup2(0, 1);    
       ^~~~~~~~~~~~~~~~~                                                 
       uk_syscall_r_stub
```

But if I remove the `stdio.o` file and rebuild, the issue is gone:

```
razvan@yggdrasil:~/.../workdir/apps/app-helloworld$ rm build/libnolibc/stdio.o 
razvan@yggdrasil:~/.../workdir/apps/app-helloworld$ kraft build 
make: Entering directory '/home/razvan/projects/unikraft/scripts/workdir/unikraft'
make[2]: Nothing to be done for 'fetch'.
make: Leaving directory '/home/razvan/projects/unikraft/scripts/workdir/unikraft'
make: Entering directory '/home/razvan/projects/unikraft/scripts/workdir/unikraft'
make: Leaving directory '/home/razvan/projects/unikraft/scripts/workdir/unikraft'
CC      libnolibc: stdio.o                                                                                                                                                             
LD      libnolibc.ld.o                                                                                                                                                                 
OBJCOPY libnolibc.o                                                                                                                                                                    
LD      helloworld_kvm-x86_64.ld.o                                                                                                                                                     
OBJCOPY helloworld_kvm-x86_64.o                                                                                                                                                        
LD      helloworld_kvm-x86_64.dbg                                                                                                                                                      
SCSTRIP helloworld_kvm-x86_64                                                                                                                                                          
GZ      helloworld_kvm-x86_64.gz                                                                                                                                                       
                                                                                                                                                                                       
Successfully built unikernels:

  => build/helloworld_kvm-x86_64
  => build/helloworld_kvm-x86_64.dbg (with symbols)

To instantiate, use: kraft run
```

I tried to remove all sorts of build files to retrigger the issue. The only way I was able to retrigger it was by running `kraft clean` or removing the `build/kconfig/` directory and then rebuilding.

2022-11-28 11:25 UTC, skuenzer commented
Please confirm but I assume the warning appears if the `syscall_shim` library is not part of the build. Because the dup system is declared in a different file and the `syscall_shim` is not generating any headers if it is switched off. So for that case the prototype defintions needs to be provided within the file. You can guard it:
```c
#if !CONFIG_LIBSYSCALL_SHIM
long uk_syscall_r_dup2(long fd0, long fd1);
#endif /* !CONFIG_LIBSYSCALL_SHIM */
```
What do you think?

2022-11-28 12:23 UTC, razvand commented
@skuenzer , your suggestion took care of that. I will create a PR with it.

2022-11-28 12:34 UTC, razvand commented
@skuenzer , @gabrielmocanu , @huanhuanou , I'm closing this PR. I opened PR #667 for this.

2022-11-28 12:34 UTC, closed without merging