lib/vfscore: Add additional flags for compatibility
unikraft/unikraft pull request #623
Opened 2022-11-03 08:38 UTC by mschlumpp

### Prerequisite checklist

 - [ ] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [ ] Tested your changes against relevant architectures and platforms;
 - [ ] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s): N/A
 - Application(s): N/A

### Additional configuration

 - `CONFIG_LIBVFSCORE=y`

### Description of changes

This adds some additional flags which can be used for filesystem implementations.

2022-11-28 22:04 UTC, razvand reviewed
Hi, @mschlumpp . What was the use case for these flags? I didn't find `IO_ASYNC` nor `IO_DIRECT` in Linux. Where did you adapt the values for them?

2022-11-28 22:38 UTC, mschlumpp commented
They are from FreeBSD and are necessary for the ext filesystem driver. The values don’t matter as much because only the symbols are used. On 28. Nov 2022, at 23:04, Razvan Deaconescu ***@***.***> wrote:﻿
@razvand commented on this pull request.

Hi, @mschlumpp . What was the use case for these flags? I didn't find IO_ASYNC nor IO_DIRECT in Linux. Where did you adapt the values for them?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-01-17 14:57 UTC, StefanJum requested changes
Only one comment.

Other than that, does it make sense to add the flags if we are not using them at the moment, or should we add them when they will be used.

2023-01-17 14:57 UTC, StefanJum commented on lib/vfscore/include/vfscore/vnode.h
> +#define IO_DIRECT	0x0008
Please add some short comments on these macros, like the one on the `MNT_NOATIME`.

2023-01-29 15:10 UTC, razvand commented
@mschlumpp, the reason I'm concerned about the actual values is in case of a binary compatibility issue. If the symbols / values are only going to be used internally in Unikraft, then it's good.

I understand @StefanJum's comment on keeping this PR open until we have an actual use (i.e. a PR that makes use of these macros). I think this is something that makes sense long term. The addition of a feature, function, macro, should be supported by a use case.

2023-01-29 20:42 UTC, mschlumpp commented
The `IO_` constants are only relevant for "kernel"-level interactions. Therefore, ABI compatiblity from a userspace application is not a concern.

2023-01-31 19:07 UTC, razvand commented
@StefanJum, we can approve this PR. Please review / approve it, and then I'll do it.

2023-01-31 19:08 UTC, StefanJum approved these changes
All good, thanks.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-01-31 19:12 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-02-02 20:23 UTC, closed without merging