lib/vfscore: Replace `access` with unikraft syscall
unikraft/unikraft pull request #636
Opened 2022-11-04 15:15 UTC by mariasfiraiala

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): `AArch64`
 - Platform(s): `kvm`
 - Application(s): `SQLite`, `redis`

### Description of changes

Current `access` calls from `vfscore` generate infinite loops when used with `musl` due to these calls being interpreted as library function calls.

Consequently, we shouldn't be relying on calling wrappers when inside `unikraft` core, but on our own "syscalls". For the `access` function case, that would be `uk_syscall_r_access` and this PR changes it accordingly.

Closes: #635 

Signed-off-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

2022-11-07 19:39 UTC, eduardvintila approved these changes
Hi, @mariasfiraiala. This indeed does seem to fix the aforementioned issues. S'all good to me.

Reviewed-by: Eduard Vintilă eduard.vintila47@gmail.com

2022-11-18 11:33 UTC, razvand commented
@mariasfiraiala , please look into fixing the `checkpatch` warnings.

2022-11-18 11:38 UTC, razvand requested changes
Hi, @mariasfiraiala . See my small comment. This is similar to the comment made by @StefanJum in his comments for PR #638

2022-11-18 11:38 UTC, razvand commented on lib/vfscore/main.c
> +	}
```suggestion
	if (error)
		return -error;
```

For consistency, `errno` should be used. And the return value should be a negative number.

2022-11-18 12:44 UTC, mariasfiraiala commented
Done @razvand . Please take a look again.

2022-11-18 12:56 UTC, razvand approved these changes
Thanks, @mariasfiraiala , it works

Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2022-11-18 13:58 UTC, closed without merging