Makfile: Add flags for cross-compiler `LLVM` target
unikraft/unikraft pull request #685
Opened 2022-12-09 21:18 UTC by mariasfiraiala

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): `AArch64`
 - Platform(s): `kvm`
 - Application(s): N/A

### Additional configuration

- `CONFIG_LLVM_TARGET_ARCH`

### Description of changes

If one wishes to compile an app using `clang`, for instance, they would have to choose the  `Custom cross-compiler LLVM target` option from the make build system, and manually set the flags.
This PR adds flags needed by the `Custom cross-compiler LLVM target` option. They are guarded by a condition which checks if these flags are really needed (by comparing `CONFIG_LLVM_TARGET_ARCH` with the empty string).

Signed-off-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

2022-12-26 08:10 UTC, michpappas requested changes
@mariasfiraiala I think we should be striving for better clang integration, if possible one that does not depend on a GCC toolchain, but rather on clang, ldd, and binutils. If that is not possible, we should still update the build system so that the user is not required to manually set so many env vars.

If you decide to pursue this, here are some useful resources:
* https://static.linaro.org/connect/bkk19/presentations/bkk19-210.pdf
* https://archive.fosdem.org/2018/schedule/event/crosscompile/attachments/slides/2107/export/events/attachments/crosscompile/slides/2107/How_to_cross_compile_with_LLVM_based_tools.pdf

2023-05-19 17:08 UTC, StefanJum commented
@mariasfiraiala @michpappas @razvand, should we go ahead with some variation of this PR until we get a better `clang` integration? It would be nice to have `clang` support on `arm64` without needing to pull PRs, and I think better `clang` integration will take quite some time.

I think we can do something very transparent to the user, like check if the user selected any `LLVM target` in the menuconfig, if not (and the used CC is clang) just add a default one (I've been testing everything with `--targtet=aarch64-linux-none-gnu` so far).

The only env variable that should be set is the `CROSS_COMPILE` that should point to the toolchain path, [everything else is set based on that](https://github.com/unikraft/unikraft/blob/staging/Makefile#L581-L599), but adding the `--target` flag works for me without even setting the `CROSS_COMPILE` variable.

2023-06-19 14:34 UTC, StefanJum commented
@mariasfiraiala following the discussion [here](https://discord.com/channels/762976922531528725/1082548752612593694/1113024585911259236) we should update this PR to just add the `aarch64-none-elf` target to `CFLAGS`, `CXXFLAGS`, `ASFLAGS` etc if `arch/arm64` is selected in the configuration menu and `CC==clang`.

We should eventually just remove the whole `CONFIG_LLVM_TARGET_ARCH`, but it looks like Rust support might need it.

2023-07-06 15:01 UTC, StefanJum requested changes
Thank you @mariasfiraiala. Besides the comment, I would replace `flags` with something more specific (like `target flags`?) in the commit message / description.

2023-07-06 15:01 UTC, StefanJum commented on Makefile
> +CXXFLAGS        += --target=aarch64-none-elf
```suggestion
ARCHFLAGS             += --target=aarch64-none-elf
ISR_ARCHFLAGS         += --target=aarch64-none-elf
```
Would it make more sense to add those to `ARCHFLAGS`?

2023-07-30 08:31 UTC, mariasfiraiala commented
Done @StefanJum, please take another look!

2023-07-30 08:39 UTC, mariasfiraiala commented
Just to have it here for documentation purposes, there is a small issue with  the TLS phdrs, that rarely shows up, a better description of it being on the [discord channel](https://discord.com/channels/762976922531528725/1082548752612593694/1131276221183967293).

2023-07-30 08:41 UTC, StefanJum approved these changes
Thank you @mariasfiraiala, all good.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-07-31 02:00 UTC, michpappas commented
Thanks @mariasfiraiala 🚀 

Approved-by: Michalis Pappas <michalis@unikraft.io>

2023-08-02 12:33 UTC, closed without merging