Use the ukarch_random API to generate PAuth keys and enable on pointer authentication on KVM
unikraft/unikraft pull request #686
Opened 2022-12-11 12:37 UTC by michpappas

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [arm64]
 - Platform(s): [`kvm`]
 - Application(s): [N/A]

### Additional configuration

### Description of changes

With the addition of the ukarch_random() API it is now possible to generate PAuth keys without delegating the implementation of key generation to the platform.

Remove ukplat_pauth_gen_key() from the platform API and generate PAuth keys using the ukarch_random() API.

Enable PAuth on KVM.

2023-01-26 21:34 UTC, mariasfiraiala requested changes
Hi @michpappas! I've tested this PR against `qemu 4.2` and `qemu 7` with CPUs that support and do not support the Pointer Authentication feature and I have a few observations:

* when the feature is not available for that CPU, it hangs due to asm instructions not being able to get decoded. This happens due to the  check being done way to far in `_libkvmplat_start()`

* same goes for when the feature is supported, you'll find a better explanation below

2023-01-26 21:34 UTC, mariasfiraiala commented on plat/kvm/arm/setup.c
> +#ifdef CONFIG_ARM64_FEAT_PAUTH
The enabling of the Pointer Authentication happens **after** a few other functions are called (`pl011_console_init()`, for instance) which in asm have instructions such as `paciasp`, `autiasp` (due to the `mbranch-protection` flag). These cannot be executed properly due to the feature not being initialized yet.

Is this how it's supposed to be? If not, suggest moving the initialization block for Pointer Authentication at the beginning of `_libkvmplat_start()`.

2023-01-28 08:28 UTC, michpappas commented
Hi @mariasfiraiala

> when the feature is not available for that CPU, it hangs due to asm instructions not being able to get decoded. This happens due to the check being done way to far in _libkvmplat_start()

Yes, this is the same behavior as with any other unsupported instruction, so it's normal. What do you mean it happens due to the check being done way too far in `_libkvmplat_start()`?

> The enabling of the Pointer Authentication happens after a few other functions are called (pl011_console_init(), for instance) which in asm have instructions such as paciasp, autiasp (due to the mbranch-protection flag). These cannot be executed properly due to the feature not being initialized yet.
>
> Is this how it's supposed to be? If not, suggest moving the initialization block for Pointer Authentication at the beginning of _libkvmplat_start().

This shouldn't be happening, PAuth is applied only after the feature is enabled in the processor via `SCTLR_EL1.EnIA`. In fact, I cannot reproduce that behavior either. Could you please provide more info on your setup?

2023-01-28 20:00 UTC, mariasfiraiala commented
> Could you please provide more info on your setup?

@michpappas I was using a compiler with a version lower than 10 I was actually getting the issue documented here #728 . I am now testing this with `gcc-arm-11.2-2022.02-x86_64-aarch64-none-linux-gnu` and `qemu 4.2` (using the `max` CPU for the virt platform). `helloworld` looks good for now. I'll test `sqlite` too and that should be it, hopefully.

2023-01-28 20:58 UTC, mariasfiraiala approved these changes
I've tested `SQLite` too (this time with `qemu 6`). Everything looks ok. Thank you @michpappas for your support!

Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

2023-01-28 21:32 UTC, razvanvirtan approved these changes
All good on my side too, thank you!

Reviewed-by: Razvan Virtan <virtanrazvan@gmail.com>

2023-02-03 22:40 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-02-03 22:49 UTC, closed without merging