lib/vfscore: Add README.md file
unikraft/unikraft pull request #780
Opened 2023-03-06 14:31 UTC by RaduNichita

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): [e.g. `x86_64` or N/A]
 - Platform(s): [e.g. `kvm`, `xen` or N/A]
 - Application(s): [e.g. `app-python3` or N/A]

### Additional configuration

### Description of changes

2023-03-08 10:19 UTC, StefanJum requested changes
Looks good @RaduNichita, see my comments.

2023-03-08 10:19 UTC, StefanJum commented on lib/vfscore/README.md
> +The `vfscore` is an internal library of Unikraft that provides a generic interface of system calls related to filesystem management. I
```suggestion
The `vfscore` is an internal library of Unikraft that provides a generic interface of system calls related to filesystem management.
```

2023-03-08 10:19 UTC, StefanJum commented on lib/vfscore/README.md
> +
```suggestion
There are multiple types of filesystems available in Unikraft (e.g: `ramfs`,` 9pfs`).

```

2023-03-08 10:19 UTC, StefanJum commented on lib/vfscore/README.md
> +
```suggestion
More about this structure [here](https://tldp.org/LDP/lkmpg/2.4/html/c577.htm).

```

2023-03-08 10:19 UTC, StefanJum commented on lib/vfscore/README.md
> +Notice that he system call will eventually call the registered operation.
```suggestion
Notice that the system call will eventually call the registered operation. 
```

2023-03-14 13:05 UTC, StefanJum requested changes
Thanks @RaduNichita, few more comments.

2023-03-14 13:05 UTC, StefanJum commented on lib/vfscore/README.md
> +The `vfscore` library provides 2 structures to define operations on a filesystem (defined in `lib/vfscore/include/vfscore/mount.h`):
```suggestion
The `vfscore` library provides 2 structures to define operations on a filesystem (defined in [`lib/vfscore/include/vfscore/mount.h`](link to file)):
```
I would add a link here.

2023-03-14 13:05 UTC, StefanJum commented on lib/vfscore/README.md
> +For using the vfscore, we need to have a filesystem that actually implements the file operations. You can follow the same approach as in [lib/ramfs/README.md](../ramfs/README md#configuring-applicati
```suggestion
For using the vfscore, we need to have a filesystem that actually implements the file operations.
You can follow the same approach as in [lib/ramfs/README.md](full link)
```
Please add a full link here, this may break when rendering the file on the website.

2023-03-14 13:05 UTC, StefanJum commented on lib/vfscore/README.md
> +```
I would add an example of how the `VOP_OPEN` is defined in an actual filesystem (e.g. ramfs).
Just explain one of the declarations [here](https://github.com/unikraft/unikraft/blob/staging/lib/ramfs/ramfs_vnops.c#L638-L676), on how the `ramfs_vnops` structure is defined. Same for [`vfsops`](https://github.com/unikraft/unikraft/blob/staging/lib/ramfs/ramfs_vfsops.c#L49-L63).
I would also add a few lines on how to register a new filesystem (see [here](https://github.com/unikraft/unikraft/blob/staging/lib/ramfs/ramfs_vfsops.c#L65-L71) for `ramfs`).

2023-03-18 09:59 UTC, RaduNichita commented
I have applied the feedback, @StefanJum. :100:  Please take another tour, when you have time.

2023-03-18 14:46 UTC, StefanJum requested changes
Thanks @RaduNichita, new round.

2023-03-18 14:46 UTC, StefanJum commented on lib/vfscore/README.md
> +You can inspect the [`extra.ld`](/lib/vfscore/extra.ld) file to see it.
Add a full link here, to avoid messing up the file renderer when we upload this to the website.

2023-03-18 14:46 UTC, StefanJum commented on lib/vfscore/README.md
> +To understand how these operations end up being used let's examine the open system call:
```suggestion
To understand how these operations end up being used let's examine the [open system call](link to the vfscore file where open is defined):
```

2023-03-18 14:46 UTC, StefanJum commented on lib/vfscore/README.md
> +`VOP_OPEN()` is a macro that is defined as follows:
```suggestion
[`VOP_OPEN()`](link to the definition of `VOP_OPEN`) is a macro that is defined as follows:
```

2023-03-18 14:46 UTC, StefanJum commented on lib/vfscore/README.md
> +
```suggestion
## Register a new filesystem

```

Don't add more than one consecutive blanc line.

2023-03-18 14:46 UTC, StefanJum commented on lib/vfscore/README.md
> +
```suggestion
For this, the library exposes a specific structure named `vfscore_fs_type`:

```

2023-03-18 14:46 UTC, StefanJum commented on lib/vfscore/README.md
> +
```suggestion
You can inspect the [`extra.ld`](/lib/vfscore/extra.ld) file to see it.

```

2023-03-18 14:46 UTC, StefanJum commented on lib/vfscore/README.md
> +
```suggestion
Where the `fssw` argument is a `vfscore_fs_type` structure.

```

2023-03-18 14:46 UTC, StefanJum commented on lib/vfscore/README.md
> +};
I wouldn't add the entire structure here, do some `[...]` in the middle.
Also add a link to where these are all defined, so the user can take a look at it more in depth.

2023-03-18 14:46 UTC, StefanJum commented on lib/vfscore/README.md
> +The `vfscore` library provides 2 structures to define operations on a filesystem (defined in [lib/vfscore/include/vfscore/mount.h](/lib/vfscore/include/vfscore/mount.h)):
```suggestion
The `vfscore` library provides 2 structures to define operations on a filesystem (defined in [lib/vfscore/include/vfscore/mount.h](/lib/vfscore/include/vfscore/mount.h:...)):
```
Add the line number.

2023-03-18 14:46 UTC, StefanJum commented on lib/vfscore/README.md
> +The first structure mainly defines the operation of mounting the filesystem, while the second defines the operations that can be executed on files (regular files, directories, etc).
I think the first structure represents the operations you can do on the filesystem, not just the mount-related ones (e.g. `sync`, `fsstat` etc.).

2023-03-18 14:46 UTC, StefanJum commented on lib/vfscore/README.md
> +To map the desired function for your filesystem with the vfscore application, you need to have declare a `struct vnops` and populate the members, as shown below:
```suggestion
To map the desired function for your filesystem with the vfscore application, you need to have declare a `struct vnops` structure and populate it's members, as shown below:
```

2023-04-09 17:43 UTC, StefanJum requested changes
Thanks @RaduNichita, looking better and better.
See the few comments.

2023-04-09 17:43 UTC, StefanJum commented on lib/vfscore/README.md
> +The `vfscore` is an internal library of Unikraft that provides a generic interface of system calls related to filesystem management.
```suggestion
`vfscore` is an internal library of Unikraft that provides a generic interface of system calls related to filesystem management.
```

2023-04-09 17:43 UTC, StefanJum commented on lib/vfscore/README.md
> +To understand how these operations end up being used let's examine the [`open system call`](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/syscalls.c#L111)
```suggestion
To understand how these operations end up being used let's examine the [`open` system call](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/syscalls.c#L111)
```

2023-04-09 17:43 UTC, StefanJum commented on lib/vfscore/README.md
> +There are multiple types of filesystems available in Unikraft (e.g: `ramfs`,` 9pfs`).
```suggestion
There are multiple types of filesystems available in Unikraft (e.g: `ramfs`, `9pfs`).
```

2023-04-09 17:43 UTC, StefanJum commented on lib/vfscore/README.md
> +The `vfscore` library provides 2 structures to define operations on a filesystem (defined in [lib/vfscore/include/vfscore/mount.h](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/includ
```suggestion
The `vfscore` library provides 2 structures to define operations on a filesystem (defined in [`lib/vfscore/include/vfscore/mount.h`](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/include/vfscore/mount.h#L151)):
```

2023-04-09 17:43 UTC, StefanJum commented on lib/vfscore/README.md
> +The first structure mainly defines the operation of mounting the filesystem, while the second defines the operations that can be executed on files (regular files, directories, etc).
```suggestion
The first structure mainly defines the operation of mounting the filesystem, while the second defines the operations that can be executed on files (regular files, directories, etc.).
```

2023-04-09 17:43 UTC, StefanJum commented on lib/vfscore/README.md
> +To map the desired function for your filesystem with the vfscore application, you need to have declare a `struct vnops` [structure](https://github.com/unikraft/unikraft/blob/staging/lib/ramfs/ramfs_v
```suggestion
To map the desired function for your filesystem with the `vfscore` application, you need to have declared a `struct vnops` [structure](https://github.com/unikraft/unikraft/blob/staging/lib/ramfs/ramfs_vnops.c#L651) and populate its members, as shown below:
```

2023-04-09 17:43 UTC, StefanJum commented on lib/vfscore/README.md
> +};
Use spaces here instead of tabs. We don't use hard tabs in markdown.

2023-04-09 17:43 UTC, StefanJum commented on lib/vfscore/README.md
> +For using the vfscore, we need to have a filesystem that actually implements the file operations. You can follow the same approach as in [lib/ramfs/README.md](https://github.com/unikraft/unikraft/tre
```suggestion
For using the `vfscore`, we need to have a filesystem that actually implements the file operations. You can follow the same approach as in [`lib/ramfs/README.md`](https://github.com/unikraft/unikraft/tree/staging/lib/ramfs#configuring-applications-to-use-ramfs)
```

2023-04-10 10:14 UTC, StefanJum requested changes
One more round @RaduNichita, probably the last one

2023-04-10 10:14 UTC, StefanJum commented on lib/vfscore/README.md
> +To map the desired function for your filesystem with the `vfscore` application, you need to have declare a `struct vnops` [structure](https://github.com/unikraft/unikraft/blob/staging/lib/ramfs/ramfs
```suggestion
To map the desired function for your filesystem with the `vfscore` application, you need to have declared a `struct vnops` [structure](https://github.com/unikraft/unikraft/blob/staging/lib/ramfs/ramfs_vnops.c#L651) and populate its members, as shown below:
```

2023-04-10 10:14 UTC, StefanJum commented on lib/vfscore/README.md
> +For using the `vfscore`, we need to have a filesystem that actually implements the file operations. You can follow the same approach as in [lib/ramfs/README.md](https://github.com/unikraft/unikraft/t
```suggestion
For using `vfscore`, we need to have a filesystem that actually implements the file operations.
You can follow the same approach as in [`lib/ramfs/README.md`](https://github.com/unikraft/unikraft/tree/staging/lib/ramfs#configuring-applications-to-use-ramfs).
```
Use one sentence per line.

2023-04-10 10:14 UTC, StefanJum commented on lib/vfscore/README.md
> +        const char *vs_name;
```suggestion
        const char *vs_name;
```
Check for trailing whitespaces.

2023-04-10 10:14 UTC, StefanJum commented on lib/vfscore/README.md
> +As we mentioned before, these sections come with help macros, so this time is no exception either.
```suggestion
As we mentioned before, these sections come with helper macros, so this time is no exception either.
```
I think `helper macros` sounds better than `help macros`

2023-04-11 07:54 UTC, StefanJum requested changes
Just 2 minor comments @RaduNichita, will approve that.
@razvand please take a look over this when you have some time.

2023-04-11 07:54 UTC, StefanJum commented on lib/vfscore/README.md
> +For using the `vfscore`, we need to have a filesystem that actually implements the file operations.
```suggestion
To use `vfscore`, we need to have a filesystem that actually implements the file operations.
```

2023-04-11 07:54 UTC, StefanJum commented on lib/vfscore/README.md
> +You can follow the same approach as in [lib/ramfs/README.md](https://github.com/unikraft/unikraft/tree/staging/lib/ramfs#configuring-applications-to-use-ramfs)
```suggestion
You can follow the same approach as in [`lib/ramfs/README.md`](https://github.com/unikraft/unikraft/tree/staging/lib/ramfs#configuring-applications-to-use-ramfs)
```

2023-04-12 08:25 UTC, StefanJum approved these changes
All good besides the one comment @RaduNichita, thanks.
I'll leave the review tag after @razvand takes a look

2023-04-12 08:25 UTC, StefanJum commented on lib/vfscore/README.md
> +To use the `vfscore`, we need to have a filesystem that actually implements the file operations.
```suggestion
To use the `vfscore` library, we need to have a filesystem that actually implements the file operations.
```

2023-04-17 21:28 UTC, razvand requested changes
@RaduNichita, this looks good. See my comments. I will then approve the PR.

2023-04-17 21:28 UTC, razvand commented on lib/vfscore/README.md
> +To understand how these operations end up being used let's examine the [`open` system call](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/syscalls.c#L111)
```suggestion
To understand how these operations end up being used, let's examine the [`open` system call](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/syscalls.c#L111)
```

2023-04-17 21:28 UTC, razvand commented on lib/vfscore/README.md
> +`vfscore` is an internal library of Unikraft that provides a generic interface of system calls related to filesystem management.
```suggestion
`vfscore` (*Virtual File System Core*) is an internal library of Unikraft that provides a generic interface of system calls related to filesystem management.
```

2023-04-17 21:28 UTC, razvand commented on lib/vfscore/README.md
> +## Register a new filesystem
```suggestion
## Register a New Filesystem
```

2023-04-17 21:28 UTC, razvand commented on lib/vfscore/README.md
> +To map the desired function for your filesystem with the `vfscore` application, you need to have declared a `struct vnops` [structure](https://github.com/unikraft/unikraft/blob/staging/lib/ramfs/ramf
```suggestion
To map the desired function for your filesystem with the `vfscore` application, you need to declare [a `struct vnops` structure](https://github.com/unikraft/unikraft/blob/staging/lib/ramfs/ramfs_vnops.c#L651) and populate its members, as shown below:
```

2023-04-17 21:28 UTC, razvand commented on lib/vfscore/README.md
> +To map the desired function for your filesystem with the `vfscore` application, you need to have declared a `struct vnops` [structure](https://github.com/unikraft/unikraft/blob/staging/lib/ramfs/ramf
Clarify that `ramfs` is just an example. A filesytem will create its own structure and implement its own functions.

2023-04-17 21:28 UTC, razvand commented on lib/vfscore/README.md
> +## Configuring Applications to use `vfscore`
```suggestion
## Configuring Applications to Use `vfscore`
```

2023-04-17 21:28 UTC, razvand commented on lib/vfscore/README.md
> +
I would reference here the functions used by [`9pfs`](https://github.com/unikraft/unikraft/tree/staging/lib/9pfs), to provide another example (apart from [`ramfs`](https://github.com/unikraft/unikraft/tree/staging/lib/ramfs)) of implementing a filesystem.

2023-04-18 22:14 UTC, RaduNichita commented
@razvand I have applied the feedback. Please take another look when you have time.

2023-04-19 10:11 UTC, razvand requested changes
@RaduNichita, now that I'm reading this more thoroughly, I think it's too thin on telling what `vfscore` is about.

I suggest you do an overview of the files in the `lib/vfscore` directory. Do not go into `Makefile`, `Config.uk` and `exportsyms.uk` or other general Unikraft files. List specific vfscore files and detail what each of them is used for. Those that implement the POSIX filesystem operations will not need detailing; just say they are the typical POSIX functions for managing files.

2023-04-19 10:11 UTC, razvand commented on lib/vfscore/README.md
> +To map the desired function for your filesystem with the `vfscore` application, you need to declare a `struct vnops` structure
```suggestion
To map the desired function for your filesystem with the `vfscore` application, you need to declare a `struct vnops` structure.
```

2023-04-22 09:31 UTC, StefanJum requested changes
Thanks @RaduNichita, see the comments.

2023-04-22 09:31 UTC, StefanJum commented on lib/vfscore/README.md
> +```
Use `tree --charset=ascii` when you paste a `tree` output in a `.md` file, so all characters are ascii.

2023-04-22 09:31 UTC, StefanJum commented on lib/vfscore/README.md
> +## Organization
I would name this section something a bit more clear, `internal structure`, `file organization` , something along those lines.

2023-04-22 09:31 UTC, StefanJum commented on lib/vfscore/README.md
> +- `vnode.c` implements functions that are used to interact with the `fdtable`
```suggestion
- `vnode.c` implements functions that are used to interact with the `fdtable`.
```

2023-04-22 09:31 UTC, StefanJum commented on lib/vfscore/README.md
> +- `vnode.c` implements functions that are used to interact with the `fdtable`
I think `functions that interact with a vnode structure` is more suited. You can also point to the `vnode` strcuture in `include/vfscore/vnode.h`.

2023-04-22 09:31 UTC, StefanJum commented on lib/vfscore/README.md
> +- `fops.c` implements the subset of functions that are defined in `vfs.h`, that are related with file operations
```suggestion
- `fops.c` implements the subset of functions that are defined in `vfs.h`, that are related with file operations.
```

2023-04-22 09:31 UTC, StefanJum commented on lib/vfscore/README.md
> +- `lookup.c` implements the subset of functions that are defined in `vfs.h`, that are related with searching for a specific path in a filesystem
```suggestion
- `lookup.c` implements the subset of functions that are defined in `vfs.h`, that are related with searching for a specific path in a filesystem.
```

2023-04-22 09:31 UTC, StefanJum commented on lib/vfscore/README.md
> +- `stdio.c` exposes the functions that are used to interact with standard I / O. We can notice that this is done very similar to defining a new filesystem, as we'll discuss later in the README
```suggestion
- `stdio.c` exposes the functions that are used to interact with standard I/O.
  We can notice that this is done very similar to defining a new filesystem, as we'll discuss later.
```

2023-04-22 09:31 UTC, StefanJum commented on lib/vfscore/README.md
> +- `stdio.c` exposes the functions that are used to interact with standard I / O. We can notice that this is done very similar to defining a new filesystem, as we'll discuss later in the README
Use either the 2nd person pronouns (you) or 1st person plural (we) through the entire file. They are mixed now, pick either one of them and change the other one.

2023-04-22 09:31 UTC, StefanJum commented on lib/vfscore/README.md
> +- `rootfs.c` implements the function that is used to mount the root filesystem
```suggestion
- `rootfs.c` implements the function that is used to mount the root filesystem.
```

2023-04-22 09:31 UTC, StefanJum commented on lib/vfscore/README.md
> +- `task.c` implements some helper function that are used to convert between different path conventions
```suggestion
- `task.c` implements some helper function that are used to convert between different path conventions.
```

2023-04-22 09:31 UTC, StefanJum commented on lib/vfscore/README.md
> +- `syscalls.c` does the actual generic implementation of the `sys_*` function defined in the `vfs.h`
```suggestion
- [`syscalls.c`](....) does the actual generic implementation of the `sys_*` function defined in [`vfs.h`](....).
```
Add links to files that you refer, both files that you describe and files that you point to in the description (like `vfs.h` here).

2023-04-22 09:31 UTC, StefanJum commented on lib/vfscore/README.md
> +- `main.c` defines the specific Unikraft system calls for interacting with a filesystem, which are based on the files described above. You can read more about adding a new system call for Unikraft [h
```suggestion
- `main.c` defines the specific Unikraft system calls for interacting with a filesystem, which are based on the files described above.
   You can read more about adding a new system call for Unikraft on the [website](https://unikraft.org/community/hackathons/sessions/bincompat/)
```

2023-04-22 09:31 UTC, StefanJum commented on lib/vfscore/README.md
> +- `main.c` defines the specific Unikraft system calls for interacting with a filesystem, which are based on the files described above. You can read more about adding a new system call for Unikraft [h
I think [this link](https://unikraft.org/docs/develop/syscall-shim/) would be more suited here instead of the hackathon session.

2023-04-22 14:00 UTC, StefanJum requested changes
See the comments @RaduNichita.

2023-04-22 14:00 UTC, StefanJum commented on lib/vfscore/README.md
> +$ tree --charset=ascii -L 2 lib/vfscore/
```suggestion
$ tree -L 2 lib/vfscore/
```
Don't add the charset to the command, it's not relevant to the user.

2023-04-22 14:00 UTC, StefanJum commented on lib/vfscore/README.md
> +
```suggestion
```

2023-04-22 14:00 UTC, StefanJum commented on lib/vfscore/README.md
> +|-- extra.ld
I think it's a bit too much. Could be better to just add the files that you get into below.

2023-04-22 14:00 UTC, StefanJum commented on lib/vfscore/README.md
> +- [`fops.c`](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/fops.c) implements the subset of functions that are defined in [`vfs.h`](https://github.com/unikraft/unikraft/blob/staging/l
```suggestion
- [`fops.c`](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/fops.c) implements a subset of functions that are defined in [`vfs.h`](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/vfs.h#L802), that are related with file operations.
```

2023-04-22 14:00 UTC, StefanJum commented on lib/vfscore/README.md
> +- [`lookup.c`](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/lookup.c) implements the subset of functions that are defined in [`vfs.h`](https://github.com/unikraft/unikraft/blob/stagi
```suggestion
- [`lookup.c`](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/lookup.c) implements a subset of functions that are defined in [`vfs.h`](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/vfs.h#L685), that are related to searching for a specific path in a filesystem.
```

2023-04-22 14:00 UTC, StefanJum commented on lib/vfscore/README.md
> +- [`stdio.c`](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/stdio.c) exposes the functions that are used to interact with standard I / O. You can notice that this is done very similar
```suggestion
- [`stdio.c`](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/stdio.c) exposes the functions that are used to interact with standard I/O.
You can notice that this is done very similar to defining a new filesystem, as it will be detailed later in the README.
```
Use one sentence per line.

2023-04-22 14:00 UTC, StefanJum commented on lib/vfscore/README.md
> +- [`task.c`](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/task.c) implements some helper function that are used to convert between different path conventions.
```suggestion
- [`task.c`](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/task.c) implements some helper functions that are used to convert between different path conventions.
```

2023-04-22 14:00 UTC, StefanJum commented on lib/vfscore/README.md
> +
```suggestion
```

2023-04-22 14:00 UTC, StefanJum commented on lib/vfscore/README.md
> +- [`main.c`](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/main.c) defines the specific Unikraft system calls for interacting with a filesystem, which are based on the files described
```suggestion
- [`main.c`](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/main.c) defines the specific Unikraft system calls for interacting with a filesystem, which are based on the files described above.
You can read more about adding a new system call for Unikraft [here](https://unikraft.org/docs/develop/syscall-shim/).
```
Use one sentence per line.

2023-04-22 14:24 UTC, StefanJum requested changes
Just a couple more comments @RaduNichita.

2023-04-22 14:24 UTC, StefanJum commented on lib/vfscore/README.md
> +- [`vnode.c`](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/vnode.c) functions that interact with a [`vnode structure`](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/i
```suggestion
- [`vnode.c`](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/vnode.c) defines functions that interact with a [`vnode structure`](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/include/vfscore/vnode.h#L76).
```

2023-04-22 14:24 UTC, StefanJum commented on lib/vfscore/README.md
> +- [`stdio.c`](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/stdio.c) exposes the functions that are used to interact with standard I / O.
```suggestion
- [`stdio.c`](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/stdio.c) exposes the functions that are used to interact with standard IO. 
```

2023-04-22 14:24 UTC, StefanJum commented on lib/vfscore/README.md
> +You can notice that this is done very similar to defining a new filesystem, as it will be detailed later in the README.
```suggestion
You can notice that this is done very similar to defining a new filesystem, as it will be detailed later.
```

2023-04-22 14:41 UTC, StefanJum approved these changes
All good, thanks @RaduNichita.

2023-04-24 20:22 UTC, razvand reviewed
Hi, @RaduNichita.

This looks excellent. Please do the following:

- Add a detailed commit message.
- Add two spaces before each list to pacify Codacy.

2023-04-26 00:32 UTC, RaduNichita commented
@razvand done. I hope the commit message is explicit now. Please, take another tour when you have time.

2023-04-26 09:50 UTC, razvand requested changes
@RaduNichita , add two spaces **before** the dash / minus (`-`). NOT before the actual item. See the Codacy warning.

2023-04-28 00:00 UTC, razvand approved these changes
Thanks, @RaduNichita.

Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-04-28 00:01 UTC, closed without merging