lib/vfscore: Fix for #821
unikraft/unikraft pull request #824
Opened 2023-04-02 11:52 UTC by FailFish

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): `x86_64`
 - Platform(s): `kvm`
 - Application(s): `app-sqlite`

### Additional configuration

### Description of changes

The issue was caused by defining the feature macro `_BSD_SOURCE` in a header file `include/vfscore/mount.h`.
This commit removes the macro from the header, resolving the issue.

Github-Fixes: #821

2023-04-05 23:32 UTC, R-Rothrock commented
I'm not really sure the application (I don't know BSD even a little bit) but wouldn't you do something like:

```c
#ifndef _BSD_SOURCE
#define _BSD_SOURCE
#endif /* define _BSD_SOURCE */
```

instead of getting rid of the definition completely? Surely it has a purpose, right?

2023-04-14 14:04 UTC, StefanJum requested changes
Thank you @FailFish.
The `_BSD_SOURCE` feature define should be removes from this file, since it's a header file, but it should also be added to the source files that include the `vfscore/mount.h` header.

Just do a `grep` for `vfscore/mount.h` and add `#define _BSD_SOURCE` to the source files (if they don't already define `_GNU_SOURCE`).

2023-04-17 01:57 UTC, FailFish commented
> Thank you @FailFish. The `_BSD_SOURCE` feature define should be removes from this file, since it's a header file, but it should also be added to the source files that include the `vfscore/mount.h` header.
> 
> Just do a `grep` for `vfscore/mount.h` and add `#define _BSD_SOURCE` to the source files (if they don't already define `_GNU_SOURCE`).
> 
> Also please change the commit message to speficy what the commit does (e.g. `lib/vfscore: Remove _BSD_SOURCE from mount.h`).

I initially thought `_BSD_SOURCE` is always default in MUSL library, so I didn't move the macro to the sources. As you requested, I added the macro over 6 files that include `mount.h` but don't have GNU's.
Also, I found out `vfscore/syscalls.c` has both macros consecutively. Is this intended?

2023-04-17 06:18 UTC, StefanJum commented
> I initially thought `_BSD_SOURCE` is always default in MUSL library, so I didn't move the macro to the sources.
> As you requested, I added the macro over 6 files that include `mount.h` but don't have GNU's.

Great, thank you. Yes, it is default in Musl and it would very likely work fine without it, but I guess it could be useful if any other libc will be ported in the future.

>Also, I found out `vfscore/syscalls.c` has both macros consecutively. Is this intended?

It looks like they were  added by the [same commit](https://github.com/unikraft/unikraft/commit/b84b3da24a7ce540ba39470be5c7bd35a06f751a#diff-23708c9441729e9694fafb5ec6a8d37ba1f16704c31d9dcdbdbf92f196f6bcb1), but I can't see a reason for that.

2023-04-17 06:18 UTC, StefanJum approved these changes
All good now, thanks @FailFish.
I'll leave the review tag after @razvand also takes a look.

2023-04-25 20:20 UTC, razvand approved these changes
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-04-25 20:40 UTC, closed without merging