lib/nolibc, lib/isrlib: Pointer comparison
unikraft/unikraft pull request #825
Opened 2023-04-02 22:10 UTC by ranfun

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Description of changes

The memmove_isr function is used to copy a block of memory from a source address to a destination address. The function is used in interrupt service routines (ISRs) where it is important to copy the memory as quickly as possible.

In the previous implementation of memmove_isr, the function assumed that the source address is either greater than the destination address or less than it. If both the conditions were false, the function would not work as expected and may cause undefined behavior. This assumption could lead to issues where the memory blocks overlap.

The modified implementation of memmove_isr takes into account both overlapping and non-overlapping cases. The function typecasts the src and dst pointers to intptr_t to ensure that the values being compared are treated as pointers rather than integers. This can help prevent errors that might occur if the pointer values are interpreted as signed integers.  ( Issue [#447](https://github.com/unikraft/unikraft/issues/447) ).

The changes were implemented in both nolibc and isrlib libraries to ensure that the code is consistent across all libraries and to prevent any issues when switching between them.

Overall, the changes ensure that memmove_isr works correctly in all cases, including when the memory blocks overlap, and that the code is robust and less prone to errors.

2023-04-13 15:26 UTC, mariasfiraiala requested changes
Thanks @ranfun, the changes look ok. However, a few cosmetic aspects should be taken into consideration before merging this:

* Run `checkpatch.pl` on your commits using the instructions from [here](https://unikraft.org/docs/contributing/testing/#using-checkpatchpl) and fix your coding style errors. You'll find a couple of examples in my comments below.

* Squash your commits. The 4 of them can be combined into a single one, which suffices.

* Modify your commit message such as the verbs are all at Present Tense. Use the prefix `lib/{nolibc,isrlib}` before the description of the changes in your commit message. A good practice is to also have less than 50 characters for the commit message, so try to accomplish that.

2023-04-13 15:26 UTC, mariasfiraiala commented on lib/isrlib/string.c
> +    }
```suggestion
    if ((intptr_t)src == (intptr_t)dst)
        return dst;
```

unnecessary braces

2023-04-13 15:26 UTC, mariasfiraiala commented on lib/nolibc/string.c
> +    }
Suspect code indent and unnecessary braces

2023-04-21 20:03 UTC, eduardvintila reviewed
Hey, @ranfun. Thanks for the changes! Please follow @mariasfiraiala's suggestions so we can merge this PR : )

2023-04-21 21:07 UTC, ranfun commented
yes will do!


On Fri, Apr 21, 2023 at 1:03 PM Eduard Vintilă ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> Hey, @ranfun <https://github.com/ranfun>. Thanks for the changes! Please
> follow @mariasfiraiala <https://github.com/mariasfiraiala>'s suggestions
> so we can merge this PR : )
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/unikraft/unikraft/pull/825#pullrequestreview-1396338355>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARPASJYYZFXNMDLTT7XRJQ3XCLR27ANCNFSM6AAAAAAWQR3Y5U>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-04-25 19:32 UTC, razvand commented
@ranfun, can you take care of this, please?

2023-04-27 03:47 UTC, razvand commented
@ranfun, please see the checkpatch warnings

2023-04-27 03:57 UTC, ranfun commented
The latest patch passed the checkpatch warnings.

2023-05-01 11:16 UTC, mariasfiraiala commented
> The latest patch passed the checkpatch warnings

This is exactly why you should drop the other 5 commits.  We shouldn't have upstream unnecessary patches, such as the first 5 commits that **do not** pass the coding style checker.

So, @ranfun, drop them.

2023-05-08 07:59 UTC, mariasfiraiala commented
Closed via #880.

2023-05-08 07:59 UTC, closed without merging