xen/x86/mm.c: fix unchecked uk_palloc value
unikraft/unikraft pull request #839
Opened 2023-04-16 10:07 UTC by hlef

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [ ] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [x] Updated relevant documentation.
 
### Base target

 - Architecture(s): x86
 - Platform(s): xen
 - Application(s): N/A

### Description of changes

The return value of uk_palloc is not checked in _arch_init_p2m.

Allocation failure at that point should never happen, but it's not a reason not to check.

At this stage, in the even of a failure, we should probably abort the boot altogether.

This bug was detected using the following Coccinelle spatch:

    @call@
    expression ptr;
    position p;
    @@

    ptr@p = uk_palloc(...);

    @ok@
    expression ptr;
    position call.p;
    @@

    ptr@p = uk_palloc(...);
    ... when != ptr
    (
     (ptr == NULL || ...)
    |
     (ptr != NULL || ...)
    )

    @depends on !ok@
    expression ptr;
    position call.p;
    @@

    ptr@p = uk_palloc(...);
    + if (ptr == NULL) return;

Note: I did not test these changes because I do not have a Xen setup.

2023-04-17 09:50 UTC, skuenzer requested changes
Thanks for this update. Can you also fix the prefix of the commit title here?
For example: `plat/xen: Fix unchecked uk_palloc() value in x86/mm.c`

2023-04-19 10:00 UTC, StefanJum commented
@hlef Everything works fine, one small typo in the commit message:
`At this stage, in the even of a failure`: `even -> event`.

2023-05-04 16:49 UTC, hlef commented
@skuenzer @StefanJum thanks, I have updated the commit message.

2023-05-04 17:20 UTC, StefanJum approved these changes
All good now @hlef, thanks. I'll leave the tag after @skuenzer goes through it.

2023-05-08 13:42 UTC, skuenzer approved these changes
@hlef: Thanks for the update!

Approved-by: Simon Kuenzer  <simon@unikraft.io>

2023-05-10 09:05 UTC, closed without merging