ukalloc: remove unreachable NULL checks
unikraft/unikraft pull request #840
Opened 2023-04-16 10:10 UTC by hlef

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s): N/A
 - Application(s): N/A

### Description of changes

These `if (ptr && ...)` will always turn out true due to the preceding `if (!ptr)`.

This was found by the following Coccinelle spatch: https://coccinelle.gitlabpages.inria.fr/website/rules/notnull.cocci

2023-04-17 09:46 UTC, skuenzer requested changes
Nice commit, much more beautiful.
Can you fix the commit prefix: `lib/ukalloc: Remove unreachable NULL checks`?

2023-04-25 13:19 UTC, marcrittinghaus commented
@skuenzer,

I force pushed a fix with @hlef's consent.

2023-05-03 21:33 UTC, LucaSeri approved these changes
Hi @hlef! Thank you for this. I tested it and it looks good to me.

Reviewed-by: Luca Seritan <luca.seritan@gmail.com>

2023-05-04 08:26 UTC, DeliaPavel approved these changes
Looks good to me!

Reviewed-by: Delia Pavel <delia_maria.pavel@stud.acs.upb.ro>

2023-05-04 12:33 UTC, skuenzer approved these changes
Approved-by: Simon Kuenzer <simon@unikraft.io>

2023-05-04 12:48 UTC, closed without merging