use page alignment macros everywhere
unikraft/unikraft pull request #842
Opened 2023-04-16 13:18 UTC by hlef

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [ ] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): ARM64, x86
 - Platform(s): Xen, KVM
 - Application(s): N/A

### Description of changes

We have PAGE_ALIGN_DOWN, PAGE_ALIGN_UP, and PAGE_ALIGN macros, but don't use them consistently. At places we still have code that does custom ALIGN_DOWN, ALIGN_UP, and masks. Use appropriate macros everywhere.

This patch was generated by the following Coccinelle rule:

    @@
    expression E;
    @@

    - ALIGN_DOWN(E, __PAGE_SIZE)
    + PAGE_ALIGN_DOWN(E)

    @@
    expression E;
    type T;
    @@

    - ALIGN_DOWN(E, (T) __PAGE_SIZE)
    + PAGE_ALIGN_DOWN(E)

    @@
    expression E;
    @@

    - ALIGN_UP(E, __PAGE_SIZE)
    + PAGE_ALIGN_UP(E)

    @@
    expression E;
    type T;
    @@

    - ALIGN_UP(E, (T) __PAGE_SIZE)
    + PAGE_ALIGN_UP(E)

    @@
    expression E;
    @@

    - (E + PAGE_SIZE - 1) & PAGE_MASK
    + PAGE_ALIGN(E)

Note: this was only tested on x86 KVM, so the bit for ARM KVM and x86 Xen hasn't been tested. Please review carefully, I might have overlooked something.

2023-04-16 13:18 UTC, hlef commented
Hopefully I got everything alright on this one? This is really minor, but a good example of the stuff we could do with Coccinelle.

2023-04-16 14:41 UTC, razvand commented
@hlef, see the `checkpatch` reports.

2023-04-17 09:43 UTC, skuenzer requested changes
Hi @hlef,

this looks fine to me. Can you add the prefix to the commit title, like
`plat/*, lib/ukalloc: Use PAGE_ALIGN_UP(), PAGE_ALIGN_DOWN()`
If you want, you can also split the commits into two:
`plat/*: Use PAGE_ALIGN_UP(), PAGE_ALIGN_DOWN()`
`lib/ukalloc: Use PAGE_ALIGN_UP(), PAGE_ALIGN_DOWN()`

Thanks,

Simon

2023-05-08 07:20 UTC, hlef commented
Hi @skuenzer, thanks! I have updated the commit message.

2023-05-10 09:08 UTC, dragosp27 approved these changes
Looks good to me! Just make sure you've fixed the error reported by `checkpatch.pl`.

Signed-off-by: Dragos Petre <dragos.petre27@gmailcom>

2023-05-10 09:14 UTC, calex257 approved these changes

2023-05-10 09:54 UTC, calex257 commented
Looking good!

Reviewed-by: Alexandru Calciu alxcalciu@gmail.com

2023-05-10 09:56 UTC, calex257 approved these changes
Looking good!
Reviewed-by: Alexandru Calciu alxcalciu@gmail.com

2023-05-10 13:30 UTC, skuenzer approved these changes
Thanks for the update!

Approved-by: Simon Kuenzer <simon@unikraft.io>

2023-05-10 13:32 UTC, closed without merging