vfscore: fix potential free(NULL)
unikraft/unikraft pull request #843
Opened 2023-04-16 13:56 UTC by hlef

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [ ] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s): N?A
 - Application(s): N/A

### Description of changes

Very clearly this code is not correct. If `names` is always non-NULL then the `if` is useless. Otherwise `names` should be freed in the `if`. Since I'm not sure I am just playing it safe and freeing `names` in the `if`.

This bug was found by Coccinelle with the following spatch:

    @@
    expression E;
    @@

    if(E) {...}
    -free(E);

NOTE: I only minimally tested this. Please carefully double check it.

2023-04-16 14:01 UTC, hlef commented
Actually I just realized that `free(NULL)` is legal. We might want to add a comment here instead, since it will probably be confusing for most people.

2023-04-16 23:18 UTC, dinhngtu approved these changes
Like you said, `free(NULL)` is safe but this change should eliminate some confusion.

Reviewed-by: Tu Dinh Ngoc <dinhngoc.tu@irit.fr>

2023-04-17 09:05 UTC, marcrittinghaus approved these changes
I agree. `free(NULL)` is valid, but I also prefer to include a check. This explicitly documents that the pointer might be `NULL` and you were thinking about this when writing the code. It is also a reminder for people extending the code later.

Just removed the approved-by tag. Please rename the commit to `lib/vfscore: Fix potential free(NULL)`.

2023-04-17 09:25 UTC, nderjung requested changes
Hi, though it wasn't caught in checkpatch, the title of the commit should be:

```
lib/vfscore: fix potential free(NULL)
```

2023-04-17 09:26 UTC, marcrittinghaus commented
Ha, noticed it right before your message 😄

2023-04-19 07:51 UTC, Starnox approved these changes
I also agree. This straightforward way of handling this case is more explicit in intention.

Reviewed-by: Eduard-Florin Mihailescu [mihailescu.eduard@gmail.com](mailto:mihailescu.eduard@gmail.com)

2023-04-21 16:17 UTC, marcrittinghaus approved these changes
Approved-by: Marc Rittinghaus <marc.rittinghaus@unikraft.io>

2023-04-21 16:25 UTC, closed without merging