lib/vfscore: Handle `FIONBIO` command in `pipe_ioctl()`
unikraft/unikraft pull request #874
Opened 2023-05-01 16:15 UTC by eduardvintila

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [e.g. `x86_64` or N/A]
 - Platform(s): [e.g. `kvm`, `xen` or N/A]
 - Application(s): [e.g. `app-python3` or N/A]

### Additional configuration

### Description of changes

The current `ioctl` implementation for pipes does not handle the `FIONBIO` command, which leads to a negative error value being returned. This PR introduces a simple case which sets the FNONBLOCK flag when such a command is passed.

Without this PR, `app-redis` won't respond to any PING requests, for example, since Redis relies on nonblocking pipes to properly work.

2023-05-02 23:44 UTC, dinhngtu reviewed
Perhaps I missed something but why was `pipe_file->flags` set instead of `vfscore_file->f_flags` as checked by `pipe_read` (see below)? I'm not quite clear on the purpose of `pipe_file->flags` anyway, it seems to be unused until this PR.

https://github.com/unikraft/unikraft/blob/5cfaf423c04d0f00b16d5726849bca5fd8187606/lib/vfscore/pipe.c#L364

2023-05-03 16:17 UTC, Starnox commented
> Why was `pipe_file->flags` set instead of `vfscore_file->f_flags` as checked by `pipe_read` (see below)? I'm not quite clear on the purpose of `pipe_file->flags` either, it seems to be unused until this PR.
> 
> https://github.com/unikraft/unikraft/blob/5cfaf423c04d0f00b16d5726849bca5fd8187606/lib/vfscore/pipe.c#L364

I have the same question, as I just started looking at the library. If you could provide a little bit more details, that would be great, thanks!

2023-05-04 13:01 UTC, eduardvintila commented
> I'm not quite clear on the purpose of `pipe_file->flags` either, it seems to be unused until this PR.

Hey, @dinhngtu @Starnox! Indeed, `pipe_file->flags` isn't used anywhere, just yet. I'm not sure of its purpose, either.  I considered setting it because maybe in the future it will be used when extending/updating/refactoring our current internal `pipes` implementation.

> Why was `pipe_file->flags` set instead of `vfscore_file->f_flags` as checked by `pipe_read` (see below)? 

All `ioctl` calls are first routed through the generic [`sys_ioctl()`](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/syscalls.c#L382) function, which already sets the `vfscore_file`'s `f_flags` member with the [desired flags](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/syscalls.c#L405), before calling the actual implementation for the given file (which, for pipes, is `pipe_ioctl()`). 

Therefore, in our case, we don't need to explicitly set `vfscore_file->f_flags`, since the aforementioned function already does that before `pipe_ioctl()` is called.

2023-05-04 13:39 UTC, dinhngtu requested changes
Per [this comment](https://github.com/unikraft/unikraft/blob/e1604e97a54c1195368463c0c1f2ccb726dac6d1/lib/vfscore/main.c#L2057-L2065), the plan going forward is to consume `f_flags` directly rather than syncing it with our own flags whenever possible. We already do this in our pipes implementation so IMO we should leave `pipe_file->flags` alone and rewrite this as:

```c
case FIONBIO:
    /* sys_ioctl() already sets f_flags, no need to do anything */
    return 0;
```

2023-05-05 07:22 UTC, eduardvintila commented
Good point, @dinhngtu! I've updated the PR to reflect this 👍🏻

2023-05-05 11:45 UTC, dinhngtu approved these changes
That's all from me, thanks.

Reviewed-by: Tu Dinh Ngoc <dinhngoc.tu@irit.fr>

2023-05-05 18:49 UTC, Starnox approved these changes
Looks good to me! Thanks!

Reviewed-by: Eduard-Florin Mihailescu <mihailescu.eduard@gmail.com>

EDIT by @marcrittinghaus: Fixed email format in tag.

2023-05-07 12:15 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-05-10 05:56 UTC, closed without merging