plat/linuxu: Fix memory region setup and issue #766
unikraft/unikraft pull request #878
Opened 2023-05-08 06:06 UTC by mogasergiu

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): [e.g. `x86_64` or N/A]
 - Platform(s): [e.g. `kvm`, `xen` or N/A]
 - Application(s): [e.g. `app-python3` or N/A]

### Additional configuration

### Description of changes

Re-submission of #797. Therefore, #797 is superseeded by this.

2023-05-08 11:35 UTC, RaduNichita requested changes
Hi, @mogasergiu!

This looks fine, I tested it with most of the complex apps and seems to be working OK. Thanks for continuing the previous work! :100:  

 Please also add the `Co-authored-by`: <> tag in the commit description, you can see the discussion from #880 and [here](https://github.com/unikraft/docs/pull/242)

2023-05-08 18:42 UTC, RaduNichita reviewed
All good, now! Thanks, @mogasergiu :t-rex: 

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

2023-05-08 20:29 UTC, RaduNichita approved these changes

2023-05-10 11:13 UTC, razvand approved these changes
Thanks, @Daparrag, @mogasergiu.

Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-05-10 11:23 UTC, closed without merging