lib/{nolibc,isrlib}: Modify pointer comparison
unikraft/unikraft pull request #880
Opened 2023-05-08 07:57 UTC by mariasfiraiala

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s): N/A
 - Application(s): N/A

### Additional configuration

### Description of changes

This PR typecasts `src` and `dst` strings from `string.h:memmove()` to ensure that their values are treated as pointers.

It also modifies the function implementation to handle overlapping.

2023-05-08 08:08 UTC, RaduNichita reviewed
I have an initial question: why is the cast required and we don't use the s and d variables for checkings?

```c
if (s == d) {
    return s;
}
[...]
```

2023-05-08 08:16 UTC, mariasfiraiala commented
> I have an initial question: why is the cast required and we don't use the s and d variables for checkings?
> 
> ```c
> if (s == d) {
>     return s;
> }
> [...]
> ```

See the discussion from #447. The cast when checking for equality was kept for consistency. I can remove it if you feel like it's necessary (the initial patch - #835 - was submitted with the cast for equality check as well).

2023-05-08 08:29 UTC, RaduNichita commented
Ok, fair enough.

We can merge this as it is now.

Thanks @mariasfiraiala for continuing work from @ranfun. :medal_sports: 

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

2023-05-08 08:29 UTC, RaduNichita approved these changes

2023-05-08 08:35 UTC, StefanJum requested changes
@mariasfiraiala please also add the `Co-authored-by: <>` tag in the commit description.

2023-05-08 09:01 UTC, StefanJum approved these changes
All good now, thanks @mariasfiraiala.
I'll add the tag after @razvand takes a look.

2023-05-10 11:43 UTC, razvand commented
This is OK. @StefanJum, please add your tag and then I'll approve the PR for merging.

2023-05-10 13:09 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-05-10 13:23 UTC, closed without merging