lib/vfscore: Avoid recursive locking in sys_rename
unikraft/unikraft pull request #888
Opened 2023-05-12 15:27 UTC by marcrittinghaus

If the source and destination directories are the same in sys_rename, the vnode is locked two times. This is problematic with non-recursive mutexes. Also the double checks for access are not needed. This commit adds a check to make sure in this case, only a single lock is done and redundant checks are avoided.

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [N/A]
 - Platform(s): [N/A]
 - Application(s): [N/A]

### Additional configuration

### Description of changes

If the source and destination directories are the same in sys_rename,
the vnode is locked two times. This is problematic with non-recursive
mutexes. Also the double checks for access are not needed. This commit
adds a check to make sure in this case, only a single lock is done and
redundant checks are avoided.

The issue can be encountered in `app-python3` when applying the #476

2023-05-12 17:15 UTC, mariasfiraiala requested changes
Thank you @marcrittinghaus. I've tested this with `app-python3` and #476 and it worked alright. I left some (nit-picky) suggestions regarding the old comments. I'll add my tag, anyway, since, from my pov, the functionality is fine.

Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

2023-05-12 17:15 UTC, mariasfiraiala commented on lib/vfscore/syscalls.c
> +		/* The source and dest must be same file system */
```suggestion
		/* The source and destination must be in the same file system */
```

Not sure about the meaning of the previous comment, so I amended it a bit.

2023-05-12 17:15 UTC, mariasfiraiala commented on lib/vfscore/syscalls.c
> +		/* Source and destination directions should be writable) */
```suggestion
		/* Source and destination directions should be writable */
```

Not sure about "directions" here. Is it ok?

2023-05-12 17:44 UTC, StefanJum commented on lib/vfscore/syscalls.c
> +		/* Source and destination directions should be writable) */
I think it's `directories`.

2023-05-12 17:45 UTC, StefanJum approved these changes
Besides @mariasfiraiala 's comments everything looks fine to me, thanks.
I'll add the tag after @razvand takes a look.

2023-05-12 17:53 UTC, marcrittinghaus commented
> Thank you @marcrittinghaus. I've tested this with `app-python3` and #476 and it worked alright. I left some (nit-picky) suggestions regarding the old comments. I'll add my tag, anyway, since, from my pov, the functionality is fine.
> 
> Reviewed-by: Maria Sfiraiala [maria.sfiraiala@gmail.com](mailto:maria.sfiraiala@gmail.com)

Thanks @mariasfiraiala for pointing this out. That was a good opportunity to fix this. I did not see this 🐮💩. It is fixed 👍🏻 

Thanks @StefanJum for testing 🙏🏻

2023-05-13 03:15 UTC, razvand reviewed
It's OK.

@StefanJum, please add your tag and then I'll do the final approval step.

2023-05-13 07:29 UTC, StefanJum approved these changes
All good, go @razvand.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-05-13 12:27 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-05-13 12:43 UTC, closed without merging