lib/vfscore: Initialize lists for stdio_vnode
unikraft/unikraft pull request #889
Opened 2023-05-13 02:07 UTC by razvand

The VFS `struct vnode` structure has two `uk_list_head` members: `v_link` and `v_names`. These need to be initialized by a dedicated macro / function, such as `UK_LIST_HEAD_INIT`.

The `stdio_vnode` variable (of type `struct vnode`) is not initializing these members (they are filled with zeros). This will cause crashes when using them.

This commit fixes that by properly initializing the `v_link` and `v_names` members of the `stdio_vnode` variable.

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [e.g. N/A]
 - Platform(s): [e.g. N/A]
 - Application(s): [e.g. N/A]

### Additional configuration

### Description of changes

2023-05-13 08:08 UTC, StefanJum commented
@razvand what application should we reproduce the crash with, and what configuration?
I tried building and running nginx with `DEBUG_VFS` defined and a root filesystem attached and everything works fine.

2023-05-13 11:40 UTC, marcrittinghaus commented
Yes, would be good to know the situation in which you had issues 😃 But anyways, totally make sense.

2023-05-13 12:26 UTC, razvand commented
> @razvand what application should we reproduce the crash with, and what configuration? I tried building and running nginx with `DEBUG_VFS` defined and a root filesystem attached and everything works fine.

I encountered the problem when building and running [`app-python3`](https://github.com/unikraft/app-python3/). Sorry for not mentioning that. There's an `ioctl()` done on file descriptor 1 (for standard output) that causes the crash.

2023-05-13 15:17 UTC, StefanJum requested changes
@razvand please remove the backticks from the commit message component (`lib/vfscore`). They are not used in the commits history.

Besides that everything looks and works fine, I was not able to reproduce the issue with `python3` when using `DEBUG_VFS`, but nothing breaks and the commit definitely makes sense.

2023-05-13 18:17 UTC, razvand commented
> @razvand please remove the backticks from the commit message component (`lib/vfscore`). They are not used in the commits history.

Similar to PR #890, there are no backticks in the commit message. Or am I missing something?

> Besides that everything looks and works fine, I was not able to reproduce the issue with `python3` when using `DEBUG_VFS`, but nothing breaks and the commit definitely makes sense.

Sorry for not providing all details. To reproduce, do the following:

1. Use `app-python3`.
1. Add the synchronization PR #476.
1. Add the DPRINTF PR #890.
1. Enable extended debugging messages via `ukdebug`.
1. Enable `vfscore` debugging by adding, in `lib/vfscore/vfs.h`:

   ```text
   #define DEBUG_VFS
   ```

1. Update the `VFSDB_FLAGS` to value `0x0000001F` to enable full debugging of vfscore.
1. Build and run `app-python3`.

2023-05-13 19:15 UTC, mariasfiraiala approved these changes
Thank you, @razvand. I was able to replicate the crash now and the fix did its job. All good from my pov.

Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

2023-05-13 21:48 UTC, StefanJum approved these changes
I've also been able to reproduce the issue, everything works fine, thanks.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-05-15 06:34 UTC, marcrittinghaus approved these changes
Thanks @razvand!

Approved-by: Marc Rittinghaus <marc.rittinghaus@unikraft.io>

2023-05-15 06:36 UTC, closed without merging