build: Use -fcf-protection for GCC >= 8 or Clang >= 7
unikraft/unikraft pull request #944
Opened 2023-06-13 14:01 UTC by Krechals

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [e.g. `x86_64` or N/A]
 - Platform(s): [e.g. `kvm`, `xen` or N/A]
 - Application(s): [e.g. `app-python3` or N/A]

### Additional configuration

### Description of changes

The build fails on every app when gcc-8.0+ isn't used.

-fcf-protection was introduced in [gcc-8.0](https://gcc.gnu.org/gcc-8/changes.html) and in [clang-7.0](https://releases.llvm.org/7.0.0/tools/clang/docs/UsersManual.html).

The build still fails for clang-7.0, since `__asm__ goto` from `plat/kvm/x86/traps.c` was introduced in clang-9.0.

2023-06-18 15:48 UTC, StefanJum requested changes
This looks fine @Krechals, thank you, see the one comment.
About the build still failing with `clang 7`, should we add a global check for the `clang` version and fail if it's <= 9 (it could be only for `x86_64` or whatever setup fails to build)?
Something like [this](https://github.com/unikraft/unikraft/blob/staging/Makefile#L689-L691).

2023-06-18 15:48 UTC, StefanJum commented on support/build/Makefile.rules
> +$(shell if [ $(CC_VER_MAJOR) -gt $(1) ] || ([ $(CC_VER_MAJOR) -eq $(1) ] && [ $(CC_VER_MINOR) -ge $(2) ]) ; then echo -n y ; fi)
Isn't `[ $(CC_VER_MAJOR) -gt $(1) ] || ([ $(CC_VER_MAJOR) -eq $(1) ]` just an `[ $(CC_VER_MAJOR) -ge $(1) ]`?

2023-07-17 08:40 UTC, razvand commented
@Krechals, could you please take a look in this PR to have it ready for upstream? See @StefanJum's comments. @mariasfiraiala , please also take a look.

2023-07-21 17:24 UTC, mariasfiraiala requested changes
This works fine, thanks! @Krechals can you please address @StefanJum's comments in order to have this merged? I think they make sense.

2023-07-24 20:44 UTC, razvand commented
@Krechals , could you please rebase this PR on top of #983 ? Simply add the `-fcf-protection` specific checks commit and use the Clang-specific Makefile updates from #983 .

2023-07-24 21:52 UTC, Krechals commented on support/build/Makefile.rules
> +$(shell if [ $(CC_VER_MAJOR) -gt $(1) ] || ([ $(CC_VER_MAJOR) -eq $(1) ] && [ $(CC_VER_MINOR) -ge $(2) ]) ; then echo -n y ; fi)
Solved in https://github.com/unikraft/unikraft/pull/988

2023-07-27 20:57 UTC, razvand commented
@Krechals , could you rebase this, now that PR #983 is in?

2023-08-02 12:35 UTC, mariasfiraiala approved these changes
All good, thanks!

Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

2023-08-02 17:44 UTC, StefanJum requested changes
[This commit](https://github.com/unikraft/unikraft/commit/77221a5be2a715b10034d7ec0e729f9bef3ce3af) adds a minimum compiler version check, which is `9.0` for `clang`. So we only need the check for `gcc`.

Something like
```make
ifeq ($(call have_gcc),y)
COMPFLAGS-$(call gcc_version_ge,8,0)	+= -fcf-protection=none
else
COMPFLAGS-$(call gcc_version_ge,8,0)	+= -fcf-protection=none
endif
```
could be better?

2023-08-11 05:46 UTC, StefanJum commented
All good now @Krechals, just please remove the id `(101668)` from the commit authored-by and sign-off tags, we can merge after that.

2023-08-11 16:48 UTC, StefanJum approved these changes
All good, thanks.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-08-14 19:31 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-08-14 19:47 UTC, closed without merging