Fix exporting of ntohs and also include the long versions
unikraft/unikraft pull request #974
Opened 2023-07-08 09:25 UTC by haesbaert

### Description of changes

This is split into two commits:
1 - ntohs(3) had a typo in the exported symbol manifest, fix that.
2 - include ntohl(3) and htonl(3) as well

I'd wage that the long versions are more used/common than the short ones (think of an ip).

2023-07-25 18:50 UTC, Starnox approved these changes
Useful addition in my point of view

Reviewed-by: Eduard-Florin Mihailescu [mihailescu.eduard@gmail.com](mailto:mihailescu.eduard@gmail.com)

2023-07-30 14:51 UTC, RaduNichita requested changes
Change the message of the commit 1f4846cb42cde84d32593c1758f869b0f20fd66b to something more suggestive. Something like 

```console
Fixes a typo in the exportsymk.uk file for the ntohs symbol.
```

2023-07-30 14:55 UTC, RaduNichita requested changes
Change the commit message of 62c65465b7f3d832b5d8d63815e9c5c86eaec38b to be something more suggestive, such as

```console
Add htonl and ntohl functions to keep consistency, since their shorter equivalannt, the htons and noths functions, are already present.
```

2023-07-30 14:56 UTC, RaduNichita commented
Nice work, @haesbaert. Please see my comments regarding changes for the commit message.

2023-07-30 14:59 UTC, haesbaert commented
> Change the commit message of [62c6546](https://github.com/unikraft/unikraft/commit/62c65465b7f3d832b5d8d63815e9c5c86eaec38b) to be something more suggestive, such as
> 
> ```
> Add htonl and ntohl functions to keep consistency, since their shorter equivalannt, the htons and noths functions, are already present.
> ```

Our of curiosity, how is that more clear than:
```
lib/nolibc: Include and export htonl(3) and ntohl(3)
Since htons and ntohs are exported, export the long versions as well.
```

2023-07-31 20:29 UTC, RaduNichita commented
> > Change the commit message of [62c6546](https://github.com/unikraft/unikraft/commit/62c65465b7f3d832b5d8d63815e9c5c86eaec38b) to be something more suggestive, such as
> > ```
> > Add htonl and ntohl functions to keep consistency, since their shorter equivalannt, the htons and noths functions, are already present.
> > ```
> 
> Our of curiosity, how is that more clear than:
> 
> ```
> lib/nolibc: Include and export htonl(3) and ntohl(3)
> Since htons and ntohs are exported, export the long versions as well.
> ```

In my example I just wanted to express more visible why the change was indeed needed. (consistency). I have no strong preference, we can do your way.

2023-07-31 20:39 UTC, haesbaert commented
> > > Change the commit message of [62c6546](https://github.com/unikraft/unikraft/commit/62c65465b7f3d832b5d8d63815e9c5c86eaec38b) to be something more suggestive, such as
> > > ```
> > > Add htonl and ntohl functions to keep consistency, since their shorter equivalannt, the htons and noths functions, are already present.
> > > ```
> > 
> > 
> > Our of curiosity, how is that more clear than:
> > ```
> > lib/nolibc: Include and export htonl(3) and ntohl(3)
> > Since htons and ntohs are exported, export the long versions as well.
> > ```
> 
> In my example I just wanted to express more visible why the change was indeed needed. (consistency). I have no strong preference, we can do your way.

No worries, I've pushed something more in terms of what you described :), leme know if there is anything else.

2023-08-04 12:56 UTC, RaduNichita approved these changes
All good now, thanks @haesbaert 

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

2023-08-07 08:49 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-08-07 17:20 UTC, closed without merging