build: Add compiler version checking for clang
unikraft/unikraft pull request #983
Opened 2023-07-19 10:39 UTC by andreittr

### Description of changes

This change adds a `clang_version_ge` make function in line with what we have already for GCC.

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s): N/A
 - Application(s): N/A

### Additional configuration

N/A

2023-07-19 10:43 UTC, StefanJum commented
@andreittr I think this will be covered by #944

2023-07-24 19:33 UTC, razvand reviewed
Hi, @andreittr . This looks good. My only comment would be using capitalized `Clang` in your commit message.

2023-07-24 19:33 UTC, StefanJum commented
@razvand do we go for this and have #944 rebased on top?
The compiler version checking is also done by that one (see the comment [above](https://github.com/unikraft/unikraft/pull/983#issuecomment-1641852065)).

2023-07-24 19:37 UTC, razvand commented
@StefanJum , yes, it makes sense. Let's merge this and then have #944 rebased on top of this.

2023-07-25 07:50 UTC, StefanJum requested changes
@andreittr can you please also add a `error_if_clang_version_lt`, similar to what we have for `gcc`?

2023-07-27 07:52 UTC, razvand approved these changes
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>

2023-07-27 08:28 UTC, closed without merging