plat/drivers/virtio-ring: Downgrade saturated desciptors error
unikraft/unikraft pull request #984
Opened 2023-07-20 13:23 UTC by mkroening

Closes https://github.com/unikraft/unikraft/issues/853.

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [ ] Tested your changes against relevant architectures and platforms;
 - [ ] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s): N/A
 - Application(s): N/A

### Additional configuration

### Description of changes

Real-world applications may run into https://github.com/unikraft/unikraft/issues/853 many times per second.
I posted a simple reproduction into the issue.
According to @mschlumpp, this just means that Unikraft is filling up the virtio descriptors faster than the host consumes them.
This commit downgrades the error to a debug message to avoid scaring and to spend less time printing errors instead of doing work.

2023-07-20 13:38 UTC, mschlumpp approved these changes
Looks good to me :+1: 

Reviewed-by: Marco Schlumpp <marco@unikraft.io>

2023-07-20 17:25 UTC, mkroening commented
Fixed a typo in the commit message and the PR title.

2023-07-24 19:27 UTC, StefanJum requested changes
Thank you @mkroening, this looks fine. Please wrap the commit description to ~80 characters per line and use `GitHub-Closes: #853` (with `GitHub` added, without a dot at the end and placed after the sign-off tag).

2023-07-24 19:28 UTC, razvand requested changes
Thanks, @mkroening. Prefer using the `GitHub-Closes: #853` line. Also wrap comment lines to 75 characters, see the Checkpatch comments.

2023-07-24 20:48 UTC, mkroening commented
Done! I addressed all concerns regarding the commit message.

Mind you, I did not change the formatting of the change itself to preserve consistency, although there is a Checkpatch warning, @razvand. :)

2023-07-24 20:54 UTC, razvand commented
Thanks, @mkroening , this works. @StefanJum , please approve the PR and add your tag and then I'll finalize it.

2023-07-25 03:33 UTC, StefanJum requested changes
@mkroening please remove the first `Closes unikraft#853.` line.
It's all good besides that.

2023-07-25 11:20 UTC, mkroening commented
> @mkroening please remove the first `Closes unikraft#853.` line.

Done. I did so in the PR message, but forgot to remove it from the commit message. :)

2023-07-26 06:19 UTC, StefanJum approved these changes
All good now, thank you @mkroening 
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-07-26 12:39 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-08-02 10:07 UTC, closed without merging