plat/drivers: Provide a single API for UART drivers
unikraft/unikraft pull request #986
Opened 2023-07-23 14:55 UTC by zhxj9823

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): `x86_64` and `ARM64`
 - Platform(s): `kvm`
 - Application(s): N/A

### Additional configuration

### Description of changes

This PR migrates the console API into a new `libukconsole`. Each console provides an ops structure that implements the console API. The APIs include `coutk`, `coutd`, `cink`, and `init`.

A unified `uk_console_init` function takes `bootinfo` as a parameter to initialize the available console in both x86 and ARM platforms. The implementation of `uk_console_init` is platform-specific.

The header for ANSI characters is moved into a separate one in `include/uk`.

GitHub-Depends-On: #989

2023-07-24 19:10 UTC, razvand commented
Hi, @zhxj9823, this is marked as draft work. What needs to happen to make this a full PR?

2023-07-24 19:21 UTC, razvand requested changes
For the last two commits of this PR, please add a motivation for their existence. Such as why move the x86 console to a COM driver under `plat/drivers/uart/`.

Also, see some minor typos: `migrate` -> `migrates`, `an addition` -> `an additional`.

Also it would be ideal to add tests as part of the new `ukconsole` library, before upstreaming it, via the [`uktest` framework](https://unikraft.org/docs/develop/writing-tests/). @michpappas , what do you think? I'm OK with upstreaming it as part of the 0.14 release even if the tests aren't there.

2023-07-24 19:21 UTC, razvand commented on lib/ukconsole/console.c
> +		   >= 0) {
See comment from Codacy. Where is offset used?

2023-07-25 06:11 UTC, zhxj9823 commented
>> Also it would be ideal to add tests as part of the new `ukconsole` library, before upstreaming it, via the [`uktest` framework](https://unikraft.org/docs/develop/writing-tests/). @michpappas , what do you think? I'm OK with upstreaming it as part of the 0.14 release even if the tests aren't there.

> The input and output of this library are from and to the serial console. Can this be fitted into the `uktest` framework?

Does not fit. In general devices are a bit more complex to write tests for, we would need to introduce some abstractions so it would take time. I propose that we skip it for now. @razvand.

2023-07-25 08:15 UTC, michpappas reviewed
Hi @zhxj9823 thanks for this work 🚀 I did a first pass, it's likely that more iterations will follow. 

Besides the inline comments, according to Unikraft's guidelines changes to each library must come on a separate commit. This applies to any updates to `nolibc`, `ukdebug`, and `ukboot`. Moreover, please introduce the `ukconsole` library on a separate commit too. Similarly for changes on each driver.

2023-07-25 08:15 UTC, michpappas commented on lib/ukconsole/Config.uk
> +config KVM_KERNEL_SERIAL_CONSOLE
KVM configuration should be in `plat/kvm/Config.uk`. The location of driver-specific configuraiton is a bit tricky right now because we don't have not moved drivers out of `plat` yet, so there is a gap on where these should go. Maybe you can move it back to `plat/kvm` for now, and I'll try to come back with an update.

2023-07-25 08:15 UTC, michpappas commented on lib/ukconsole/console.c
> +#if CONFIG_ARCH_X86_64
If you need per-architecture variants you need to place architecture-specific variants under `lib/ukconsole/arch/<arch>/<name>.c` and update your `Makefile.uk` accordingly.

2023-07-25 08:15 UTC, michpappas commented on lib/ukconsole/console.c
> - * Copyright (c) 2021 OpenSynergy GmbH
Here it looks like derived work from an existing file, which is not the case. Please introduce a new file. The copyright for new files should be:
```
/* SPDX-License-Identifier: BSD-3-Clause */
/* Copyright (c) 2023, Unikraft GmbH and The Unikraft Authors.
 * Licensed under the BSD-3-Clause License (the "License").
 * You may not use this file except in compliance with the License.
 */
```

2023-07-25 08:15 UTC, michpappas commented on lib/ukconsole/console.c
> +void uk_console_init(const void *dtb)
To avoid having different function prototypes per architecture, and to support in the future other discovery methods like ACPI, you can instead pass all instances a parameter to the bootinfo. In the case of the dtb you should get the address from there.

As discussed, that depends on #912, so please rebase and mark the dependency in the cover letter of your PR using `GitHub-Depends-On`. For reference you can see https://github.com/unikraft/unikraft/pull/988 and https://github.com/unikraft/unikraft/pull/989.

2023-07-25 08:15 UTC, michpappas commented on lib/ukconsole/include/uk/console.h
> +#if CONFIG_ARCH_X86_64
To avoid having different function prototypes per architecture, and to support in the future other discovery methods like ACPI, you can instead pass all instances a parameter to the bootinfo. In the case of the dtb you should get the address from there.

As discussed, that depends on #912, so please rebase and mark the dependency in the cover letter of your PR using `GitHub-Depends-On`. For reference you can see https://github.com/unikraft/unikraft/pull/988 and https://github.com/unikraft/unikraft/pull/989.

2023-07-25 08:15 UTC, michpappas commented on lib/ukconsole/console.c
> +int ukplat_coutk(const char *buf, unsigned int len)
These should no longer be `ukplat_`  but `uk_console`

2023-07-25 08:15 UTC, michpappas commented on plat/kvm/Makefile.uk
> +LIBKVMPLAT_SRCS-$(CONFIG_ARCH_ARM_64) += $(UK_PLAT_DRIVERS_BASE)/uart/ns16550.c
Looks like this change does not belong to this commit.

2023-07-25 08:15 UTC, michpappas commented on plat/drivers/include/uart/com.h
>  void _libkvmplat_init_serial_console(void);
COMx devices are not KVM specific: https://en.wikipedia.org/wiki/COM_(hardware_interface), so the interface provided by this driver should come with appropriate names. Also shouldn't this driver also provide a set of ops like the rest?

2023-07-25 08:15 UTC, michpappas commented on plat/drivers/uart/ns16550.c
> +int ns16550_coutk(const char *buf, unsigned int len)
These should be `static` now. In the rest of the drivers too.

2023-07-25 10:08 UTC, zhxj9823 commented on plat/drivers/include/uart/com.h
>  void _libkvmplat_init_serial_console(void);
This relates to the issue that `vga` console and `com` console are used concurrently in `unikraft/plat/kvm/x86/console.c`. In the current scheme, there can be an `ops` structure for this file. However, having a separate `ops` structure for `com` driver breaks the backward compatibility. Another choice is to enable multiple consoles instead of only using one.

2023-07-25 15:35 UTC, zhxj9823 commented on lib/ukconsole/console.c
> +#if CONFIG_ARCH_X86_64
In this case, would it make sense to divide the `.h` and `.c` files? For the `console.h` file, the ANSI characters and console APIs are used in different cases. For the `console.c` file, it can be divided into the arch-specific `console_init` function and the other three arch-independent functions.

2023-08-01 04:48 UTC, michpappas commented
I had a brief look on how the reg-shift and width for the `earlycon` are specified on linux. There these are not compiled in, but rather derived from the command-line options:
* https://www.kernel.org/doc/html/v4.14/admin-guide/kernel-parameters.html
* https://elixir.bootlin.com/linux/latest/source/drivers/tty/serial/earlycon.c#L93

The latter derives the regshift from the mmio width, ie 0 by default, 1 for MMIO16, and 2 for MMIO32 access. Right now we use 16-bit access and a regshift of 2 which doesn't make sense. @kubanrob should that be 32-bit access instead? Also would the command line be a valid option for earlycon in your case, assuming we implemented that? I imagine that since it's used on linux, it should be no problem for Unikraft.

2023-08-07 15:03 UTC, michpappas commented
Hi @zhxj9823. I opened a PR with some changes to introduce a drivers subsystem #1023, and migrated the `pl011` and `ns16550` drivers there (#1025 and #1026). You can update this PR to move the COM and VGA console drivers to `drivers/uktty` using `pl011` as a template. Moveover, please rename this library from `ukconsole` to `uktty`.

You can also consider refactoring the current PR to register the `pl011` and `ns16550` drivers as platform drivers using the `PF_REGISTER_DRIVER` of the the platform bus (see `plat/common/include/platform_bus.h`). That will allow you to remove the dts probing from this library and replace it with a `uktty_init()` that the drivers will call on `add_device` to pass their ops to the `uktty` library.

2024-08-01 02:13 UTC, michpappas commented
Obsoleted by #1464

2024-08-01 02:13 UTC, closed without merging