arch/x86_64: Paging code - Enclose params of function-like macros in brackets
unikraft/unikraft pull request #987
Opened 2023-07-23 18:46 UTC by cppstef

Minor improvement in paging code: enclosed params of function-like macros in brackets to account for expressions that mess with operator precedence where the param is used within the macro.

2023-07-24 19:09 UTC, razvand requested changes
Hi, @cppstef , please follow the guidelines on formatting your commit. Please also add a detailed description to motivate your changes.

2023-07-30 13:16 UTC, RaduNichita requested changes
Nice work, @cppstef 

Please sign off with your real email address in the commit message. For now, it is something default, provided by Github.

You can find information [here](https://support.atlassian.com/bitbucket-cloud/docs/configure-your-dvcs-username-for-commits/) about how to do that.

2023-07-31 20:32 UTC, RaduNichita approved these changes
All good from my side.

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

2023-08-06 15:43 UTC, maniatro111 approved these changes
Looks good to me. Thank you!

Reviewed-by: Florin Postolache <florin.postolache.of@gmail.com>

2023-08-09 12:29 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-08-09 16:11 UTC, closed without merging