lib/vfscore: Accept negative timestamps
unikraft/unikraft pull request #991
Opened 2023-07-24 21:01 UTC by andreittr

### Description of changes

Previously vfs code would reject timestamps that are more than 1 second before the epoch as invalid. This is wrong; unix time is defined as a signed offset and as such can and must support dates before the epoch. This change relaxes the overly-strict validity check, allowing the full range of valid file timestamps to be used.

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s): N/A
 - Application(s): N/A

### Additional configuration

Test with:
```
struct utimbuf t = {-1, -1};
int r = utime("file", &t);
if (r) perror("Bug in utime");
```

2023-08-06 15:51 UTC, StefanJum requested changes
@andreittr the changes make sense, but shouldn't they be made in [`is_timeval_valid`](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/syscalls.c#L1297) too (since that is the function that is eventually called by the `utime` syscall)?

2023-08-07 10:07 UTC, andreittr commented
> @andreittr the changes make sense, but shouldn't they be made in [`is_timeval_valid`](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/syscalls.c#L1297) too (since that is the function that is eventually called by the `utime` syscall)?

Good catch, thanks! Updated with fix.

2023-08-08 15:40 UTC, StefanJum approved these changes
All good, thank you.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-08-09 06:21 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-08-09 07:29 UTC, closed without merging