lib/ramfs: Ensure stability of inode numbers
unikraft/unikraft pull request #996
Opened 2023-07-24 21:21 UTC by andreittr

### Description of changes

Previously ramfs would assign a new unique inode number to a file on every successful filesystem lookup. This can lead to the same file being allocated multiple different inodes, breaking code that (correctly) uses inodes as reliable indicators of file identity.
This change makes inode numbers persistent, allocated along with the filesystem node, and stable across multiple lookups of the same file.

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s): N/A
 - Application(s): N/A

### Additional configuration

Test with:
```
int f = open("file", O_RDONLY);
fstat(f, &st1);
stat("file", &st2);
printf("Should be same: %ld %ld\n", st1.st_ino, st2.st_ino);
```

2023-07-25 22:16 UTC, RaduNichita requested changes
This seems OK, thanks @andreittr! I left some minor nitpicks

2023-07-25 22:16 UTC, RaduNichita commented on lib/ramfs/ramfs.h
> +	uint64_t rn_ino;
Please add a comment about the need for this member in the structure.

2023-07-25 22:16 UTC, RaduNichita commented on lib/ramfs/ramfs_vnops.c
> +	np->rn_ino = inode_count++;
Why have an empty line before?

2023-07-30 10:48 UTC, RaduNichita commented
@andreittr, is it intended to open the file without the `O_CREAT` flag?

2023-08-02 11:16 UTC, andreittr commented
> @andreittr, is it intended to open the file without the `O_CREAT` flag?
> 
> I am asking this since for Linux, it creates a file, but the inode number differs at the second attempt or running (0 vs a large number).

Yes, the test snippet assumes "file" exists and is a regular file created ahead of time (e.g. already included in the ramfs/initrd)

2023-08-02 11:57 UTC, mariasfiraiala commented
@andreittr The changes look fine, however I wasn't able to reproduce the issue. Could you please share a bit more regarding your setup?

This is what I've tested:

```C
int main(void)
{
	struct stat st1 = {0};
	struct stat st2 = {0};

	int f = open("file", O_CREAT);
	fstat(f, &st1);
	stat("file", &st2);
	printf("Should be same: %ld %ld\n", st1.st_ino, st2.st_ino);
}
```

And this is the output:

![ttr-inode](https://github.com/unikraft/unikraft/assets/94474066/d2265793-4e73-4bb0-8b83-98f2731468c2)

Notice how the [break point at which the static variable should be incremented](https://github.com/unikraft/unikraft/blob/staging/lib/ramfs/ramfs_vnops.c#L233) is reached only once.

2023-08-02 12:25 UTC, andreittr commented
> @andreittr The changes look fine, however I wasn't able to reproduce the issue. Could you please share a bit more regarding your setup?
> 
> This is what I've tested:
> 
> ```c
> int main(void)
> {
> 	struct stat st1 = {0};
> 	struct stat st2 = {0};
> 
> 	int f = open("file", O_CREAT);
> 	fstat(f, &st1);
> 	stat("file", &st2);
> 	printf("Should be same: %ld %ld\n", st1.st_ino, st2.st_ino);
> }
> ```
> 
> And this is the output:
> 
> ![ttr-inode](https://user-images.githubusercontent.com/94474066/257804110-d2265793-4e73-4bb0-8b83-98f2731468c2.png)
> 
> Notice how the [break point at which the static variable should be incremented](https://github.com/unikraft/unikraft/blob/staging/lib/ramfs/ramfs_vnops.c#L233) is reached only once.

Hi! See the above comment as well as the test snippet in the description. `open()` is not supposed to be called with `O_CREAT`, rather just with `O_RDONLY` and "file" needs to already exist. This is necessary to cause multiple FS lookups of the file, resulting in different inode numbers.

2023-08-02 14:39 UTC, andreittr commented
Pushed changes addressing comments.

2023-08-02 15:56 UTC, mariasfiraiala approved these changes
I see, all good on my side, then. Let's merge this!

Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

2023-08-02 22:24 UTC, RaduNichita commented
It works for me as well.

I used something more hackish:

```console
int main(void)
{
        struct stat st1, st2;
        int f = open("file", O_CREAT);
        fstat(f, &st1);
        close(f);

        f = open("file", O_RDONLY);
        stat("file", &st2);
        printf("Should be same: %ld %ld\n", st1.st_ino, st2.st_ino);
        close(f);
        return 0;
}
```

but it does the trick 

Thanks, @andreittr 

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

2023-08-02 22:38 UTC, RaduNichita approved these changes

2023-08-05 05:39 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-08-07 17:13 UTC, closed without merging